//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 202.147359 on Stable branch
// Generated with ALiVE version 1.13.2.2102061
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class B_VirjuansiAF_WDL {
        displayName = "Rarefield Air Cavalry";
        side = 1;
        flag = "WS_MISC\data\markers\flags\rare_calv_ca.paa";
        icon = "WS_MISC\data\markers\flags\rare_calv_ca.paa";
        priority = 0;
    };
};

class CfgGroups {
    class WEST {

        class B_VirjuansiAF_WDL {
            name = "Rarefield Air Cavalry";

            class Infantry {
                name = "Infantry";

                class b_virjuansiaf_infantry_rac_fire_team_wdl {
                    name = "RAC - Fire Team";
                    side = 1;
                    faction = "B_VirjuansiAF_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_VirjuansiAF_Rarefield_Air_Cavalry_Footsoldier_WDL_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_VirjuansiAF_Rarefield_Air_Cavalry_Footsoldier_WDL_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_VirjuansiAF_Rarefield_Air_Cavalry_Footsoldier_WDL_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_VirjuansiAF_Rarefield_Air_Cavalry_Footsoldier_WDL_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class B_Pilot_F;
    class B_Pilot_F_OCimport_01 : B_Pilot_F { scope = 0; class EventHandlers; };
    class B_Pilot_F_OCimport_02 : B_Pilot_F_OCimport_01 { class EventHandlers; };

    class B_Story_SF_Captain_F;
    class B_Story_SF_Captain_F_OCimport_01 : B_Story_SF_Captain_F { scope = 0; class EventHandlers; };
    class B_Story_SF_Captain_F_OCimport_02 : B_Story_SF_Captain_F_OCimport_01 { class EventHandlers; };

    class RAC_Z95;
    class RAC_Z95_OCimport_01 : RAC_Z95 { scope = 0; class EventHandlers; class Turrets; };
    class RAC_Z95_OCimport_02 : RAC_Z95_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };


    class B_VirjuansiAF_Rarefield_Air_Cavalry_Pilot_WDL_01 : B_Pilot_F_OCimport_02 {
        author = "Wyvern Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rarefield Air Cavalry - Pilot";
        side = 1;
        faction = "B_VirjuansiAF_WDL";

        identityTypes[] = {"Head_Russian","LanguageENG_F","G_NATO_default"};

        uniformClass = "mgsr_sneaksuit";

        linkedItems[] = {"mgsr_carrier_belt","H_PilotHelmetHeli_B","ItemMap","ItemcTab","SWLB_comlink_hush98","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"mgsr_carrier_belt","H_PilotHelmetHeli_B","ItemMap","ItemcTab","SWLB_comlink_hush98","ItemCompass","ItemWatch"};

        weapons[] = {"JLTS_DC17SA"};
        respawnWeapons[] = {"JLTS_DC17SA"};

        magazines[] = {"JLTS_DC17SA_mag","JLTS_DC17SA_mag"};
        respawnMagazines[] = {"JLTS_DC17SA_mag","JLTS_DC17SA_mag"};

        backpack = "ACE_NonSteerableParachute";

        ALiVE_orbatCreator_loadout[] = {{},{},{"JLTS_DC17SA","","","",{"JLTS_DC17SA_mag",20},{"JLTS_stun_mag_short",10},""},{"mgsr_sneaksuit",{{"FirstAidKit",1},{"JLTS_DC17SA_mag",2,20}}},{"mgsr_carrier_belt",{{"JLTS_ids_gar_army",1},{"ACE_elasticBandage",10},{"ACE_fieldDressing",5},{"ACE_packingBandage",10},{"ACE_epinephrine",2},{"ItemcTabHCam",1},{"ACE_HuntIR_monitor",1},{"ACE_IR_Strobe_Item",1},{"ACE_microDAGR",1},{"ACE_MapTools",1},{"ACE_morphine",3}}},{"ACE_NonSteerableParachute",{}},"H_PilotHelmetHeli_B","G_Balaclava_TI_blk_F",{},{"ItemMap","ItemcTab","SWLB_comlink_hush98","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_VirjuansiAF_Rarefield_Air_Cavalry_Footsoldier_WDL_01 : B_VirjuansiAF_Rarefield_Air_Cavalry_Pilot_WDL_01 {
        author = "Wyvern Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rarefield Air Cavalry - Footsoldier";
        side = 1;
        faction = "B_VirjuansiAF_WDL";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "mgsr_sneaksuit";

        linkedItems[] = {"mgsr_vest_black","OPTRE_UNSC_VX16_Helmet_Mask","ItemMap","ItemcTab","SWLB_comlink_hush98","ItemCompass","ItemWatch","JLTS_CloneNVGCC_KS"};
        respawnlinkedItems[] = {"mgsr_vest_black","OPTRE_UNSC_VX16_Helmet_Mask","ItemMap","ItemcTab","SWLB_comlink_hush98","ItemCompass","ItemWatch","JLTS_CloneNVGCC_KS"};

        weapons[] = {"JLTS_DC15S"};
        respawnWeapons[] = {"JLTS_DC15S"};

        magazines[] = {"JLTS_DC15A_mag","JLTS_stun_mag_short","JLTS_DC15A_mag","JLTS_stun_mag_short"};
        respawnMagazines[] = {"JLTS_DC15A_mag","JLTS_stun_mag_short","JLTS_DC15A_mag","JLTS_stun_mag_short"};

        backpack = "ls_mandalorian_light_backpack";

        ALiVE_orbatCreator_loadout[] = {{"JLTS_DC15S","","","",{"JLTS_DC15A_mag",60},{"JLTS_stun_mag_short",10},""},{},{},{"mgsr_sneaksuit",{{"FirstAidKit",1}}},{"mgsr_vest_black",{{"JLTS_ids_gar_army",1},{"ACE_elasticBandage",10},{"ACE_packingBandage",5},{"ACE_epinephrine",2},{"ItemcTabHCam",1},{"ACE_HuntIR_monitor",1},{"ACE_IR_Strobe_Item",1},{"ACE_microDAGR",1},{"ACE_MapTools",1},{"ACE_morphine",3},{"ACE_fieldDressing",5},{"ACE_EntrenchingTool",1}}},{"ls_mandalorian_light_backpack",{{"JLTS_DC15S_mag",9,80},{"JLTS_stun_mag_short",2,10},{"442_thermal_det_mag",2,1}}},"OPTRE_UNSC_VX16_Helmet_Mask","G_Balaclava_TI_blk_F",{},{"ItemMap","ItemcTab","SWLB_comlink_hush98","ItemCompass","ItemWatch","JLTS_CloneNVGCC_KS"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_VirjuansiAF_Rarefield_Air_Cavalry_Antoc_Merrick_WDL_01 : B_Story_SF_Captain_F_OCimport_02 {
        author = "Wyvern Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rarefield Air Cavalry - Antoc Merrick";
        side = 1;
        faction = "B_VirjuansiAF_WDL";

        identityTypes[] = {"Head_Russian","Miller","G_NATO_default"};

        uniformClass = "mgsr_sneaksuit";

        linkedItems[] = {"mgsr_vest_black","H_HeadBandage_bloody_F","ItemMap","ItemcTab","SWLB_comlink_hush98","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"mgsr_vest_black","H_HeadBandage_bloody_F","ItemMap","ItemcTab","SWLB_comlink_hush98","ItemCompass","ItemWatch"};

        weapons[] = {"JLTS_DC17SA"};
        respawnWeapons[] = {"JLTS_DC17SA"};

        magazines[] = {"JLTS_DC17SA_mag","JLTS_DC17SA_mag"};
        respawnMagazines[] = {"JLTS_DC17SA_mag","JLTS_DC17SA_mag"};

        backpack = "B_LegStrapBag_black_F";

        ALiVE_orbatCreator_loadout[] = {{},{},{"JLTS_DC17SA","","","",{"JLTS_DC17SA_mag",20},{},""},{"mgsr_sneaksuit",{{"FirstAidKit",1},{"JLTS_DC17SA_mag",2,20}}},{"mgsr_vest_black",{{"JLTS_ids_gar_army",1},{"ACE_elasticBandage",10},{"ACE_fieldDressing",5},{"ACE_packingBandage",10},{"ACE_epinephrine",2},{"ItemcTabHCam",1},{"ACE_HuntIR_monitor",1},{"ACE_IR_Strobe_Item",1},{"ACE_microDAGR",1},{"ACE_MapTools",1},{"ACE_morphine",3},{"JLTS_ids_gar_navy",1},{"JLTS_intel_datacard",1}}},{"B_LegStrapBag_black_F",{}},"H_HeadBandage_bloody_F","G_Aviator",{},{"ItemMap","ItemcTab","SWLB_comlink_hush98","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_VirjuansiAF_Z95_Headhunter_WDL_01 : RAC_Z95_OCimport_02 {
        author = "Wyvern Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "Z-95 Headhunter";
        side = 1;
        faction = "B_VirjuansiAF_WDL";
        crew = "B_VirjuansiAF_Rarefield_Air_Cavalry_Pilot_WDL_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};