//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 204.147719 on Stable branch
// Generated with ALiVE version 1.14.1.2105061
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class O_VCArmy_WDL {
        displayName = "The Vakir Collective";
        side = 0;
        flag = "\OPTRE_Core\Data\flag_Ins_ca.paa";
        icon = "\OPTRE_Core\Data\flag_Ins_ca.paa";
        priority = 0;
    };
};

class CfgGroups {
    class EAST {

        class O_VCArmy_WDL {
            name = "The Vakir Collective";

            class Infantry {
                name = "Infantry";

                class o_vcarmy_infantry_fireteam_wdl {
                    name = "Fireteam";
                    side = 0;
                    faction = "O_VCArmy_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_VCArmy_Rifleman_WDL_01";
                    };
                    class Unit1 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_VCArmy_Rifleman_WDL_01";
                    };
                    class Unit2 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_VCArmy_Rifleman_WDL_01";
                    };
                    class Unit3 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_VCArmy_Rifleman_WDL_01";
                    };
                };

                class o_vcarmy_infantry_squad_wdl {
                    name = "Squad";
                    side = 0;
                    faction = "O_VCArmy_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_VCArmy_Squad_Leader_WDL_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_VCArmy_Rifleman_WDL_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_VCArmy_Medic_WDL_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_VCArmy_Rifleman_WDL_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_VCArmy_Rifleman_WDL_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_VCArmy_Rifleman_WDL_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_VCArmy_Rifleman_WDL_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_VCArmy_Rifleman_WDL_01";
                    };
                };

                class o_vcarmy_infantry_urban_assault_team_wdl {
                    name = "Urban Assault Team";
                    side = 0;
                    faction = "O_VCArmy_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_VCArmy_Rifleman_WDL_02";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_VCArmy_Rifleman_WDL_02";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_VCArmy_Rifleman_WDL_02";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_VCArmy_Rifleman_WDL_02";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_VCArmy_Rifleman_WDL_02";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_VCArmy_Rifleman_WDL_02";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class O_Soldier_F;
    class O_Soldier_F_OCimport_01 : O_Soldier_F { scope = 0; class EventHandlers; };
    class O_Soldier_F_OCimport_02 : O_Soldier_F_OCimport_01 { class EventHandlers; };

    class O_soldierU_F;
    class O_soldierU_F_OCimport_01 : O_soldierU_F { scope = 0; class EventHandlers; };
    class O_soldierU_F_OCimport_02 : O_soldierU_F_OCimport_01 { class EventHandlers; };

    class OPTRE_M12_LRV;
    class OPTRE_M12_LRV_OCimport_01 : OPTRE_M12_LRV { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_M12_LRV_OCimport_02 : OPTRE_M12_LRV_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoGunner_1;
            class MainTurret;
        };
    };

    class OPTRE_M813_TT;
    class OPTRE_M813_TT_OCimport_01 : OPTRE_M813_TT { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_M813_TT_OCimport_02 : OPTRE_M813_TT_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoGunner_1;
            class CargoGunner_02;
            class CargoGunner_03;
            class CargoGunner_04;
            class CargoGunner_05;
            class CargoGunner_06;
            class CargoGunner_07;
        };
    };

    class OPTRE_UNSC_falcon_unarmed;
    class OPTRE_UNSC_falcon_unarmed_OCimport_01 : OPTRE_UNSC_falcon_unarmed { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_UNSC_falcon_unarmed_OCimport_02 : OPTRE_UNSC_falcon_unarmed_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
        };
    };


    class O_VCArmy_Rifleman_WDL_01 : O_Soldier_F_OCimport_02 {
        author = "LTC Denver";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman";
        side = 0;
        faction = "O_VCArmy_WDL";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "mgsr_fatigues_letni";

        linkedItems[] = {"mgsr_vest_black","H_HelmetAggressor_F","ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch","NVGogglesB_blk_F"};
        respawnlinkedItems[] = {"mgsr_vest_black","H_HelmetAggressor_F","ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch","NVGogglesB_blk_F"};

        weapons[] = {"OPTRE_M392_DMR"};
        respawnWeapons[] = {"OPTRE_M392_DMR"};

        magazines[] = {"OPTRE_15Rnd_762x51_Mag","OPTRE_15Rnd_762x51_Mag"};
        respawnMagazines[] = {"OPTRE_15Rnd_762x51_Mag","OPTRE_15Rnd_762x51_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M392_DMR","","","OPTRE_M392_Scope",{"OPTRE_15Rnd_762x51_Mag",15},{},""},{},{},{"mgsr_fatigues_letni",{{"ACE_elasticBandage",3},{"ACE_fieldDressing",6},{"ACE_packingBandage",6},{"ACE_epinephrine",2},{"ACE_morphine",1},{"ACE_tourniquet",2}}},{"mgsr_vest_black",{{"OPTRE_15Rnd_762x51_Mag",8,15},{"OPTRE_M9_Frag",1,1}}},{},"H_HelmetAggressor_F","G_Balaclava_TI_blk_F",{},{"ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch","NVGogglesB_blk_F"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_emblems_hornet'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_emblems_hornet";

    };

    class O_VCArmy_Officer_WDL_01 : O_VCArmy_Rifleman_WDL_01 {
        author = "LTC Denver";
        scope = 2;
        scopeCurator = 2;
        displayName = "Officer";
        side = 0;
        faction = "O_VCArmy_WDL";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "mgsr_fatigues_letni";

        linkedItems[] = {"mgsr_vest_black","H_MilCap_grn","ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch","OPTRE_NVG"};
        respawnlinkedItems[] = {"mgsr_vest_black","H_MilCap_grn","ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch","OPTRE_NVG"};

        weapons[] = {"OPTRE_M392_DMR","optre_hgun_comet_F"};
        respawnWeapons[] = {"OPTRE_M392_DMR","optre_hgun_comet_F"};

        magazines[] = {"OPTRE_15Rnd_762x51_Mag","4Rnd_454Casull","OPTRE_15Rnd_762x51_Mag","4Rnd_454Casull"};
        respawnMagazines[] = {"OPTRE_15Rnd_762x51_Mag","4Rnd_454Casull","OPTRE_15Rnd_762x51_Mag","4Rnd_454Casull"};

        backpack = "B_LegStrapBag_black_F";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M392_DMR","","","OPTRE_M392_Scope",{"OPTRE_15Rnd_762x51_Mag",15},{},""},{},{"optre_hgun_comet_F","","","optic_Yorris",{"4Rnd_454Casull",4},{},""},{"mgsr_fatigues_letni",{{"ACE_elasticBandage",3},{"ACE_fieldDressing",6},{"ACE_packingBandage",6},{"ACE_epinephrine",2},{"ACE_morphine",1},{"ACE_tourniquet",2}}},{"mgsr_vest_black",{{"OPTRE_15Rnd_762x51_Mag",8,15},{"OPTRE_M9_Frag",1,1}}},{"B_LegStrapBag_black_F",{{"4Rnd_454Casull",4,4}}},"H_MilCap_grn","G_Aviator",{},{"ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_emblems_hornet'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_emblems_hornet";

    };

    class O_VCArmy_Sniper_WDL_01 : O_VCArmy_Rifleman_WDL_01 {
        author = "LTC Denver";
        scope = 2;
        scopeCurator = 2;
        displayName = "Sniper";
        side = 0;
        faction = "O_VCArmy_WDL";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "mgsr_fatigues_letni";

        linkedItems[] = {"mgsr_vest_black","H_Booniehat_mgrn","ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch","OPTRE_NVG"};
        respawnlinkedItems[] = {"mgsr_vest_black","H_Booniehat_mgrn","ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch","OPTRE_NVG"};

        weapons[] = {"OPTRE_SRS99C","OPTRE_M6B"};
        respawnWeapons[] = {"OPTRE_SRS99C","OPTRE_M6B"};

        magazines[] = {"OPTRE_4Rnd_145x114_APFSDS_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_4Rnd_145x114_APFSDS_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_4Rnd_145x114_APFSDS_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_4Rnd_145x114_APFSDS_Mag","OPTRE_8Rnd_127x40_Mag"};

        backpack = "B_Messenger_Black_F";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_SRS99C","","","OPTRE_SRS99C_Scope",{"OPTRE_4Rnd_145x114_APFSDS_Mag",4},{},""},{},{"OPTRE_M6B","","","",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"mgsr_fatigues_letni",{{"ACE_elasticBandage",3},{"ACE_fieldDressing",6},{"ACE_packingBandage",6},{"ACE_epinephrine",2},{"ACE_morphine",1},{"ACE_tourniquet",2}}},{"mgsr_vest_black",{{"OPTRE_M9_Frag",1,1},{"OPTRE_4Rnd_145x114_APFSDS_Mag",3,4},{"OPTRE_8Rnd_127x40_Mag",4,8}}},{"B_Messenger_Black_F",{{"OPTRE_4Rnd_145x114_APFSDS_Mag",3,4},{"OPTRE_4Rnd_145x114_HVAP_Mag",3,4},{"ACE_HandFlare_White",1,1}}},"H_Booniehat_mgrn","OPTRE_EyePiece",{},{"ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_emblems_hornet'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_emblems_hornet";

    };

    class O_VCArmy_Squad_Leader_WDL_01 : O_VCArmy_Rifleman_WDL_01 {
        author = "LTC Denver";
        scope = 2;
        scopeCurator = 2;
        displayName = "Squad Leader";
        side = 0;
        faction = "O_VCArmy_WDL";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "mgsr_fatigues_letni";

        linkedItems[] = {"mgsr_vest_black","H_MilCap_grn","ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch","OPTRE_NVG"};
        respawnlinkedItems[] = {"mgsr_vest_black","H_MilCap_grn","ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch","OPTRE_NVG"};

        weapons[] = {"OPTRE_M392_DMR"};
        respawnWeapons[] = {"OPTRE_M392_DMR"};

        magazines[] = {"OPTRE_15Rnd_762x51_Mag","OPTRE_15Rnd_762x51_Mag"};
        respawnMagazines[] = {"OPTRE_15Rnd_762x51_Mag","OPTRE_15Rnd_762x51_Mag"};

        backpack = "B_RadioBag_01_eaf_F";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M392_DMR","","","OPTRE_M392_Scope",{"OPTRE_15Rnd_762x51_Mag",15},{},""},{},{},{"mgsr_fatigues_letni",{{"ACE_elasticBandage",3},{"ACE_fieldDressing",6},{"ACE_packingBandage",6},{"ACE_epinephrine",2},{"ACE_morphine",1},{"ACE_tourniquet",2}}},{"mgsr_vest_black",{{"OPTRE_15Rnd_762x51_Mag",8,15},{"OPTRE_M9_Frag",1,1}}},{"B_RadioBag_01_eaf_F",{}},"H_MilCap_grn","G_Aviator",{},{"ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_emblems_hornet'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_emblems_hornet";

    };

    class O_VCArmy_Medic_WDL_01 : O_VCArmy_Rifleman_WDL_01 {
        author = "LTC Denver";
        scope = 2;
        scopeCurator = 2;
        displayName = "Medic";
        side = 0;
        faction = "O_VCArmy_WDL";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "mgsr_fatigues_letni";

        linkedItems[] = {"mgsr_vest_black","H_HelmetAggressor_F","ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch","NVGogglesB_blk_F"};
        respawnlinkedItems[] = {"mgsr_vest_black","H_HelmetAggressor_F","ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch","NVGogglesB_blk_F"};

        weapons[] = {"OPTRE_M392_DMR"};
        respawnWeapons[] = {"OPTRE_M392_DMR"};

        magazines[] = {"OPTRE_15Rnd_762x51_Mag","OPTRE_15Rnd_762x51_Mag"};
        respawnMagazines[] = {"OPTRE_15Rnd_762x51_Mag","OPTRE_15Rnd_762x51_Mag"};

        backpack = "OPTRE_ILCS_Rucksack_Medical";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M392_DMR","","","OPTRE_M392_Scope",{"OPTRE_15Rnd_762x51_Mag",15},{},""},{},{},{"mgsr_fatigues_letni",{{"ACE_elasticBandage",3},{"ACE_fieldDressing",6},{"ACE_packingBandage",6},{"ACE_epinephrine",2},{"ACE_morphine",1},{"ACE_tourniquet",2}}},{"mgsr_vest_black",{{"OPTRE_15Rnd_762x51_Mag",8,15},{"OPTRE_M9_Frag",1,1}}},{"OPTRE_ILCS_Rucksack_Medical",{{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_quikclot",15},{"ACE_packingBandage",25},{"ACE_elasticBandage",25},{"ACE_fieldDressing",20},{"ACE_salineIV",2},{"ACE_salineIV_500",2},{"ACE_salineIV_250",4},{"ACE_splint",4},{"ACE_tourniquet",8},{"ACE_surgicalKit",1},{"adv_aceCPR_AED",1}}},"H_HelmetAggressor_F","G_Balaclava_TI_blk_F",{},{"ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch","NVGogglesB_blk_F"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_emblems_hornet'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_emblems_hornet";

    };

    class O_VCArmy_Rifleman_WDL_02 : O_soldierU_F_OCimport_02 {
        author = "LTC Denver";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman";
        side = 0;
        faction = "O_VCArmy_WDL";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "mgsr_fatigues_short_letni";

        linkedItems[] = {"mgsr_vest_black","H_MilCap_grn","ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"mgsr_vest_black","H_MilCap_grn","ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_MA37K"};
        respawnWeapons[] = {"OPTRE_MA37K"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_32Rnd_762x51_Mag"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_32Rnd_762x51_Mag"};

        backpack = "B_Messenger_Black_F";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA37K","","","OPTRE_M12_Optic",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{},{},{"mgsr_fatigues_short_letni",{{"ACE_elasticBandage",3},{"ACE_fieldDressing",6},{"ACE_packingBandage",6},{"ACE_epinephrine",2},{"ACE_morphine",1},{"ACE_tourniquet",2}}},{"mgsr_vest_black",{{"OPTRE_M9_Frag",2,1},{"OPTRE_M2_Smoke",2,1},{"SmokeShellYellow",1,1},{"OPTRE_32Rnd_762x51_Mag",6,32}}},{"B_Messenger_Black_F",{{"ACE_CableTie",3},{"ACE_bodyBag",2},{"ACE_SpraypaintBlack",1},{"OPTRE_32Rnd_762x51_Mag",2,32}}},"H_MilCap_grn","G_Bandanna_blk",{},{"ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_emblems_hornet'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_emblems_hornet";

    };

    class O_VCArmy_M12_LRV_MG_WDL_01 : OPTRE_M12_LRV_OCimport_02 {
        author = "LTC Denver";
        scope = 2;
        scopeCurator = 2;
        displayName = "M12 LRV [MG]";
        side = 0;
        faction = "O_VCArmy_WDL";
        crew = "O_VCArmy_Rifleman_WDL_01";

        class Turrets : Turrets {
            class CargoGunner_1 : CargoGunner_1 { gunnerType = "O_VCArmy_Rifleman_WDL_01"; };
            class MainTurret : MainTurret { gunnerType = "O_VCArmy_Rifleman_WDL_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\OPTRE_Vehicles\Warthog\data\woodland\M12HogMaav_extupper_wood_co.paa'];_unit setObjectTextureGlobal [1,'\OPTRE_Vehicles\Warthog\data\woodland\M12HogMaav_extunder_wood_co.paa'];_unit setObjectTextureGlobal [2,'\OPTRE_Vehicles\Warthog\data\turrets\m12_turret_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "colorwood";

    };

    class O_VCArmy_M813_TT_WDL_01 : OPTRE_M813_TT_OCimport_02 {
        author = "LTC Denver";
        scope = 2;
        scopeCurator = 2;
        displayName = "M813 TT";
        side = 0;
        faction = "O_VCArmy_WDL";
        crew = "O_VCArmy_Rifleman_WDL_02";

        class Turrets : Turrets {
            class CargoGunner_1 : CargoGunner_1 { gunnerType = "O_VCArmy_Rifleman_WDL_02"; };
            class CargoGunner_02 : CargoGunner_02 { gunnerType = "O_VCArmy_Rifleman_WDL_02"; };
            class CargoGunner_03 : CargoGunner_03 { gunnerType = "O_VCArmy_Rifleman_WDL_02"; };
            class CargoGunner_04 : CargoGunner_04 { gunnerType = "O_VCArmy_Medic_WDL_01"; };
            class CargoGunner_05 : CargoGunner_05 { gunnerType = "O_VCArmy_Rifleman_WDL_02"; };
            class CargoGunner_06 : CargoGunner_06 { gunnerType = "O_VCArmy_Rifleman_WDL_02"; };
            class CargoGunner_07 : CargoGunner_07 { gunnerType = "O_VCArmy_Medic_WDL_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\OPTRE_Vehicles\Warthog\data\woodland\M12HogMaav_extupper_wood_co.paa'];_unit setObjectTextureGlobal [1,'\OPTRE_Vehicles\Warthog\data\woodland\M12HogMaav_extunder_wood_co.paa'];_unit setObjectTextureGlobal [2,'\OPTRE_Vehicles\Warthog\data\woodland\transp_lopo_wood_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "colorwood";

    };

    class O_VCArmy_UH_144_Falcon_WDL_01 : OPTRE_UNSC_falcon_unarmed_OCimport_02 {
        author = "LTC Denver";
        scope = 2;
        scopeCurator = 2;
        displayName = "UH-144 Falcon";
        side = 0;
        faction = "O_VCArmy_WDL";
        crew = "OPTRE_UNSC_Airforce_Soldier_Airman";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'OPTRE_Vehicles\Falcon\data\falcon_hull_CO.paa'];_unit setObjectTextureGlobal [1,'optre_vehicles\falcon\data\falcon_hullextra_co.paa'];_unit setObjectTextureGlobal [2,'optre_vehicles\falcon\data\falcon_wingtips_co.paa'];_unit setObjectTextureGlobal [3,'optre_vehicles\falcon\data\falcon_skid_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "colorgreen";

    };

    class O_VCArmy_Pilot_WDL_01 : O_VCArmy_Rifleman_WDL_01 {
        author = "LTC Denver";
        scope = 2;
        scopeCurator = 2;
        displayName = "Pilot";
        side = 0;
        faction = "O_VCArmy_WDL";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "mgsr_fatigues_letni";

        linkedItems[] = {"mgsr_vest_black","H_Cap_headphones","ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch","OPTRE_NVG"};
        respawnlinkedItems[] = {"mgsr_vest_black","H_Cap_headphones","ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch","OPTRE_NVG"};

        weapons[] = {"optre_hgun_comet_F"};
        respawnWeapons[] = {"optre_hgun_comet_F"};

        magazines[] = {"4Rnd_454Casull","4Rnd_454Casull"};
        respawnMagazines[] = {"4Rnd_454Casull","4Rnd_454Casull"};

        backpack = "B_LegStrapBag_black_F";

        ALiVE_orbatCreator_loadout[] = {{},{},{"optre_hgun_comet_F","","","optic_Yorris",{"4Rnd_454Casull",4},{},""},{"mgsr_fatigues_letni",{{"ACE_elasticBandage",3},{"ACE_fieldDressing",6},{"ACE_packingBandage",6},{"ACE_epinephrine",2},{"ACE_morphine",1},{"ACE_tourniquet",2}}},{"mgsr_vest_black",{{"OPTRE_M9_Frag",1,1}}},{"B_LegStrapBag_black_F",{{"4Rnd_454Casull",4,4}}},"H_Cap_headphones","G_Aviator",{},{"ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_emblems_hornet'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_emblems_hornet";

    };

};