//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 204.147719 on Stable branch
// Generated with ALiVE version 1.14.1.2105061
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class O_MA {
        displayName = "Misriah Armory";
        side = 0;
        flag = "\OPTRE_Core\Data\flag_UNSC_ca.paa";
        icon = "\OPTRE_Core\Data\flag_UNSC_ca.paa";
        priority = 0;
    };
};

class CfgGroups {
    class EAST {

        class O_MA {
            name = "Misriah Armory";

            class Infantry {
                name = "Infantry";

                class o_ma_infantry_security_reinforcment_squad {
                    name = "Security Reinforcment Squad";
                    side = 0;
                    faction = "O_MA";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_MA_Heavy_Security_Guard_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_MA_Heavy_Security_Guard_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_MA_Heavy_Security_Guard_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_MA_Heavy_Security_Guard_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_MA_Heavy_Security_Guard_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_MA_Heavy_Security_Guard_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_MA_Security_Guard_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_MA_Security_Guard_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class O_Soldier_F;
    class O_Soldier_F_OCimport_01 : O_Soldier_F { scope = 0; class EventHandlers; };
    class O_Soldier_F_OCimport_02 : O_Soldier_F_OCimport_01 { class EventHandlers; };

    class OPTRE_Ins_ER_Warlord;
    class OPTRE_Ins_ER_Warlord_OCimport_01 : OPTRE_Ins_ER_Warlord { scope = 0; class EventHandlers; };
    class OPTRE_Ins_ER_Warlord_OCimport_02 : OPTRE_Ins_ER_Warlord_OCimport_01 { class EventHandlers; };

    class O_recon_JTAC_F;
    class O_recon_JTAC_F_OCimport_01 : O_recon_JTAC_F { scope = 0; class EventHandlers; };
    class O_recon_JTAC_F_OCimport_02 : O_recon_JTAC_F_OCimport_01 { class EventHandlers; };

    class O_Story_CEO_F;
    class O_Story_CEO_F_OCimport_01 : O_Story_CEO_F { scope = 0; class EventHandlers; };
    class O_Story_CEO_F_OCimport_02 : O_Story_CEO_F_OCimport_01 { class EventHandlers; };


    class O_MA_Security_Guard_01 : O_Soldier_F_OCimport_02 {
        author = "LTC Denver";
        scope = 2;
        scopeCurator = 2;
        displayName = "Security Guard";
        side = 0;
        faction = "O_MA";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "U_Marshal";

        linkedItems[] = {"V_PlateCarrier1_blk","OPTRE_PatrolCap_Navy","ItemMap","C_UavTerminal","tf_rf7800str_1","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_PlateCarrier1_blk","OPTRE_PatrolCap_Navy","ItemMap","C_UavTerminal","tf_rf7800str_1","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_M393S_DMR","OPTRE_M6G"};
        respawnWeapons[] = {"OPTRE_M393S_DMR","OPTRE_M6G"};

        magazines[] = {"OPTRE_15Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_15Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_15Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_15Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M393S_DMR","","OPTRE_BMR_Laser","OPTRE_M393_EOTECH",{"OPTRE_15Rnd_762x51_Mag",15},{},""},{},{"OPTRE_M6G","","OPTRE_M6G_Flashlight","",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"U_Marshal",{{"OPTRE_Biofoam",3},{"ACE_CableTie",2}}},{"V_PlateCarrier1_blk",{{"ItemcTabHCam",1},{"ACE_tourniquet",4},{"OPTRE_8Rnd_127x40_Mag",4,8},{"OPTRE_15Rnd_762x51_Mag",9,15}}},{},"OPTRE_PatrolCap_Navy","",{},{"ItemMap","C_UavTerminal","tf_rf7800str_1","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'Astra'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "Astra";

    };

    class O_MA_Heavy_Security_Guard_01 : O_MA_Security_Guard_01 {
        author = "LTC Denver";
        scope = 2;
        scopeCurator = 2;
        displayName = "Heavy Security Guard";
        side = 0;
        faction = "O_MA";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "U_Marshal";

        linkedItems[] = {"V_PlateCarrier1_blk","H_PASGT_basic_black_F","ItemMap","C_UavTerminal","tf_rf7800str_1","ItemCompass","ItemWatch","OPTRE_NVG"};
        respawnlinkedItems[] = {"V_PlateCarrier1_blk","H_PASGT_basic_black_F","ItemMap","C_UavTerminal","tf_rf7800str_1","ItemCompass","ItemWatch","OPTRE_NVG"};

        weapons[] = {"OPTRE_M393S_DMR","OPTRE_M6G"};
        respawnWeapons[] = {"OPTRE_M393S_DMR","OPTRE_M6G"};

        magazines[] = {"OPTRE_15Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_15Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_15Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_15Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};

        backpack = "B_Messenger_Black_F";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M393S_DMR","","OPTRE_BMR_Laser","OPTRE_M393_EOTECH",{"OPTRE_15Rnd_762x51_Mag",15},{},""},{},{"OPTRE_M6G","","OPTRE_M6G_Flashlight","",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"U_Marshal",{{"OPTRE_Biofoam",3},{"ACE_CableTie",2}}},{"V_PlateCarrier1_blk",{{"ItemcTabHCam",1},{"ACE_tourniquet",4},{"OPTRE_8Rnd_127x40_Mag",4,8},{"OPTRE_15Rnd_762x51_Mag",10,15}}},{"B_Messenger_Black_F",{{"OPTRE_M9_Frag",2,1},{"OPTRE_M2_Smoke",2,1},{"OPTRE_M2_Smoke_Blue",1,1}}},"H_PASGT_basic_black_F","G_Tactical_Clear",{},{"ItemMap","C_UavTerminal","tf_rf7800str_1","ItemCompass","ItemWatch","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'Astra'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "Astra";

    };

    class O_MA_Armed_Worker_01 : OPTRE_Ins_ER_Warlord_OCimport_02 {
        author = "LTC Denver";
        scope = 2;
        scopeCurator = 2;
        displayName = "Armed Worker";
        side = 0;
        faction = "O_MA";

        identityTypes[] = {"Head_NATO","LanguageGRE_F","Miller","Kerry","EPA_B_Northgate","EPA_B_Hardy","EPA_B_James","EPA_B_McKay","G_IRAN_default"};

        uniformClass = "U_C_ConstructionCoverall_Black_F";

        linkedItems[] = {"V_Safety_yellow_F","H_Construction_earprot_white_F","ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_Safety_yellow_F","H_Construction_earprot_white_F","ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_M6G"};
        respawnWeapons[] = {"OPTRE_M6G"};

        magazines[] = {"OPTRE_8Rnd_127x40_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_8Rnd_127x40_Mag","OPTRE_8Rnd_127x40_Mag"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"OPTRE_M6G","","","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"U_C_ConstructionCoverall_Black_F",{{"OPTRE_8Rnd_127x40_Mag",3,8}}},{"V_Safety_yellow_F",{}},{},"H_Construction_earprot_white_F","",{},{"ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_MA_Worker_01 : O_MA_Armed_Worker_01 {
        author = "LTC Denver";
        scope = 2;
        scopeCurator = 2;
        displayName = "Worker";
        side = 0;
        faction = "O_MA";

        identityTypes[] = {"Head_NATO","LanguageGRE_F","Miller","Kerry","EPA_B_Northgate","EPA_B_Hardy","EPA_B_James","EPA_B_McKay","G_IRAN_default"};

        uniformClass = "U_C_ConstructionCoverall_Black_F";

        linkedItems[] = {"V_Safety_yellow_F","H_Construction_earprot_white_F","ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_Safety_yellow_F","H_Construction_earprot_white_F","ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"U_C_ConstructionCoverall_Black_F",{}},{"V_Safety_yellow_F",{}},{},"H_Construction_earprot_white_F","",{},{"ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_MA_Bodyguard_01 : O_recon_JTAC_F_OCimport_02 {
        author = "LTC Denver";
        scope = 2;
        scopeCurator = 2;
        displayName = "Bodyguard";
        side = 0;
        faction = "O_MA";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "U_C_FormalSuit_01_black_F";

        linkedItems[] = {"ls_cis_bxCommando_vest","H_WirelessEarpiece_F","ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"ls_cis_bxCommando_vest","H_WirelessEarpiece_F","ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_MA37K"};
        respawnWeapons[] = {"OPTRE_MA37K"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_32Rnd_762x51_Mag"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_32Rnd_762x51_Mag"};

        backpack = "B_Messenger_Black_F";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA37K","","","",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{},{},{"U_C_FormalSuit_01_black_F",{{"OPTRE_32Rnd_762x51_Mag",1,32}}},{"ls_cis_bxCommando_vest",{{"OPTRE_32Rnd_762x51_Mag",4,32}}},{"B_Messenger_Black_F",{{"OPTRE_32Rnd_762x51_Mag",9,32}}},"H_WirelessEarpiece_F","G_Aviator",{},{"ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_MA_Supervisor_01 : O_Story_CEO_F_OCimport_02 {
        author = "LTC Denver";
        scope = 2;
        scopeCurator = 2;
        displayName = "Supervisor";
        side = 0;
        faction = "O_MA";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "U_C_FormalSuit_01_tshirt_gray_F";

        linkedItems[] = {"V_LegStrapBag_black_F","H_Beret_EAF_01_F","ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_LegStrapBag_black_F","H_Beret_EAF_01_F","ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_M6C"};
        respawnWeapons[] = {"OPTRE_M6C"};

        magazines[] = {"OPTRE_12Rnd_127x40_Mag","OPTRE_12Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_12Rnd_127x40_Mag","OPTRE_12Rnd_127x40_Mag"};

        backpack = "B_Messenger_Gray_F";

        ALiVE_orbatCreator_loadout[] = {{},{},{"OPTRE_M6C","OPTRE_M6C_compensator","OPTRE_M6C_Laser","OPTRE_M6C_Scope",{"OPTRE_12Rnd_127x40_Mag",12},{},""},{"U_C_FormalSuit_01_tshirt_gray_F",{{"OPTRE_12Rnd_127x40_Mag",2,12}}},{"V_LegStrapBag_black_F",{{"OPTRE_12Rnd_127x40_Mag",5,12}}},{"B_Messenger_Gray_F",{{"ACE_Cellphone",1},{"ACE_DeadManSwitch",1},{"ItemcTabHCam",1},{"ACE_Flashlight_XL50",1},{"OPTRE_Biofoam",2},{"OPTRE_Medigel",1},{"JLTS_scanner_police",1},{"JLTS_repairkit_weapon",1},{"ACE_WaterBottle_Half",1},{"ACE_wirecutter",1},{"JLTS_intel_briefcase",1},{"JLTS_intel_datapad_civ",1},{"JLTS_credits_5000",1},{"JLTS_credits_1000",2},{"JLTS_credits_100",2},{"JLTS_credits_500",2}}},"H_Beret_EAF_01_F","G_Aviator",{},{"ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};