//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 208.149102 on Stable branch
// Generated with ALiVE version 1.15.0.2112041
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class O_CIS74 {
        displayName = "[CIS] 74th ""Mudhorn"" Garrison ";
        side = 0;
        flag = "\MRC\JLTS\Core_mod_droids\data\markers\flags\cis_ca.paa";
        icon = "\MRC\JLTS\Core_mod_droids\data\markers\flags\cis_ca.paa";
        priority = 0;
    };
};

class CfgGroups {
    class EAST {

        class O_CIS74 {
            name = "[CIS] 74th ""Mudhorn"" Garrison ";

            class Infantry {
                name = "Infantry";

                class o_cis_74_infantry_squad {
                    name = "Squad";
                    side = 0;
                    faction = "O_CIS74";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_CIS_74_Squad_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Medic_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_CIS_74_Rifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Rifleman_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_AutoRifleman_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Rifleman_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Rifleman_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Rifleman_01";
                    };
                };

                class o_cis_74_infantry_squad_at {
                    name = "Squad (AT)";
                    side = 0;
                    faction = "O_CIS74";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_CIS_74_Squad_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Medic_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_CIS_74_Rifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Rifleman_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_AutoRifleman_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Rifleman_01";
                    };
                    class Unit6 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Rifleman_01";
                    };
                    class Unit7 {
                        position[] = {-15,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Rocket_Trooper_01";
                    };
                };

                class o_cis_74_infantry_squad_aa {
                    name = "Squad (AA)";
                    side = 0;
                    faction = "O_CIS74";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_CIS_74_Squad_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Medic_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_CIS_74_Rifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Rifleman_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_AutoRifleman_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Rifleman_01";
                    };
                    class Unit6 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Rifleman_01";
                    };
                    class Unit7 {
                        position[] = {-15,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Rocket_Trooper_AA_01";
                    };
                };

                class o_cis_74_infantry_raider_squad {
                    name = "Raider Squad";
                    side = 0;
                    faction = "O_CIS74";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_CIS_74_Raider_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Raider_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Raider_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Heavy_Gunner_01";
                    };
                };

                class o_cis_74_infantry_security_team {
                    name = "Security Team";
                    side = 0;
                    faction = "O_CIS74";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_CIS_74_Facility_Guard_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Facility_Guard_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Facility_Guard_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Facility_Guard_01";
                    };
                };

                class o_cis_74_infantry_naval_squad {
                    name = "Naval Squad";
                    side = 0;
                    faction = "O_CIS74";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_CIS_74_Naval_Officer_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Naval_Soldier_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Naval_Soldier_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Naval_Soldier_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Naval_Soldier_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Naval_Soldier_01";
                    };
                };

                class o_cis_74_infantry_fireteam {
                    name = "FireTeam";
                    side = 0;
                    faction = "O_CIS74";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_CIS_74_Rifleman_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Rifleman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Rifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Rifleman_01";
                    };
                };

                class o_cis_74_infantry_heavy_squad {
                    name = "Heavy Squad";
                    side = 0;
                    faction = "O_CIS74";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_CIS_74_Squad_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Raider_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Rocket_Trooper_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Rocket_Trooper_AA_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Heavy_Gunner_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_AutoRifleman_01";
                    };
                };

                class o_cis_74_infantry_vehicle_team {
                    name = "Vehicle Team";
                    side = 0;
                    faction = "O_CIS74";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_CIS_74_Vehicle_Crewman_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Vehicle_Crewman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Vehicle_Crewman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Vehicle_Crewman_01";
                    };
                };

                class o_cis_74_infantry_naval_team {
                    name = "Naval Team";
                    side = 0;
                    faction = "O_CIS74";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_CIS_74_Naval_Crewman_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Naval_Crewman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Naval_Crewman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Naval_Crewman_01";
                    };
                };

                class o_cis_74_infantry_aviation_team {
                    name = "Aviation Team";
                    side = 0;
                    faction = "O_CIS74";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_CIS_74_Pilot_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Pilot_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Pilot_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Pilot_01";
                    };
                };

                class o_cis_74_infantry_patrol_team {
                    name = "Patrol Team";
                    side = 0;
                    faction = "O_CIS74";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_CIS_74_Marksman_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Marksman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Rifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Rifleman_01";
                    };
                };

                class o_cis_74_infantry_security_team_b1 {
                    name = "Security Team (B1)";
                    side = 0;
                    faction = "O_CIS74";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_CIS_74_Security_Droid_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Security_Droid_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Security_Droid_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_Security_Droid_01";
                    };
                };

                class o_cis_74_infantry_b1_squad {
                    name = "B1 Squad";
                    side = 0;
                    faction = "O_CIS74";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_CIS_74_B1_Jungle_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_B1_Jungle_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_B1_AutoRifleman_Jungle_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_B1_Jungle_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_B1_Jungle_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_B1_Jungle_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_B1_Jungle_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_B1_Jungle_01";
                    };
                };

                class o_cis_74_infantry_b1_fireteam {
                    name = "B1 Fireteam";
                    side = 0;
                    faction = "O_CIS74";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_CIS_74_B1_Jungle_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_B1_Jungle_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_B1_Jungle_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_B1_Jungle_01";
                    };
                };

                class o_cis_74_infantry_bx_security_team {
                    name = "BX Security Team";
                    side = 0;
                    faction = "O_CIS74";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_CIS_74_BX_series_Security_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_BX_series_Security_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_BX_series_Security_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_BX_series_Security_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CIS_74_BX_series_Security_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class O_T_Soldier_F;
    class O_T_Soldier_F_OCimport_01 : O_T_Soldier_F { scope = 0; class EventHandlers; };
    class O_T_Soldier_F_OCimport_02 : O_T_Soldier_F_OCimport_01 { class EventHandlers; };

    class O_A_soldier_F;
    class O_A_soldier_F_OCimport_01 : O_A_soldier_F { scope = 0; class EventHandlers; };
    class O_A_soldier_F_OCimport_02 : O_A_soldier_F_OCimport_01 { class EventHandlers; };

    class optre_catfish_unarmed_f;
    class optre_catfish_unarmed_f_OCimport_01 : optre_catfish_unarmed_f { scope = 0; class EventHandlers; class Turrets; };
    class optre_catfish_unarmed_f_OCimport_02 : optre_catfish_unarmed_f_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
        };
    };

    class optre_catfish_mg_f;
    class optre_catfish_mg_f_OCimport_01 : optre_catfish_mg_f { scope = 0; class EventHandlers; class Turrets; };
    class optre_catfish_mg_f_OCimport_02 : optre_catfish_mg_f_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
            class MainTurret;
        };
    };

    class lsd_cis_b1_standard;
    class lsd_cis_b1_standard_OCimport_01 : lsd_cis_b1_standard { scope = 0; class EventHandlers; };
    class lsd_cis_b1_standard_OCimport_02 : lsd_cis_b1_standard_OCimport_01 { class EventHandlers; };

    class lsd_cis_bxSecurity_specops;
    class lsd_cis_bxSecurity_specops_OCimport_01 : lsd_cis_bxSecurity_specops { scope = 0; class EventHandlers; };
    class lsd_cis_bxSecurity_specops_OCimport_02 : lsd_cis_bxSecurity_specops_OCimport_01 { class EventHandlers; };


    class O_CIS_74_Rifleman_01 : O_T_Soldier_F_OCimport_02 {
        author = "CC-3572 ""Cordo""";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman";
        side = 0;
        faction = "O_CIS74";

        identityTypes[] = {"Head_TK_camo_semiarid","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "WS_74th_Trooper_F_CombatUniform";

        linkedItems[] = {"WS_TrooperCapeBelt_armor","WS_74th_Trooper_helmet","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr","OPTRE_NVG"};
        respawnlinkedItems[] = {"WS_TrooperCapeBelt_armor","WS_74th_Trooper_helmet","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr","OPTRE_NVG"};

        weapons[] = {"JLTS_E5","JMSLLTE_W_TD23_black_F"};
        respawnWeapons[] = {"JLTS_E5","JMSLLTE_W_TD23_black_F"};

        magazines[] = {"JLTS_E5_mag","Laserbatteries","JLTS_E5_mag","Laserbatteries"};
        respawnMagazines[] = {"JLTS_E5_mag","Laserbatteries","JLTS_E5_mag","Laserbatteries"};

        ALiVE_orbatCreator_loadout[] = {{"JLTS_E5","","","",{"JLTS_E5_mag",100},{},""},{},{},{"WS_74th_Trooper_F_CombatUniform",{{"ACE_elasticBandage",10},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_CableTie",2},{"ACE_epinephrine",2},{"ACE_morphine",2},{"ACE_IR_Strobe_Item",1},{"ItemcTabHCam",1},{"ACE_Flashlight_XL50",1},{"ACE_MapTools",1},{"ACE_splint",2},{"ACE_tourniquet",4},{"StimAdrenal",2},{"OPTRE_M2_Smoke",2,1},{"OPTRE_M2_Smoke_Orange",2,1}}},{"WS_TrooperCapeBelt_armor",{{"JLTS_E5_mag",9,100}}},{},"WS_74th_Trooper_helmet","G_JMSLLTE_TrooperMask_2",{"JMSLLTE_W_TD23_black_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_CIS_74_AutoRifleman_01 : O_CIS_74_Rifleman_01 {
        author = "CC-3572 ""Cordo""";
        scope = 2;
        scopeCurator = 2;
        displayName = "AutoRifleman";
        side = 0;
        faction = "O_CIS74";

        identityTypes[] = {"Head_TK_camo_semiarid","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "WS_74th_Trooper_F_CombatUniform";

        linkedItems[] = {"WS_TrooperCapeBelt_armor","WS_74th_Trooper_helmet","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr","OPTRE_NVG"};
        respawnlinkedItems[] = {"WS_TrooperCapeBelt_armor","WS_74th_Trooper_helmet","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr","OPTRE_NVG"};

        weapons[] = {"JLTS_E5C_stock","JMSLLTE_W_TD23_black_F"};
        respawnWeapons[] = {"JLTS_E5C_stock","JMSLLTE_W_TD23_black_F"};

        magazines[] = {"JLTS_E5C_mag","Laserbatteries","JLTS_E5C_mag","Laserbatteries"};
        respawnMagazines[] = {"JLTS_E5C_mag","Laserbatteries","JLTS_E5C_mag","Laserbatteries"};

        backpack = "JMSLLTE_back_sandpack_v1";

        ALiVE_orbatCreator_loadout[] = {{"JLTS_E5C_stock","","","",{"JLTS_E5C_mag",150},{},""},{},{},{"WS_74th_Trooper_F_CombatUniform",{{"ACE_elasticBandage",10},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_CableTie",2},{"ACE_epinephrine",2},{"ACE_morphine",2},{"ACE_IR_Strobe_Item",1},{"ItemcTabHCam",1},{"ACE_Flashlight_XL50",1},{"ACE_MapTools",1},{"ACE_splint",2},{"ACE_tourniquet",4},{"StimAdrenal",2},{"OPTRE_M2_Smoke",2,1},{"OPTRE_M2_Smoke_Orange",2,1},{"JLTS_E5C_mag",3,150}}},{"WS_TrooperCapeBelt_armor",{{"JLTS_E5C_mag",10,150}}},{"JMSLLTE_back_sandpack_v1",{}},"WS_74th_Trooper_helmet","G_JMSLLTE_TrooperMask_2",{"JMSLLTE_W_TD23_black_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_CIS_74_Heavy_Gunner_01 : O_CIS_74_Rifleman_01 {
        author = "CC-3572 ""Cordo""";
        scope = 2;
        scopeCurator = 2;
        displayName = "Heavy Gunner";
        side = 0;
        faction = "O_CIS74";

        identityTypes[] = {"Head_TK_camo_semiarid","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "WS_74th_Trooper_F_CombatUniform";

        linkedItems[] = {"WS_TrooperCapeBelt_armor","WS_74th_Trooper_helmet","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr","OPTRE_NVG"};
        respawnlinkedItems[] = {"WS_TrooperCapeBelt_armor","WS_74th_Trooper_helmet","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr","OPTRE_NVG"};

        weapons[] = {"JMSLLTE_DLT19BlasterRifle","JMSLLTE_W_TD23_black_F"};
        respawnWeapons[] = {"JMSLLTE_DLT19BlasterRifle","JMSLLTE_W_TD23_black_F"};

        magazines[] = {"JMSLLTE_DLT19_75Rnd_Mag","Laserbatteries","JMSLLTE_DLT19_75Rnd_Mag","Laserbatteries"};
        respawnMagazines[] = {"JMSLLTE_DLT19_75Rnd_Mag","Laserbatteries","JMSLLTE_DLT19_75Rnd_Mag","Laserbatteries"};

        backpack = "JMSLLTE_back_sandpack_v1";

        ALiVE_orbatCreator_loadout[] = {{"JMSLLTE_DLT19BlasterRifle","","","",{"JMSLLTE_DLT19_75Rnd_Mag",75},{},""},{},{},{"WS_74th_Trooper_F_CombatUniform",{{"ACE_elasticBandage",10},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_CableTie",2},{"ACE_epinephrine",2},{"ACE_morphine",2},{"ACE_IR_Strobe_Item",1},{"ItemcTabHCam",1},{"ACE_Flashlight_XL50",1},{"ACE_MapTools",1},{"ACE_splint",2},{"ACE_tourniquet",4},{"StimAdrenal",2},{"OPTRE_M2_Smoke",2,1},{"OPTRE_M2_Smoke_Orange",2,1}}},{"WS_TrooperCapeBelt_armor",{}},{"JMSLLTE_back_sandpack_v1",{{"JMSLLTE_DLT19_75Rnd_Mag",14,75}}},"WS_74th_Trooper_helmet","G_JMSLLTE_TrooperMask_1",{"JMSLLTE_W_TD23_black_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_CIS_74_Medic_01 : O_CIS_74_Rifleman_01 {
        author = "CC-3572 ""Cordo""";
        scope = 2;
        scopeCurator = 2;
        displayName = "Medic";
        side = 0;
        faction = "O_CIS74";

        identityTypes[] = {"Head_TK_camo_semiarid","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "WS_74th_Medic_F_CombatUniform";

        linkedItems[] = {"WS_TrooperCapeBelt_armor","WS_74th_Trooper_helmet","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr","OPTRE_NVG"};
        respawnlinkedItems[] = {"WS_TrooperCapeBelt_armor","WS_74th_Trooper_helmet","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr","OPTRE_NVG"};

        weapons[] = {"JLTS_E5","JMSLLTE_W_TD23_black_F"};
        respawnWeapons[] = {"JLTS_E5","JMSLLTE_W_TD23_black_F"};

        magazines[] = {"JLTS_E5_mag","Laserbatteries","JLTS_E5_mag","Laserbatteries"};
        respawnMagazines[] = {"JLTS_E5_mag","Laserbatteries","JLTS_E5_mag","Laserbatteries"};

        backpack = "JMSLLTE_back_stormpack_v1";

        ALiVE_orbatCreator_loadout[] = {{"JLTS_E5","","","",{"JLTS_E5_mag",100},{},""},{},{},{"WS_74th_Medic_F_CombatUniform",{{"ACE_elasticBandage",10},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_CableTie",2},{"ACE_epinephrine",2},{"ACE_morphine",2},{"ACE_IR_Strobe_Item",1},{"ItemcTabHCam",1},{"ACE_Flashlight_XL50",1},{"ACE_MapTools",1},{"ACE_splint",2},{"ACE_tourniquet",4},{"StimAdrenal",2},{"OPTRE_M2_Smoke",2,1},{"OPTRE_M2_Smoke_Orange",2,1}}},{"WS_TrooperCapeBelt_armor",{{"JLTS_E5_mag",9,100}}},{"JMSLLTE_back_stormpack_v1",{{"ACE_elasticBandage",25},{"ACE_fieldDressing",20},{"ACE_packingBandage",20},{"ACE_quikclot",15},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_splint",8},{"ACE_surgicalKit",1},{"ACE_salineIV_500",4},{"ACE_salineIV_250",4},{"ACE_salineIV",3}}},"WS_74th_Trooper_helmet","G_JMSLLTE_TrooperMask_3",{"JMSLLTE_W_TD23_black_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_CIS_74_Rocket_Trooper_01 : O_CIS_74_Rifleman_01 {
        author = "CC-3572 ""Cordo""";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rocket Trooper";
        side = 0;
        faction = "O_CIS74";

        identityTypes[] = {"Head_TK_camo_semiarid","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "WS_74th_Trooper_F_CombatUniform";

        linkedItems[] = {"WS_TrooperCapeBelt_armor","WS_74th_Trooper_helmet","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr","OPTRE_NVG"};
        respawnlinkedItems[] = {"WS_TrooperCapeBelt_armor","WS_74th_Trooper_helmet","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr","OPTRE_NVG"};

        weapons[] = {"JLTS_E5","JLTS_RPS6","JMSLLTE_W_TD23_black_F"};
        respawnWeapons[] = {"JLTS_E5","JLTS_RPS6","JMSLLTE_W_TD23_black_F"};

        magazines[] = {"JLTS_E5_mag","JLTS_RPS6_mag","Laserbatteries","JLTS_E5_mag","Laserbatteries"};
        respawnMagazines[] = {"JLTS_E5_mag","JLTS_RPS6_mag","Laserbatteries","JLTS_E5_mag","Laserbatteries"};

        backpack = "JMSLLTE_back_sandpack_v1";

        ALiVE_orbatCreator_loadout[] = {{"JLTS_E5","","","",{"JLTS_E5_mag",100},{},""},{"JLTS_RPS6","","","",{"JLTS_RPS6_mag",1},{},""},{},{"WS_74th_Trooper_F_CombatUniform",{{"ACE_elasticBandage",10},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_CableTie",2},{"ACE_epinephrine",2},{"ACE_morphine",2},{"ACE_IR_Strobe_Item",1},{"ItemcTabHCam",1},{"ACE_Flashlight_XL50",1},{"ACE_MapTools",1},{"ACE_splint",2},{"ACE_tourniquet",4},{"StimAdrenal",2},{"OPTRE_M2_Smoke",2,1},{"OPTRE_M2_Smoke_Orange",2,1}}},{"WS_TrooperCapeBelt_armor",{{"JLTS_E5_mag",9,100}}},{"JMSLLTE_back_sandpack_v1",{{"JLTS_RPS6_mag",2,1},{"JLTS_RPS6_HE_mag",2,1}}},"WS_74th_Trooper_helmet","G_JMSLLTE_TrooperMask_2",{"JMSLLTE_W_TD23_black_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_CIS_74_Rocket_Trooper_AA_01 : O_CIS_74_Rocket_Trooper_01 {
        author = "CC-3572 ""Cordo""";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rocket Trooper (AA)";
        side = 0;
        faction = "O_CIS74";

        identityTypes[] = {"Head_TK_camo_semiarid","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "WS_74th_Trooper_F_CombatUniform";

        linkedItems[] = {"WS_TrooperCapeBelt_armor","WS_74th_Trooper_helmet","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr","OPTRE_NVG"};
        respawnlinkedItems[] = {"WS_TrooperCapeBelt_armor","WS_74th_Trooper_helmet","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr","OPTRE_NVG"};

        weapons[] = {"JLTS_E5","SWLW_E60R_AA","JMSLLTE_W_TD23_black_F"};
        respawnWeapons[] = {"JLTS_E5","SWLW_E60R_AA","JMSLLTE_W_TD23_black_F"};

        magazines[] = {"JLTS_E5_mag","SWLW_e60r_aa_mag","Laserbatteries","JLTS_E5_mag","Laserbatteries"};
        respawnMagazines[] = {"JLTS_E5_mag","SWLW_e60r_aa_mag","Laserbatteries","JLTS_E5_mag","Laserbatteries"};

        backpack = "JMSLLTE_back_sandpack_v1";

        ALiVE_orbatCreator_loadout[] = {{"JLTS_E5","","","",{"JLTS_E5_mag",100},{},""},{"SWLW_E60R_AA","","","",{"SWLW_e60r_aa_mag",3},{},""},{},{"WS_74th_Trooper_F_CombatUniform",{{"ACE_elasticBandage",10},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_CableTie",2},{"ACE_epinephrine",2},{"ACE_morphine",2},{"ACE_IR_Strobe_Item",1},{"ItemcTabHCam",1},{"ACE_Flashlight_XL50",1},{"ACE_MapTools",1},{"ACE_splint",2},{"ACE_tourniquet",4},{"StimAdrenal",2},{"OPTRE_M2_Smoke",2,1},{"OPTRE_M2_Smoke_Orange",2,1}}},{"WS_TrooperCapeBelt_armor",{{"JLTS_E5_mag",9,100}}},{"JMSLLTE_back_sandpack_v1",{{"SWLW_e60r_aa_mag",2,3},{"Titan_AA",1,1}}},"WS_74th_Trooper_helmet","G_JMSLLTE_TrooperMask_2",{"JMSLLTE_W_TD23_black_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_CIS_74_Marksman_01 : O_CIS_74_Rifleman_01 {
        author = "CC-3572 ""Cordo""";
        scope = 2;
        scopeCurator = 2;
        displayName = "Marksman";
        side = 0;
        faction = "O_CIS74";

        identityTypes[] = {"Head_TK_camo_semiarid","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "WS_74th_Trooper_F_CombatUniform";

        linkedItems[] = {"WS_TrooperCapeBelt_armor","WS_74th_Trooper_helmet","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr","OPTRE_NVG"};
        respawnlinkedItems[] = {"WS_TrooperCapeBelt_armor","WS_74th_Trooper_helmet","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr","OPTRE_NVG"};

        weapons[] = {"JLTS_E5S","JMSLLTE_rk3pistol","JMSLLTE_W_TD23_black_F"};
        respawnWeapons[] = {"JLTS_E5S","JMSLLTE_rk3pistol","JMSLLTE_W_TD23_black_F"};

        magazines[] = {"JLTS_E5S_mag","JMSLLTE_RK3_20rnd_Mag","Laserbatteries","JLTS_E5S_mag","JMSLLTE_RK3_20rnd_Mag","Laserbatteries"};
        respawnMagazines[] = {"JLTS_E5S_mag","JMSLLTE_RK3_20rnd_Mag","Laserbatteries","JLTS_E5S_mag","JMSLLTE_RK3_20rnd_Mag","Laserbatteries"};

        ALiVE_orbatCreator_loadout[] = {{"JLTS_E5S","","","",{"JLTS_E5S_mag",20},{},""},{},{"JMSLLTE_rk3pistol","","","",{"JMSLLTE_RK3_20rnd_Mag",20},{},""},{"WS_74th_Trooper_F_CombatUniform",{{"ACE_elasticBandage",10},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_CableTie",2},{"ACE_epinephrine",2},{"ACE_morphine",2},{"ACE_IR_Strobe_Item",1},{"ItemcTabHCam",1},{"ACE_Flashlight_XL50",1},{"ACE_MapTools",1},{"ACE_splint",2},{"ACE_tourniquet",4},{"StimAdrenal",2},{"OPTRE_M2_Smoke",2,1},{"OPTRE_M2_Smoke_Orange",2,1},{"JMSLLTE_RK3_20rnd_Mag",3,20}}},{"WS_TrooperCapeBelt_armor",{{"JLTS_E5S_mag",9,20}}},{},"WS_74th_Trooper_helmet","G_JMSLLTE_TrooperMask_3",{"JMSLLTE_W_TD23_black_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_CIS_74_Squad_Leader_01 : O_CIS_74_Rifleman_01 {
        author = "CC-3572 ""Cordo""";
        scope = 2;
        scopeCurator = 2;
        displayName = "Squad Leader";
        side = 0;
        faction = "O_CIS74";

        identityTypes[] = {"Head_TK_camo_semiarid","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "WS_74th_Trooper_F_CombatUniform";

        linkedItems[] = {"WS_TrooperCapeBelt_armor","WS_74th_Trooper_helmet","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr","OPTRE_NVG"};
        respawnlinkedItems[] = {"WS_TrooperCapeBelt_armor","WS_74th_Trooper_helmet","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr","OPTRE_NVG"};

        weapons[] = {"JLTS_E5","JMSLLTE_W_TD23_black_F"};
        respawnWeapons[] = {"JLTS_E5","JMSLLTE_W_TD23_black_F"};

        magazines[] = {"JLTS_E5_mag","Laserbatteries","JLTS_E5_mag","Laserbatteries"};
        respawnMagazines[] = {"JLTS_E5_mag","Laserbatteries","JLTS_E5_mag","Laserbatteries"};

        backpack = "JMSLLTE_back_radio_v1";

        ALiVE_orbatCreator_loadout[] = {{"JLTS_E5","","","",{"JLTS_E5_mag",100},{},""},{},{},{"WS_74th_Trooper_F_CombatUniform",{{"ACE_elasticBandage",10},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_CableTie",2},{"ACE_epinephrine",2},{"ACE_morphine",2},{"ACE_IR_Strobe_Item",1},{"ItemcTabHCam",1},{"ACE_Flashlight_XL50",1},{"ACE_MapTools",1},{"ACE_splint",2},{"ACE_tourniquet",4},{"StimAdrenal",2},{"OPTRE_M2_Smoke",2,1},{"OPTRE_M2_Smoke_Orange",2,1}}},{"WS_TrooperCapeBelt_armor",{{"JLTS_E5_mag",9,100}}},{"JMSLLTE_back_radio_v1",{}},"WS_74th_Trooper_helmet","",{"JMSLLTE_W_TD23_black_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_CIS_74_Raider_01 : O_CIS_74_Rifleman_01 {
        author = "CC-3572 ""Cordo""";
        scope = 2;
        scopeCurator = 2;
        displayName = "Raider";
        side = 0;
        faction = "O_CIS74";

        identityTypes[] = {"Head_TK_camo_semiarid","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "WS_74th_Trooper_F_CombatUniform";

        linkedItems[] = {"WS_TrooperCapeBelt_armor","WS_74th_Trooper_helmet","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr","OPTRE_NVG"};
        respawnlinkedItems[] = {"WS_TrooperCapeBelt_armor","WS_74th_Trooper_helmet","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr","OPTRE_NVG"};

        weapons[] = {"JLTS_SBB3","JMSLLTE_W_TD23_black_F"};
        respawnWeapons[] = {"JLTS_SBB3","JMSLLTE_W_TD23_black_F"};

        magazines[] = {"JLTS_SBB3_mag","Laserbatteries","JLTS_SBB3_mag","Laserbatteries"};
        respawnMagazines[] = {"JLTS_SBB3_mag","Laserbatteries","JLTS_SBB3_mag","Laserbatteries"};

        ALiVE_orbatCreator_loadout[] = {{"JLTS_SBB3","","","",{"JLTS_SBB3_mag",25},{},""},{},{},{"WS_74th_Trooper_F_CombatUniform",{{"ACE_elasticBandage",10},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_CableTie",2},{"ACE_epinephrine",2},{"ACE_morphine",2},{"ACE_IR_Strobe_Item",1},{"ItemcTabHCam",1},{"ACE_Flashlight_XL50",1},{"ACE_MapTools",1},{"ACE_splint",2},{"ACE_tourniquet",4},{"StimAdrenal",2},{"OPTRE_M2_Smoke",2,1},{"OPTRE_M2_Smoke_Orange",2,1},{"JMSLLTE_thermaldetonator_HandGrenade",2,1}}},{"WS_TrooperCapeBelt_armor",{{"JLTS_SBB3_mag",8,25}}},{},"WS_74th_Trooper_helmet","G_JMSLLTE_TrooperMask_2",{"JMSLLTE_W_TD23_black_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_CIS_74_Pilot_01 : O_CIS_74_Rifleman_01 {
        author = "CC-3572 ""Cordo""";
        scope = 2;
        scopeCurator = 2;
        displayName = "Pilot";
        side = 0;
        faction = "O_CIS74";

        identityTypes[] = {"Head_TK_camo_semiarid","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "WS_74th_Pilot_CombatUniform";

        linkedItems[] = {"mgsr_vest_black","H_PilotHelmetHeli_O","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr"};
        respawnlinkedItems[] = {"mgsr_vest_black","H_PilotHelmetHeli_O","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr"};

        weapons[] = {"JMSLLTE_rk3pistol","JMSLLTE_W_TD23_black_F"};
        respawnWeapons[] = {"JMSLLTE_rk3pistol","JMSLLTE_W_TD23_black_F"};

        magazines[] = {"JMSLLTE_RK3_20rnd_Mag","Laserbatteries","JMSLLTE_RK3_20rnd_Mag","Laserbatteries"};
        respawnMagazines[] = {"JMSLLTE_RK3_20rnd_Mag","Laserbatteries","JMSLLTE_RK3_20rnd_Mag","Laserbatteries"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"JMSLLTE_rk3pistol","","","",{"JMSLLTE_RK3_20rnd_Mag",20},{},""},{"WS_74th_Pilot_CombatUniform",{{"ACE_elasticBandage",10},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_CableTie",2},{"ACE_epinephrine",2},{"ACE_morphine",2},{"ACE_IR_Strobe_Item",1},{"ItemcTabHCam",1},{"ACE_Flashlight_XL50",1},{"ACE_MapTools",1},{"ACE_splint",2},{"ACE_tourniquet",4},{"StimAdrenal",2},{"OPTRE_M2_Smoke",1,1}}},{"mgsr_vest_black",{{"JMSLLTE_RK3_20rnd_Mag",5,20}}},{},"H_PilotHelmetHeli_O","G_JMSLLTE_TrooperMask_1",{"JMSLLTE_W_TD23_black_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_CIS_74_Vehicle_Crewman_01 : O_CIS_74_Rifleman_01 {
        author = "CC-3572 ""Cordo""";
        scope = 2;
        scopeCurator = 2;
        displayName = "Vehicle Crewman";
        side = 0;
        faction = "O_CIS74";

        identityTypes[] = {"Head_TK_camo_semiarid","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "JMSLLTE_EmpTrooperCamo_F_CombatUniform";

        linkedItems[] = {"SWLB_clone_basic_armor","JMSLLTE_Tanktrooper_trooper_helmet","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr"};
        respawnlinkedItems[] = {"SWLB_clone_basic_armor","JMSLLTE_Tanktrooper_trooper_helmet","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr"};

        weapons[] = {"JMSLLTE_rk3pistol","JMSLLTE_W_TD23_black_F"};
        respawnWeapons[] = {"JMSLLTE_rk3pistol","JMSLLTE_W_TD23_black_F"};

        magazines[] = {"JMSLLTE_RK3_20rnd_Mag","Laserbatteries","JMSLLTE_RK3_20rnd_Mag","Laserbatteries"};
        respawnMagazines[] = {"JMSLLTE_RK3_20rnd_Mag","Laserbatteries","JMSLLTE_RK3_20rnd_Mag","Laserbatteries"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"JMSLLTE_rk3pistol","","","",{"JMSLLTE_RK3_20rnd_Mag",20},{},""},{"JMSLLTE_EmpTrooperCamo_F_CombatUniform",{{"ACE_elasticBandage",10},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_CableTie",2},{"ACE_epinephrine",2},{"ACE_morphine",2},{"ACE_IR_Strobe_Item",1},{"ItemcTabHCam",1},{"ACE_Flashlight_XL50",1},{"ACE_MapTools",1},{"ACE_splint",2},{"ACE_tourniquet",4},{"StimAdrenal",2},{"OPTRE_M2_Smoke",1,1}}},{"SWLB_clone_basic_armor",{{"JMSLLTE_RK3_20rnd_Mag",5,20}}},{},"JMSLLTE_Tanktrooper_trooper_helmet","",{"JMSLLTE_W_TD23_black_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_CIS_74_Naval_Crewman_01 : O_CIS_74_Rifleman_01 {
        author = "CC-3572 ""Cordo""";
        scope = 2;
        scopeCurator = 2;
        displayName = "Naval Crewman";
        side = 0;
        faction = "O_CIS74";

        identityTypes[] = {"Head_TK","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "WS_74th_Pilot_CombatUniform";

        linkedItems[] = {"WS_OfficerChest_armor","JMSLLTE_EmpOfficer_helmet","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr"};
        respawnlinkedItems[] = {"WS_OfficerChest_armor","JMSLLTE_EmpOfficer_helmet","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr"};

        weapons[] = {"JMSLLTE_rk3pistol","JMSLLTE_W_TD23_black_F"};
        respawnWeapons[] = {"JMSLLTE_rk3pistol","JMSLLTE_W_TD23_black_F"};

        magazines[] = {"JMSLLTE_RK3_20rnd_Mag","Laserbatteries","JMSLLTE_RK3_20rnd_Mag","Laserbatteries"};
        respawnMagazines[] = {"JMSLLTE_RK3_20rnd_Mag","Laserbatteries","JMSLLTE_RK3_20rnd_Mag","Laserbatteries"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"JMSLLTE_rk3pistol","","","",{"JMSLLTE_RK3_20rnd_Mag",20},{},""},{"WS_74th_Pilot_CombatUniform",{{"ACE_elasticBandage",10},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_CableTie",2},{"ACE_epinephrine",2},{"ACE_morphine",2},{"ACE_IR_Strobe_Item",1},{"ItemcTabHCam",1},{"ACE_Flashlight_XL50",1},{"ACE_MapTools",1},{"ACE_splint",2},{"ACE_tourniquet",4},{"StimAdrenal",2},{"OPTRE_M2_Smoke",1,1}}},{"WS_OfficerChest_armor",{{"JMSLLTE_RK3_20rnd_Mag",5,20}}},{},"JMSLLTE_EmpOfficer_helmet","",{"JMSLLTE_W_TD23_black_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_CIS_74_Naval_Soldier_01 : O_CIS_74_Rifleman_01 {
        author = "CC-3572 ""Cordo""";
        scope = 2;
        scopeCurator = 2;
        displayName = "Naval Soldier";
        side = 0;
        faction = "O_CIS74";

        identityTypes[] = {"Head_TK","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "WS_74th_Pilot_CombatUniform";

        linkedItems[] = {"WS_OfficerChest_armor","JMSLLTE_EmpOfficer_helmet","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr"};
        respawnlinkedItems[] = {"WS_OfficerChest_armor","JMSLLTE_EmpOfficer_helmet","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr"};

        weapons[] = {"JMSLLTE_dh17rifle","JMSLLTE_rk3pistol","JMSLLTE_W_TD23_black_F"};
        respawnWeapons[] = {"JMSLLTE_dh17rifle","JMSLLTE_rk3pistol","JMSLLTE_W_TD23_black_F"};

        magazines[] = {"JMSLLTE_DH17_60Rnd_Mag","JMSLLTE_RK3_20rnd_Mag","Laserbatteries","JMSLLTE_DH17_60Rnd_Mag","JMSLLTE_RK3_20rnd_Mag","Laserbatteries"};
        respawnMagazines[] = {"JMSLLTE_DH17_60Rnd_Mag","JMSLLTE_RK3_20rnd_Mag","Laserbatteries","JMSLLTE_DH17_60Rnd_Mag","JMSLLTE_RK3_20rnd_Mag","Laserbatteries"};

        ALiVE_orbatCreator_loadout[] = {{"JMSLLTE_dh17rifle","","JMSLLTE_acc_flashlight_reb","JMSLLTE_dh17_bl_Scope",{"JMSLLTE_DH17_60Rnd_Mag",60},{},""},{},{"JMSLLTE_rk3pistol","","","",{"JMSLLTE_RK3_20rnd_Mag",20},{},""},{"WS_74th_Pilot_CombatUniform",{{"ACE_elasticBandage",10},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_CableTie",2},{"ACE_epinephrine",2},{"ACE_morphine",2},{"ACE_IR_Strobe_Item",1},{"ItemcTabHCam",1},{"ACE_Flashlight_XL50",1},{"ACE_MapTools",1},{"ACE_splint",2},{"ACE_tourniquet",4},{"StimAdrenal",2},{"OPTRE_M2_Smoke",1,1}}},{"WS_OfficerChest_armor",{{"JMSLLTE_DH17_60Rnd_Mag",8,60}}},{},"JMSLLTE_EmpOfficer_helmet","",{"JMSLLTE_W_TD23_black_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_CIS_74_Naval_Officer_01 : O_CIS_74_Rifleman_01 {
        author = "CC-3572 ""Cordo""";
        scope = 2;
        scopeCurator = 2;
        displayName = "Naval Officer";
        side = 0;
        faction = "O_CIS74";

        identityTypes[] = {"Head_TK","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "WS_74th_Pilot_CombatUniform";

        linkedItems[] = {"WS_OfficerChest_armor","JMSLLTE_EmpOfficerCap_troop_helmet","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr"};
        respawnlinkedItems[] = {"WS_OfficerChest_armor","JMSLLTE_EmpOfficerCap_troop_helmet","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr"};

        weapons[] = {"JMSLLTE_rk3pistol","JMSLLTE_W_TD23_black_F"};
        respawnWeapons[] = {"JMSLLTE_rk3pistol","JMSLLTE_W_TD23_black_F"};

        magazines[] = {"JMSLLTE_RK3_20rnd_Mag","Laserbatteries","JMSLLTE_RK3_20rnd_Mag","Laserbatteries"};
        respawnMagazines[] = {"JMSLLTE_RK3_20rnd_Mag","Laserbatteries","JMSLLTE_RK3_20rnd_Mag","Laserbatteries"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"JMSLLTE_rk3pistol","","","",{"JMSLLTE_RK3_20rnd_Mag",20},{},""},{"WS_74th_Pilot_CombatUniform",{{"ACE_elasticBandage",10},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_CableTie",2},{"ACE_epinephrine",2},{"ACE_morphine",2},{"ACE_IR_Strobe_Item",1},{"ItemcTabHCam",1},{"ACE_Flashlight_XL50",1},{"ACE_MapTools",1},{"ACE_splint",2},{"ACE_tourniquet",4},{"StimAdrenal",2},{"OPTRE_M2_Smoke",1,1}}},{"WS_OfficerChest_armor",{}},{},"JMSLLTE_EmpOfficerCap_troop_helmet","",{"JMSLLTE_W_TD23_black_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_CIS_74_Facility_Guard_01 : O_CIS_74_Rifleman_01 {
        author = "CC-3572 ""Cordo""";
        scope = 2;
        scopeCurator = 2;
        displayName = "Facility Guard";
        side = 0;
        faction = "O_CIS74";

        identityTypes[] = {"Head_TK","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "JMSLLTE_EmpTrooperCamo_F_CombatUniform";

        linkedItems[] = {"SWLB_clone_basic_armor","JMSLLTE_EmpTrooper_helmet","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr"};
        respawnlinkedItems[] = {"SWLB_clone_basic_armor","JMSLLTE_EmpTrooper_helmet","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr"};

        weapons[] = {"JLTS_E5","JMSLLTE_W_TD23_black_F"};
        respawnWeapons[] = {"JLTS_E5","JMSLLTE_W_TD23_black_F"};

        magazines[] = {"JLTS_E5_mag","Laserbatteries","JLTS_E5_mag","Laserbatteries"};
        respawnMagazines[] = {"JLTS_E5_mag","Laserbatteries","JLTS_E5_mag","Laserbatteries"};

        ALiVE_orbatCreator_loadout[] = {{"JLTS_E5","","","",{"JLTS_E5_mag",100},{},""},{},{},{"JMSLLTE_EmpTrooperCamo_F_CombatUniform",{{"ACE_elasticBandage",10},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_CableTie",2},{"ACE_epinephrine",2},{"ACE_morphine",2},{"ACE_IR_Strobe_Item",1},{"ItemcTabHCam",1},{"ACE_Flashlight_XL50",1},{"ACE_MapTools",1},{"ACE_splint",2},{"ACE_tourniquet",4},{"StimAdrenal",2},{"OPTRE_M2_Smoke",1,1}}},{"SWLB_clone_basic_armor",{{"JLTS_E5_mag",4,100}}},{},"JMSLLTE_EmpTrooper_helmet","G_Spectacles",{"JMSLLTE_W_TD23_black_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_CIS_74_Lieutenant_Brigov_01 : O_A_soldier_F_OCimport_02 {
        author = "CC-3572 ""Cordo""";
        scope = 2;
        scopeCurator = 2;
        displayName = "Lieutenant Brigov";
        side = 0;
        faction = "O_CIS74";

        identityTypes[] = {"Head_TK","LanguageFRE_F","G_IRAN_default"};

        uniformClass = "WS_74th_Brigov_F_CombatUniform";

        linkedItems[] = {"JMSLLTE_StormtrooperPauldronC_black_armor","WS_74th_Medic_helmet","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr","OPTRE_NVG"};
        respawnlinkedItems[] = {"JMSLLTE_StormtrooperPauldronC_black_armor","WS_74th_Medic_helmet","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr","OPTRE_NVG"};

        weapons[] = {"JLTS_E5","JMSLLTE_W_TD23_black_F"};
        respawnWeapons[] = {"JLTS_E5","JMSLLTE_W_TD23_black_F"};

        magazines[] = {"JLTS_E5_mag","Laserbatteries","JLTS_E5_mag","Laserbatteries"};
        respawnMagazines[] = {"JLTS_E5_mag","Laserbatteries","JLTS_E5_mag","Laserbatteries"};

        backpack = "JMSLLTE_back_radio_v1";

        ALiVE_orbatCreator_loadout[] = {{"JLTS_E5","","","",{"JLTS_E5_mag",100},{},""},{},{},{"WS_74th_Brigov_F_CombatUniform",{{"ACE_elasticBandage",10},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_CableTie",2},{"ACE_epinephrine",2},{"ACE_morphine",2},{"ACE_IR_Strobe_Item",1},{"ItemcTabHCam",1},{"ACE_Flashlight_XL50",1},{"ACE_MapTools",1},{"ACE_splint",2},{"ACE_tourniquet",4},{"StimAdrenal",2},{"OPTRE_M2_Smoke",2,1},{"OPTRE_M2_Smoke_Orange",2,1}}},{"JMSLLTE_StormtrooperPauldronC_black_armor",{{"JLTS_E5_mag",7,100}}},{"JMSLLTE_back_radio_v1",{}},"WS_74th_Medic_helmet","G_JMSLLTE_TrooperMask_3",{"JMSLLTE_W_TD23_black_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_CIS_74_River_Patrol_Craft_01 : optre_catfish_unarmed_f_OCimport_02 {
        author = "CC-3572 ""Cordo""";
        scope = 2;
        scopeCurator = 2;
        displayName = "River Patrol Craft";
        side = 0;
        faction = "O_CIS74";
        crew = "OPTRE_UNSC_Marine_Soldier_Rifleman_AR";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\OPTRE_Vehicles\catfish\data\optre_catfish_boat_green_co.paa'];_unit setObjectTextureGlobal [1,'\OPTRE_Vehicles\catfish\data\optre_catfish_interior_co.paa'];_unit setObjectTextureGlobal [2,'\OPTRE_Vehicles\catfish\data\optre_catfish_seats_co.paa'];_unit setObjectTextureGlobal [3,'\OPTRE_Vehicles\catfish\data\optre_catfish_windscreen_ca.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "texGreen";

    };

    class O_CIS_74_River_Patrol_Craft_Armed_01 : optre_catfish_mg_f_OCimport_02 {
        author = "CC-3572 ""Cordo""";
        scope = 2;
        scopeCurator = 2;
        displayName = "River Patrol Craft (Armed)";
        side = 0;
        faction = "O_CIS74";
        crew = "OPTRE_UNSC_Marine_Soldier_Rifleman_AR";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class MainTurret : MainTurret { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\OPTRE_Vehicles\catfish\data\optre_catfish_boat_green_co.paa'];_unit setObjectTextureGlobal [1,'\OPTRE_Vehicles\catfish\data\optre_catfish_interior_co.paa'];_unit setObjectTextureGlobal [2,'\OPTRE_Vehicles\catfish\data\optre_catfish_seats_co.paa'];_unit setObjectTextureGlobal [3,'\OPTRE_Vehicles\catfish\data\optre_catfish_windscreen_ca.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "texGreen";

    };

    class O_CIS_74_Security_Droid_01 : lsd_cis_b1_standard_OCimport_02 {
        author = "CC-3572 ""Cordo""";
        scope = 2;
        scopeCurator = 2;
        displayName = "Security Droid";
        side = 0;
        faction = "O_CIS74";

        identityTypes[] = {"lsd_voice_b1Droid"};

        uniformClass = "lsd_cis_oomSecurity_uniform";

        linkedItems[] = {"ls_cis_b1_helmet","ItemMap","SWLB_comlink_droid","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"ls_cis_b1_helmet","ItemMap","SWLB_comlink_droid","ItemCompass","ItemWatch"};

        weapons[] = {"JLTS_E5"};
        respawnWeapons[] = {"JLTS_E5"};

        magazines[] = {"JLTS_E5_mag","JLTS_E5_mag"};
        respawnMagazines[] = {"JLTS_E5_mag","JLTS_E5_mag"};

        ALiVE_orbatCreator_loadout[] = {{"JLTS_E5","","","",{"JLTS_E5_mag",100},{},""},{},{},{"lsd_cis_oomSecurity_uniform",{{"FirstAidKit",2},{"ACE_EarPlugs",1},{"JLTS_E5_mag",8,100}}},{},{},"ls_cis_b1_helmet","",{},{"ItemMap","","SWLB_comlink_droid","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_CIS_74_B1_Jungle_01 : O_CIS_74_Security_Droid_01 {
        author = "CC-3572 ""Cordo""";
        scope = 2;
        scopeCurator = 2;
        displayName = "B1 (Jungle)";
        side = 0;
        faction = "O_CIS74";

        identityTypes[] = {"lsd_voice_b1Droid"};

        uniformClass = "lsd_cis_oomCrew_uniform";

        linkedItems[] = {"lsd_cis_oomCrew_helmet","ItemMap","SWLB_comlink_droid","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"lsd_cis_oomCrew_helmet","ItemMap","SWLB_comlink_droid","ItemCompass","ItemWatch"};

        weapons[] = {"JLTS_E5"};
        respawnWeapons[] = {"JLTS_E5"};

        magazines[] = {"JLTS_E5_mag","JLTS_E5_mag"};
        respawnMagazines[] = {"JLTS_E5_mag","JLTS_E5_mag"};

        backpack = "lsd_cis_crew_backpack";

        ALiVE_orbatCreator_loadout[] = {{"JLTS_E5","","","",{"JLTS_E5_mag",100},{},""},{},{},{"lsd_cis_oomCrew_uniform",{{"FirstAidKit",2},{"ACE_EarPlugs",1},{"JLTS_E5_mag",9,100}}},{},{"lsd_cis_crew_backpack",{}},"lsd_cis_oomCrew_helmet","",{},{"ItemMap","","SWLB_comlink_droid","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_CIS_74_B1_AutoRifleman_Jungle_01 : O_CIS_74_B1_Jungle_01 {
        author = "CC-3572 ""Cordo""";
        scope = 2;
        scopeCurator = 2;
        displayName = "B1 AutoRifleman (Jungle)";
        side = 0;
        faction = "O_CIS74";

        identityTypes[] = {"lsd_voice_b1Droid"};

        uniformClass = "lsd_cis_oomCrew_uniform";

        linkedItems[] = {"lsd_cis_oomCrew_helmet","ItemMap","SWLB_comlink_droid","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"lsd_cis_oomCrew_helmet","ItemMap","SWLB_comlink_droid","ItemCompass","ItemWatch"};

        weapons[] = {"JLTS_E5C_stock"};
        respawnWeapons[] = {"JLTS_E5C_stock"};

        magazines[] = {"JLTS_E5C_mag","JLTS_E5C_mag"};
        respawnMagazines[] = {"JLTS_E5C_mag","JLTS_E5C_mag"};

        backpack = "lsd_cis_crew_backpack";

        ALiVE_orbatCreator_loadout[] = {{"JLTS_E5C_stock","","","",{"JLTS_E5C_mag",150},{},""},{},{},{"lsd_cis_oomCrew_uniform",{{"FirstAidKit",2},{"ACE_EarPlugs",1},{"JLTS_E5C_mag",12,150}}},{},{"lsd_cis_crew_backpack",{}},"lsd_cis_oomCrew_helmet","",{},{"ItemMap","","SWLB_comlink_droid","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_CIS_74_BX_series_Security_01 : lsd_cis_bxSecurity_specops_OCimport_02 {
        author = "CC-3572 ""Cordo""";
        scope = 2;
        scopeCurator = 2;
        displayName = "BX-series Security";
        side = 0;
        faction = "O_CIS74";

        identityTypes[] = {"Head_LSD_BX","LanguageENG_F"};

        uniformClass = "lsd_cis_bxSecurityDroid_uniform";

        linkedItems[] = {"JMSLLTE_StormtrooperHidden_armor","ItemMap","SWLB_comlink_droid","ItemCompass","ItemWatch","ls_mandalorian_rangefinder_nvg"};
        respawnlinkedItems[] = {"JMSLLTE_StormtrooperHidden_armor","ItemMap","SWLB_comlink_droid","ItemCompass","ItemWatch","ls_mandalorian_rangefinder_nvg"};

        weapons[] = {"JLTS_E5"};
        respawnWeapons[] = {"JLTS_E5"};

        magazines[] = {"JLTS_E5_mag","JLTS_E5_mag"};
        respawnMagazines[] = {"JLTS_E5_mag","JLTS_E5_mag"};

        ALiVE_orbatCreator_loadout[] = {{"JLTS_E5","","","",{"JLTS_E5_mag",100},{},""},{},{},{"lsd_cis_bxSecurityDroid_uniform",{{"FirstAidKit",1},{"ACE_EarPlugs",1},{"JLTS_E5_mag",11,100}}},{"JMSLLTE_StormtrooperHidden_armor",{}},{},"","",{},{"ItemMap","","SWLB_comlink_droid","ItemCompass","ItemWatch","ls_mandalorian_rangefinder_nvg"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};