//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 208.149102 on Stable branch
// Generated with ALiVE version 1.15.0.2112041
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class I_HERD {
        displayName = "Tribe of the Poisoned";
        side = 2;
        flag = "\a3\Data_F_Exp\Flags\flag_SYND_CO.paa";
        icon = "\a3\Data_F_Exp\Flags\flag_SYND_CO.paa";
        priority = 0;
    };
};

class CfgGroups {
    class Indep {

        class I_HERD {
            name = "Tribe of the Poisoned";

            class Infantry {
                name = "Infantry";

                class i_herd_infantry_group {
                    name = "Group";
                    side = 2;
                    faction = "I_HERD";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_HERD_Warrior_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_HERD_Warrior_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_HERD_Warrior_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_HERD_Rusher_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_HERD_Rusher_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_HERD_Rusher_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class I_L_Hunter_F;
    class I_L_Hunter_F_OCimport_01 : I_L_Hunter_F { scope = 0; class EventHandlers; };
    class I_L_Hunter_F_OCimport_02 : I_L_Hunter_F_OCimport_01 { class EventHandlers; };


    class I_HERD_Warrior_01 : I_L_Hunter_F_OCimport_02 {
        author = "CC-3572 ""Cordo""";
        scope = 2;
        scopeCurator = 2;
        displayName = "Warrior";
        side = 2;
        faction = "I_HERD";

        identityTypes[] = {"Head_Rangemaster","LanguagePOL_F","G_GUERIL_default"};

        uniformClass = "U_I_C_Soldier_Para_5_F";

        linkedItems[] = {"OPTRE_UNSC_M52A_Armor_Sniper_DES","OPTRE_UNSC_CH252_Helmet3_DES","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr"};
        respawnlinkedItems[] = {"OPTRE_UNSC_M52A_Armor_Sniper_DES","OPTRE_UNSC_CH252_Helmet3_DES","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr"};

        weapons[] = {"srifle_DMR_06_hunter_F"};
        respawnWeapons[] = {"srifle_DMR_06_hunter_F"};

        magazines[] = {"10Rnd_Mk14_762x51_Mag","10Rnd_Mk14_762x51_Mag"};
        respawnMagazines[] = {"10Rnd_Mk14_762x51_Mag","10Rnd_Mk14_762x51_Mag"};

        backpack = "JMSLLTE_back_mimbcover_v1";

        ALiVE_orbatCreator_loadout[] = {{"srifle_DMR_06_hunter_F","","","",{"10Rnd_Mk14_762x51_Mag",10},{},""},{},{},{"U_I_C_Soldier_Para_5_F",{{"10Rnd_Mk14_762x51_Mag",5,10}}},{"OPTRE_UNSC_M52A_Armor_Sniper_DES",{{"20Rnd_762x51_Mag",7,20}}},{"JMSLLTE_back_mimbcover_v1",{}},"OPTRE_UNSC_CH252_Helmet3_DES","",{},{"ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_HERD_Rusher_01 : I_HERD_Warrior_01 {
        author = "CC-3572 ""Cordo""";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rusher";
        side = 2;
        faction = "I_HERD";

        identityTypes[] = {"Head_Rangemaster","LanguagePOL_F","G_GUERIL_default"};

        uniformClass = "U_I_C_Soldier_Para_5_F";

        linkedItems[] = {"OPTRE_UNSC_M52A_Armor_Sniper_DES","OPTRE_UNSC_CH252_Helmet3_DES","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr"};
        respawnlinkedItems[] = {"OPTRE_UNSC_M52A_Armor_Sniper_DES","OPTRE_UNSC_CH252_Helmet3_DES","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr"};

        weapons[] = {"srifle_DMR_06_hunter_F"};
        respawnWeapons[] = {"srifle_DMR_06_hunter_F"};

        magazines[] = {"10Rnd_Mk14_762x51_Mag","10Rnd_Mk14_762x51_Mag"};
        respawnMagazines[] = {"10Rnd_Mk14_762x51_Mag","10Rnd_Mk14_762x51_Mag"};

        backpack = "JMSLLTE_back_mimbcover_v1";

        ALiVE_orbatCreator_loadout[] = {{"srifle_DMR_06_hunter_F","","","",{"10Rnd_Mk14_762x51_Mag",10},{},""},{},{},{"U_I_C_Soldier_Para_5_F",{{"10Rnd_Mk14_762x51_Mag",5,10}}},{"OPTRE_UNSC_M52A_Armor_Sniper_DES",{{"20Rnd_762x51_Mag",7,20}}},{"JMSLLTE_back_mimbcover_v1",{}},"OPTRE_UNSC_CH252_Helmet3_DES","",{},{"ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_HERD_Chief_01 : I_HERD_Warrior_01 {
        author = "CC-3572 ""Cordo""";
        scope = 2;
        scopeCurator = 2;
        displayName = "Chief";
        side = 2;
        faction = "I_HERD";

        identityTypes[] = {"Head_m_zabrak","LanguagePOL_F","G_GUERIL_default"};

        uniformClass = "U_I_FullGhillie_sard";

        linkedItems[] = {"OPTRE_UNSC_M52D_Armor_Lum","OPTRE_UNSC_CH252A_Helmet_dp","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr"};
        respawnlinkedItems[] = {"OPTRE_UNSC_M52D_Armor_Lum","OPTRE_UNSC_CH252A_Helmet_dp","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr"};

        weapons[] = {"JMSLLTE_DLT19BlasterRifle"};
        respawnWeapons[] = {"JMSLLTE_DLT19BlasterRifle"};

        magazines[] = {"JMSLLTE_DLT19_75Rnd_Mag","JMSLLTE_DLT19_75Rnd_Mag"};
        respawnMagazines[] = {"JMSLLTE_DLT19_75Rnd_Mag","JMSLLTE_DLT19_75Rnd_Mag"};

        backpack = "JMSLLTE_back_stormpack_v1";

        ALiVE_orbatCreator_loadout[] = {{"JMSLLTE_DLT19BlasterRifle","","","",{"JMSLLTE_DLT19_75Rnd_Mag",75},{},""},{},{},{"U_I_FullGhillie_sard",{{"JLTS_drugs_deathstick",3},{"JMSLLTE_DLT19_75Rnd_Mag",3,75}}},{"OPTRE_UNSC_M52D_Armor_Lum",{}},{"JMSLLTE_back_stormpack_v1",{{"JMSLLTE_DLT19_75Rnd_Mag",21,75}}},"OPTRE_UNSC_CH252A_Helmet_dp","Shadow_mask",{},{"ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_HERD_Seeker_01 : I_HERD_Warrior_01 {
        author = "CC-3572 ""Cordo""";
        scope = 2;
        scopeCurator = 2;
        displayName = "Seeker";
        side = 2;
        faction = "I_HERD";

        identityTypes[] = {"Head_Rangemaster","LanguagePOL_F","G_GUERIL_default"};

        uniformClass = "U_I_C_Soldier_Para_5_F";

        linkedItems[] = {"OPTRE_UNSC_M52A_Armor_Sniper_DES","OPTRE_UNSC_CH252_Helmet3_DES","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr"};
        respawnlinkedItems[] = {"OPTRE_UNSC_M52A_Armor_Sniper_DES","OPTRE_UNSC_CH252_Helmet3_DES","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr"};

        weapons[] = {"k_773_rifle"};
        respawnWeapons[] = {"k_773_rifle"};

        magazines[] = {"442_408_10rnd_blue_mag","442_408_10rnd_blue_mag"};
        respawnMagazines[] = {"442_408_10rnd_blue_mag","442_408_10rnd_blue_mag"};

        backpack = "JMSLLTE_back_mimbcover_v1";

        ALiVE_orbatCreator_loadout[] = {{"k_773_rifle","","","k_773_scope1",{"442_408_10rnd_blue_mag",10},{},""},{},{},{"U_I_C_Soldier_Para_5_F",{{"442_408_10rnd_blue_mag",2,10}}},{"OPTRE_UNSC_M52A_Armor_Sniper_DES",{{"442_408_10rnd_blue_mag",6,10}}},{"JMSLLTE_back_mimbcover_v1",{}},"OPTRE_UNSC_CH252_Helmet3_DES","",{},{"ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","tf_microdagr",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};