//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 208.149102 on Stable branch
// Generated with ALiVE version 1.15.0.2112041
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class HS_GIN_DES {
        displayName = "[HS] Galactic Insurgents (Desert)";
        side = 2;
        flag = "\a3\Data_F_Exp\Flags\flag_SYND_CO.paa";
        icon = "\a3\Data_F_Exp\Flags\flag_SYND_CO.paa";
        priority = 0;
    };
};

class CfgGroups {
    class Indep {

        class HS_GIN_DES {
            name = "[HS] Galactic Insurgents (Desert)";

            class Infantry {
                name = "Infantry";

                class i_gin_infantry_squad_des {
                    name = "Squad";
                    side = 2;
                    faction = "HS_GIN_DES";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_GIN_Squad_Leader_DES_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_GIN_Rifleman_DES_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_GIN_Rifleman_DES_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_GIN_Medic_DES_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_GIN_Autorifleman_DES_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_GIN_Rifleman_DES_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_GIN_Rifleman_DES_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_GIN_Rifleman_DES_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_GIN_Rifleman_DES_01";
                    };
                };

                class i_gin_infantry_squad_at_des {
                    name = "Squad AT";
                    side = 2;
                    faction = "HS_GIN_DES";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_GIN_Squad_Leader_DES_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_GIN_Rifleman_DES_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_GIN_Rifleman_DES_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_GIN_Medic_DES_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_GIN_Autorifleman_DES_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_GIN_Rifleman_DES_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_GIN_Rifleman_DES_01";
                    };
                    class Unit7 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_GIN_Rifleman_DES_01";
                    };
                    class Unit8 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_GIN_Rifleman_AT_DES_01";
                    };
                };

                class i_gin_infantry_squad_aa_des {
                    name = "Squad AA";
                    side = 2;
                    faction = "HS_GIN_DES";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_GIN_Squad_Leader_DES_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_GIN_Rifleman_DES_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_GIN_Rifleman_DES_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_GIN_Medic_DES_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_GIN_Autorifleman_DES_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_GIN_Rifleman_DES_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_GIN_Rifleman_DES_01";
                    };
                    class Unit7 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_GIN_Rifleman_DES_01";
                    };
                    class Unit8 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_GIN_Rifleman_AA_DES_01";
                    };
                };

                class i_gin_infantry_patrol_team_des {
                    name = "Patrol Team";
                    side = 2;
                    faction = "HS_GIN_DES";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_GIN_Rifleman_Light_DES_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_GIN_Rifleman_Light_DES_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_GIN_Rifleman_Light_DES_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_GIN_Sniper_DES_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_GIN_Medic_DES_01";
                    };
                };

                class i_gin_infantry_fireteam_des {
                    name = "Fireteam";
                    side = 2;
                    faction = "HS_GIN_DES";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_GIN_Rifleman_DES_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_GIN_Rifleman_DES_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_GIN_Rifleman_DES_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_GIN_Rifleman_DES_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

                class i_gin_motorized_polaris_des {
                    name = "Polaris";
                    side = 2;
                    faction = "HS_GIN_DES";
                    icon = "\A3\ui_f\data\map\markers\nato\n_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_GIN_Polaris_DES_01";
                    };
                };

                class i_gin_motorized_polaris_armed_des {
                    name = "Polaris (Armed)";
                    side = 2;
                    faction = "HS_GIN_DES";
                    icon = "\A3\ui_f\data\map\markers\nato\n_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_GIN_Polaris_Armed_DES_01";
                    };
                };

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

                class i_gin_armored_namer_des {
                    name = "Namer";
                    side = 2;
                    faction = "HS_GIN_DES";
                    icon = "\A3\ui_f\data\map\markers\nato\n_armor.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_GIN_Namer_DES_01";
                    };
                };

                class i_gin_armored_rooikat_des {
                    name = "Rooikat";
                    side = 2;
                    faction = "HS_GIN_DES";
                    icon = "\A3\ui_f\data\map\markers\nato\n_armor.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_GIN_Rooikat_DES_01";
                    };
                };

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class I_G_Soldier_F;
    class I_G_Soldier_F_OCimport_01 : I_G_Soldier_F { scope = 0; class EventHandlers; };
    class I_G_Soldier_F_OCimport_02 : I_G_Soldier_F_OCimport_01 { class EventHandlers; };

    class B_CTRG_LSV_01_light_F;
    class B_CTRG_LSV_01_light_F_OCimport_01 : B_CTRG_LSV_01_light_F { scope = 0; class EventHandlers; class Turrets; };
    class B_CTRG_LSV_01_light_F_OCimport_02 : B_CTRG_LSV_01_light_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_01;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
        };
    };

    class B_LSV_01_armed_F;
    class B_LSV_01_armed_F_OCimport_01 : B_LSV_01_armed_F { scope = 0; class EventHandlers; class Turrets; };
    class B_LSV_01_armed_F_OCimport_02 : B_LSV_01_armed_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class TopTurret;
            class CodRiverTurret;
            class CargoTurret_02;
            class CargoTurret_03;
        };
    };

    class B_APC_Tracked_01_rcws_F;
    class B_APC_Tracked_01_rcws_F_OCimport_01 : B_APC_Tracked_01_rcws_F { scope = 0; class EventHandlers; class Turrets; };
    class B_APC_Tracked_01_rcws_F_OCimport_02 : B_APC_Tracked_01_rcws_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CommanderOptics;
        };
    };

    class B_Mortar_01_F;
    class B_Mortar_01_F_OCimport_01 : B_Mortar_01_F { scope = 0; class EventHandlers; class Turrets; };
    class B_Mortar_01_F_OCimport_02 : B_Mortar_01_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class B_AFV_Wheeled_01_cannon_F;
    class B_AFV_Wheeled_01_cannon_F_OCimport_01 : B_AFV_Wheeled_01_cannon_F { scope = 0; class EventHandlers; class Turrets; };
    class B_AFV_Wheeled_01_cannon_F_OCimport_02 : B_AFV_Wheeled_01_cannon_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };


    class I_GIN_Rifleman_DES_01 : I_G_Soldier_F_OCimport_02 {
        author = "Helix Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman";
        side = 2;
        faction = "HS_GIN_DES";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "JMSLLTE_ScumCommando_desertS_F_CombatUniform";

        linkedItems[] = {"mgsr_vest_khaki","JMSLLTE_Commando_desert_helmet","ItemMap","ItemGPS","SWLB_comlink_hush98","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"mgsr_vest_khaki","JMSLLTE_Commando_desert_helmet","ItemMap","ItemGPS","SWLB_comlink_hush98","ItemCompass","ItemWatch"};

        weapons[] = {"JMSLLTE_a280","JMSLLTE_W_TD23_tan_F"};
        respawnWeapons[] = {"JMSLLTE_a280","JMSLLTE_W_TD23_tan_F"};

        magazines[] = {"JMSLLTE_A280_30rnd_Mag","Laserbatteries","JMSLLTE_A280_30rnd_Mag","Laserbatteries"};
        respawnMagazines[] = {"JMSLLTE_A280_30rnd_Mag","Laserbatteries","JMSLLTE_A280_30rnd_Mag","Laserbatteries"};

        backpack = "B_FieldPack_cbr";

        ALiVE_orbatCreator_loadout[] = {{"JMSLLTE_a280","","","JMSLLTE_a280c_bl_Scope",{"JMSLLTE_A280_30rnd_Mag",30},{},""},{},{},{"JMSLLTE_ScumCommando_desertS_F_CombatUniform",{{"ACE_elasticBandage",10},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_epinephrine",3},{"ACE_morphine",3},{"ACE_splint",1},{"ACE_tourniquet",2}}},{"mgsr_vest_khaki",{{"ACE_Flashlight_XL50",1},{"ACE_IR_Strobe_Item",1},{"ACE_EntrenchingTool",1},{"JMSLLTE_A280_30rnd_Mag",9,30},{"ls_mag_classC_thermalDet",1,1}}},{"B_FieldPack_cbr",{}},"JMSLLTE_Commando_desert_helmet","G_Bandanna_tan",{"JMSLLTE_W_TD23_tan_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","SWLB_comlink_hush98","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_GIN_Rifleman_AA_DES_01 : I_GIN_Rifleman_DES_01 {
        author = "Helix Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (AA)";
        side = 2;
        faction = "HS_GIN_DES";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "JMSLLTE_ScumCommando_desertS_F_CombatUniform";

        linkedItems[] = {"mgsr_vest_khaki","JMSLLTE_Commando_desert_helmet","ItemMap","ItemGPS","SWLB_comlink_hush98","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"mgsr_vest_khaki","JMSLLTE_Commando_desert_helmet","ItemMap","ItemGPS","SWLB_comlink_hush98","ItemCompass","ItemWatch"};

        weapons[] = {"JMSLLTE_a280","SWLW_E60R_AA","JMSLLTE_W_TD23_tan_F"};
        respawnWeapons[] = {"JMSLLTE_a280","SWLW_E60R_AA","JMSLLTE_W_TD23_tan_F"};

        magazines[] = {"JMSLLTE_A280_30rnd_Mag","SWLW_e60r_aa_mag","Laserbatteries","JMSLLTE_A280_30rnd_Mag","Laserbatteries"};
        respawnMagazines[] = {"JMSLLTE_A280_30rnd_Mag","SWLW_e60r_aa_mag","Laserbatteries","JMSLLTE_A280_30rnd_Mag","Laserbatteries"};

        backpack = "B_Carryall_cbr";

        ALiVE_orbatCreator_loadout[] = {{"JMSLLTE_a280","","","JMSLLTE_a280c_bl_Scope",{"JMSLLTE_A280_30rnd_Mag",30},{},""},{"SWLW_E60R_AA","","","",{"SWLW_e60r_aa_mag",3},{},""},{},{"JMSLLTE_ScumCommando_desertS_F_CombatUniform",{{"ACE_elasticBandage",10},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_epinephrine",3},{"ACE_morphine",3},{"ACE_splint",1},{"ACE_tourniquet",2}}},{"mgsr_vest_khaki",{{"ACE_Flashlight_XL50",1},{"ACE_IR_Strobe_Item",1},{"ACE_EntrenchingTool",1},{"JMSLLTE_A280_30rnd_Mag",9,30},{"ls_mag_classC_thermalDet",1,1}}},{"B_Carryall_cbr",{{"Titan_AA",1,1},{"SWLW_e60r_aa_mag",3,3}}},"JMSLLTE_Commando_desert_helmet","G_Bandanna_tan",{"JMSLLTE_W_TD23_tan_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","SWLB_comlink_hush98","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_GIN_Rifleman_AT_DES_01 : I_GIN_Rifleman_DES_01 {
        author = "Helix Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (AT)";
        side = 2;
        faction = "HS_GIN_DES";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "JMSLLTE_ScumCommando_desertS_F_CombatUniform";

        linkedItems[] = {"mgsr_vest_khaki","JMSLLTE_Commando_desert_helmet","ItemMap","ItemGPS","SWLB_comlink_hush98","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"mgsr_vest_khaki","JMSLLTE_Commando_desert_helmet","ItemMap","ItemGPS","SWLB_comlink_hush98","ItemCompass","ItemWatch"};

        weapons[] = {"JMSLLTE_a280","JLTS_RPS6","JMSLLTE_W_TD23_tan_F"};
        respawnWeapons[] = {"JMSLLTE_a280","JLTS_RPS6","JMSLLTE_W_TD23_tan_F"};

        magazines[] = {"JMSLLTE_A280_30rnd_Mag","JLTS_RPS6_mag","Laserbatteries","JMSLLTE_A280_30rnd_Mag","Laserbatteries"};
        respawnMagazines[] = {"JMSLLTE_A280_30rnd_Mag","JLTS_RPS6_mag","Laserbatteries","JMSLLTE_A280_30rnd_Mag","Laserbatteries"};

        backpack = "B_Carryall_cbr";

        ALiVE_orbatCreator_loadout[] = {{"JMSLLTE_a280","","","JMSLLTE_a280c_bl_Scope",{"JMSLLTE_A280_30rnd_Mag",30},{},""},{"JLTS_RPS6","","","",{"JLTS_RPS6_mag",1},{},""},{},{"JMSLLTE_ScumCommando_desertS_F_CombatUniform",{{"ACE_elasticBandage",10},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_epinephrine",3},{"ACE_morphine",3},{"ACE_splint",1},{"ACE_tourniquet",2}}},{"mgsr_vest_khaki",{{"ACE_Flashlight_XL50",1},{"ACE_IR_Strobe_Item",1},{"ACE_EntrenchingTool",1},{"JMSLLTE_A280_30rnd_Mag",9,30},{"ls_mag_classC_thermalDet",1,1}}},{"B_Carryall_cbr",{{"JLTS_RPS6_mag",3,1},{"JLTS_RPS6_HE_mag",3,1}}},"JMSLLTE_Commando_desert_helmet","G_Bandanna_tan",{"JMSLLTE_W_TD23_tan_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","SWLB_comlink_hush98","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_GIN_Rifleman_Light_DES_01 : I_GIN_Rifleman_DES_01 {
        author = "Helix Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (Light)";
        side = 2;
        faction = "HS_GIN_DES";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "U_B_CombatUniform_mcam_tshirt";

        linkedItems[] = {"mgsr_vest_khaki","H_Booniehat_tan","ItemMap","ItemGPS","SWLB_comlink_hush98","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"mgsr_vest_khaki","H_Booniehat_tan","ItemMap","ItemGPS","SWLB_comlink_hush98","ItemCompass","ItemWatch"};

        weapons[] = {"JLTS_DC15S","JMSLLTE_W_TD23_tan_F"};
        respawnWeapons[] = {"JLTS_DC15S","JMSLLTE_W_TD23_tan_F"};

        magazines[] = {"JLTS_DC15A_mag","Laserbatteries","JLTS_DC15A_mag","Laserbatteries"};
        respawnMagazines[] = {"JLTS_DC15A_mag","Laserbatteries","JLTS_DC15A_mag","Laserbatteries"};

        backpack = "B_FieldPack_cbr";

        ALiVE_orbatCreator_loadout[] = {{"JLTS_DC15S","","","",{"JLTS_DC15A_mag",60},{},""},{},{},{"U_B_CombatUniform_mcam_tshirt",{{"ACE_elasticBandage",10},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_epinephrine",3},{"ACE_morphine",3},{"ACE_splint",1},{"ACE_tourniquet",2}}},{"mgsr_vest_khaki",{{"ACE_Flashlight_XL50",1},{"ACE_IR_Strobe_Item",1},{"ACE_EntrenchingTool",1},{"ls_mag_classC_thermalDet",1,1}}},{"B_FieldPack_cbr",{{"JLTS_DC15A_mag",9,60}}},"H_Booniehat_tan","G_Balaclava_oli",{"JMSLLTE_W_TD23_tan_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","SWLB_comlink_hush98","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_GIN_Sniper_DES_01 : I_GIN_Rifleman_DES_01 {
        author = "Helix Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "Sniper";
        side = 2;
        faction = "HS_GIN_DES";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "JMSLLTE_ScumAlCommando_desert_F_CombatUniform";

        linkedItems[] = {"mgsr_vest_khaki","JMSLLTE_Path_1_brown_cap","ItemMap","ItemGPS","SWLB_comlink_hush98","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"mgsr_vest_khaki","JMSLLTE_Path_1_brown_cap","ItemMap","ItemGPS","SWLB_comlink_hush98","ItemCompass","ItemWatch"};

        weapons[] = {"SWLW_sniper","JMSLLTE_dl44pistol","JMSLLTE_W_TD23_tan_F"};
        respawnWeapons[] = {"SWLW_sniper","JMSLLTE_dl44pistol","JMSLLTE_W_TD23_tan_F"};

        magazines[] = {"SWLW_sniper_Mag","JMSLLTE_DL44_10rnd_Mag","Laserbatteries","SWLW_sniper_Mag","JMSLLTE_DL44_10rnd_Mag","Laserbatteries"};
        respawnMagazines[] = {"SWLW_sniper_Mag","JMSLLTE_DL44_10rnd_Mag","Laserbatteries","SWLW_sniper_Mag","JMSLLTE_DL44_10rnd_Mag","Laserbatteries"};

        backpack = "B_FieldPack_cbr";

        ALiVE_orbatCreator_loadout[] = {{"SWLW_sniper","","","SWLW_sniper_scope",{"SWLW_sniper_Mag",10},{},""},{},{"JMSLLTE_dl44pistol","","","",{"JMSLLTE_DL44_10rnd_Mag",10},{},""},{"JMSLLTE_ScumAlCommando_desert_F_CombatUniform",{{"ACE_elasticBandage",10},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_epinephrine",3},{"ACE_morphine",3},{"ACE_splint",1},{"ACE_tourniquet",2},{"SWLW_sniper_Mag",3,10},{"JMSLLTE_DL44_10rnd_Mag",3,10}}},{"mgsr_vest_khaki",{{"ACE_Flashlight_XL50",1},{"ACE_IR_Strobe_Item",1},{"ACE_EntrenchingTool",1},{"ls_mag_classC_thermalDet",1,1},{"SWLW_sniper_Mag",8,10}}},{"B_FieldPack_cbr",{{"JMSLLTE_DL44_10rnd_Mag",6,10}}},"JMSLLTE_Path_1_brown_cap","",{"JMSLLTE_W_TD23_tan_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","SWLB_comlink_hush98","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_GIN_Squad_Leader_DES_01 : I_GIN_Rifleman_DES_01 {
        author = "Helix Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "Squad Leader";
        side = 2;
        faction = "HS_GIN_DES";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "JMSLLTE_ScumCommando_desertS_F_CombatUniform";

        linkedItems[] = {"V_SmershVest_01_radio_F","JMSLLTE_Navy_brown_helmet","ItemMap","ItemGPS","SWLB_comlink_hush98","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_SmershVest_01_radio_F","JMSLLTE_Navy_brown_helmet","ItemMap","ItemGPS","SWLB_comlink_hush98","ItemCompass","ItemWatch"};

        weapons[] = {"JMSLLTE_a280","JMSLLTE_rk3pistol","JMSLLTE_W_TD23_tan_F"};
        respawnWeapons[] = {"JMSLLTE_a280","JMSLLTE_rk3pistol","JMSLLTE_W_TD23_tan_F"};

        magazines[] = {"JMSLLTE_A280_30rnd_Mag","JMSLLTE_RK3_20rnd_Mag","Laserbatteries","JMSLLTE_A280_30rnd_Mag","JMSLLTE_RK3_20rnd_Mag","Laserbatteries"};
        respawnMagazines[] = {"JMSLLTE_A280_30rnd_Mag","JMSLLTE_RK3_20rnd_Mag","Laserbatteries","JMSLLTE_A280_30rnd_Mag","JMSLLTE_RK3_20rnd_Mag","Laserbatteries"};

        backpack = "ls_mandalorian_rto_backpack";

        ALiVE_orbatCreator_loadout[] = {{"JMSLLTE_a280","","","JMSLLTE_a280c_bl_Scope",{"JMSLLTE_A280_30rnd_Mag",30},{},""},{},{"JMSLLTE_rk3pistol","","","",{"JMSLLTE_RK3_20rnd_Mag",20},{},""},{"JMSLLTE_ScumCommando_desertS_F_CombatUniform",{{"ACE_elasticBandage",10},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_epinephrine",3},{"ACE_morphine",3},{"ACE_splint",1},{"ACE_tourniquet",2}}},{"V_SmershVest_01_radio_F",{{"ACE_Flashlight_XL50",1},{"ACE_IR_Strobe_Item",1},{"ACE_EntrenchingTool",1},{"JMSLLTE_A280_30rnd_Mag",9,30},{"ls_mag_classC_thermalDet",1,1},{"JMSLLTE_RK3_20rnd_Mag",7,20}}},{"ls_mandalorian_rto_backpack",{}},"JMSLLTE_Navy_brown_helmet","G_Bandanna_tan",{"JMSLLTE_W_TD23_tan_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","SWLB_comlink_hush98","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_GIN_Pilot_DES_01 : I_GIN_Rifleman_DES_01 {
        author = "Helix Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "Pilot";
        side = 2;
        faction = "HS_GIN_DES";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "JMSLLTE_ScumCommando_desertS_F_CombatUniform";

        linkedItems[] = {"mgsr_vest_khaki","H_Cap_marshal","ItemMap","ItemGPS","SWLB_comlink_hush98","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"mgsr_vest_khaki","H_Cap_marshal","ItemMap","ItemGPS","SWLB_comlink_hush98","ItemCompass","ItemWatch"};

        weapons[] = {"JMSLLTE_rk3pistol","JMSLLTE_W_TD23_tan_F"};
        respawnWeapons[] = {"JMSLLTE_rk3pistol","JMSLLTE_W_TD23_tan_F"};

        magazines[] = {"JMSLLTE_RK3_20rnd_Mag","Laserbatteries","JMSLLTE_RK3_20rnd_Mag","Laserbatteries"};
        respawnMagazines[] = {"JMSLLTE_RK3_20rnd_Mag","Laserbatteries","JMSLLTE_RK3_20rnd_Mag","Laserbatteries"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"JMSLLTE_rk3pistol","","","",{"JMSLLTE_RK3_20rnd_Mag",20},{},""},{"JMSLLTE_ScumCommando_desertS_F_CombatUniform",{{"ACE_elasticBandage",10},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_epinephrine",3},{"ACE_morphine",3},{"ACE_splint",1},{"ACE_tourniquet",2}}},{"mgsr_vest_khaki",{{"ACE_Flashlight_XL50",1},{"ACE_IR_Strobe_Item",1},{"ACE_EntrenchingTool",1},{"ls_mag_classC_thermalDet",1,1},{"JMSLLTE_RK3_20rnd_Mag",7,20}}},{},"H_Cap_marshal","",{"JMSLLTE_W_TD23_tan_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","SWLB_comlink_hush98","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_GIN_Crewman_DES_01 : I_GIN_Rifleman_DES_01 {
        author = "Helix Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crewman";
        side = 2;
        faction = "HS_GIN_DES";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "JMSLLTE_ScumCommando_desertS_F_CombatUniform";

        linkedItems[] = {"mgsr_vest_khaki","H_HelmetCrew_I_E","ItemMap","ItemGPS","SWLB_comlink_hush98","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"mgsr_vest_khaki","H_HelmetCrew_I_E","ItemMap","ItemGPS","SWLB_comlink_hush98","ItemCompass","ItemWatch"};

        weapons[] = {"JMSLLTE_rk3pistol","JMSLLTE_W_TD23_tan_F"};
        respawnWeapons[] = {"JMSLLTE_rk3pistol","JMSLLTE_W_TD23_tan_F"};

        magazines[] = {"JMSLLTE_RK3_20rnd_Mag","Laserbatteries","JMSLLTE_RK3_20rnd_Mag","Laserbatteries"};
        respawnMagazines[] = {"JMSLLTE_RK3_20rnd_Mag","Laserbatteries","JMSLLTE_RK3_20rnd_Mag","Laserbatteries"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"JMSLLTE_rk3pistol","","","",{"JMSLLTE_RK3_20rnd_Mag",20},{},""},{"JMSLLTE_ScumCommando_desertS_F_CombatUniform",{{"ACE_elasticBandage",10},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_epinephrine",3},{"ACE_morphine",3},{"ACE_splint",1},{"ACE_tourniquet",2}}},{"mgsr_vest_khaki",{{"ACE_Flashlight_XL50",1},{"ACE_IR_Strobe_Item",1},{"ACE_EntrenchingTool",1},{"ls_mag_classC_thermalDet",1,1},{"JMSLLTE_RK3_20rnd_Mag",7,20}}},{},"H_HelmetCrew_I_E","",{"JMSLLTE_W_TD23_tan_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","SWLB_comlink_hush98","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_GIN_Autorifleman_DES_01 : I_GIN_Rifleman_DES_01 {
        author = "Helix Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "Autorifleman";
        side = 2;
        faction = "HS_GIN_DES";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "JMSLLTE_ScumTroopCom_desert_F_CombatUniform";

        linkedItems[] = {"mgsr_vest_khaki","H_Bandanna_cbr","ItemMap","ItemGPS","SWLB_comlink_hush98","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"mgsr_vest_khaki","H_Bandanna_cbr","ItemMap","ItemGPS","SWLB_comlink_hush98","ItemCompass","ItemWatch"};

        weapons[] = {"JLTS_E5C_stock","JMSLLTE_W_TD23_tan_F"};
        respawnWeapons[] = {"JLTS_E5C_stock","JMSLLTE_W_TD23_tan_F"};

        magazines[] = {"JLTS_E5C_mag","Laserbatteries","JLTS_E5C_mag","Laserbatteries"};
        respawnMagazines[] = {"JLTS_E5C_mag","Laserbatteries","JLTS_E5C_mag","Laserbatteries"};

        backpack = "B_FieldPack_cbr";

        ALiVE_orbatCreator_loadout[] = {{"JLTS_E5C_stock","","","",{"JLTS_E5C_mag",150},{},""},{},{},{"JMSLLTE_ScumTroopCom_desert_F_CombatUniform",{{"ACE_elasticBandage",10},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_epinephrine",3},{"ACE_morphine",3},{"ACE_splint",1},{"ACE_tourniquet",2}}},{"mgsr_vest_khaki",{{"ACE_Flashlight_XL50",1},{"ACE_IR_Strobe_Item",1},{"ACE_EntrenchingTool",1},{"ls_mag_classC_thermalDet",1,1},{"JLTS_E5C_mag",9,150}}},{"B_FieldPack_cbr",{}},"H_Bandanna_cbr","G_Bandanna_oli",{"JMSLLTE_W_TD23_tan_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","SWLB_comlink_hush98","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_GIN_Medic_DES_01 : I_GIN_Rifleman_DES_01 {
        author = "Helix Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "Medic";
        side = 2;
        faction = "HS_GIN_DES";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "JMSLLTE_ScumCommando_desertS_F_CombatUniform";

        linkedItems[] = {"mgsr_vest_khaki","JMSLLTE_Desert_1_helmet","ItemMap","ItemGPS","SWLB_comlink_hush98","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"mgsr_vest_khaki","JMSLLTE_Desert_1_helmet","ItemMap","ItemGPS","SWLB_comlink_hush98","ItemCompass","ItemWatch"};

        weapons[] = {"JMSLLTE_dh17rifle","JMSLLTE_W_TD23_tan_F"};
        respawnWeapons[] = {"JMSLLTE_dh17rifle","JMSLLTE_W_TD23_tan_F"};

        magazines[] = {"JMSLLTE_DH17_60Rnd_Mag","Laserbatteries","JMSLLTE_DH17_60Rnd_Mag","Laserbatteries"};
        respawnMagazines[] = {"JMSLLTE_DH17_60Rnd_Mag","Laserbatteries","JMSLLTE_DH17_60Rnd_Mag","Laserbatteries"};

        backpack = "ls_mandalorian_medic_backpack";

        ALiVE_orbatCreator_loadout[] = {{"JMSLLTE_dh17rifle","","JMSLLTE_acc_flashlight_reb","JMSLLTE_dh17_bl_Scope",{"JMSLLTE_DH17_60Rnd_Mag",60},{},""},{},{},{"JMSLLTE_ScumCommando_desertS_F_CombatUniform",{{"ACE_elasticBandage",10},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_epinephrine",3},{"ACE_morphine",3},{"ACE_splint",1},{"ACE_tourniquet",2}}},{"mgsr_vest_khaki",{{"ACE_Flashlight_XL50",1},{"ACE_IR_Strobe_Item",1},{"ACE_EntrenchingTool",1},{"ls_mag_classC_thermalDet",1,1},{"JMSLLTE_DH17_60Rnd_Mag",9,60}}},{"ls_mandalorian_medic_backpack",{{"ACE_elasticBandage",25},{"ACE_fieldDressing",15},{"ACE_packingBandage",15},{"ACE_quikclot",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_splint",8},{"ACE_surgicalKit",1},{"ACE_tourniquet",10}}},"JMSLLTE_Desert_1_helmet","G_Bandanna_tan",{"JMSLLTE_W_TD23_tan_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","SWLB_comlink_hush98","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_GIN_Survivor_DES_01 : I_GIN_Rifleman_DES_01 {
        author = "Helix Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "Survivor";
        side = 2;
        faction = "HS_GIN_DES";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "JMSLLTE_ScumCommando_desertS_F_CombatUniform";

        linkedItems[] = {"mgsr_carrier_belt","ItemMap","ItemGPS","SWLB_comlink_hush98","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"mgsr_carrier_belt","ItemMap","ItemGPS","SWLB_comlink_hush98","ItemCompass","ItemWatch"};

        weapons[] = {"JMSLLTE_W_TD23_tan_F"};
        respawnWeapons[] = {"JMSLLTE_W_TD23_tan_F"};

        magazines[] = {"Laserbatteries","Laserbatteries"};
        respawnMagazines[] = {"Laserbatteries","Laserbatteries"};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"JMSLLTE_ScumCommando_desertS_F_CombatUniform",{{"ACE_elasticBandage",10},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_epinephrine",3},{"ACE_morphine",3},{"ACE_splint",1},{"ACE_tourniquet",2}}},{"mgsr_carrier_belt",{{"ACE_Flashlight_XL50",1},{"ACE_IR_Strobe_Item",1},{"ACE_EntrenchingTool",1}}},{},"","",{"JMSLLTE_W_TD23_tan_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","SWLB_comlink_hush98","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_GIN_Polaris_DES_01 : B_CTRG_LSV_01_light_F_OCimport_02 {
        author = "Helix Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "Polaris";
        side = 2;
        faction = "HS_GIN_DES";
        crew = "I_GIN_Rifleman_AA_DES_01";

        class Turrets : Turrets {
            class CargoTurret_02 : CargoTurret_02 { gunnerType = "I_GIN_Rifleman_DES_01"; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = "I_GIN_Rifleman_DES_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = "I_GIN_Rifleman_DES_01"; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = "I_GIN_Rifleman_DES_01"; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = "I_GIN_Medic_DES_01"; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = "I_GIN_Autorifleman_DES_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\A3\Soft_F_Exp\LSV_01\Data\NATO_LSV_01_sand_CO.paa'];_unit setObjectTextureGlobal [1,'\A3\Soft_F_Exp\LSV_01\Data\NATO_LSV_02_sand_CO.paa'];_unit setObjectTextureGlobal [2,'\A3\Soft_F_Exp\LSV_01\Data\NATO_LSV_03_sand_CO.paa'];_unit setObjectTextureGlobal [3,'\A3\Soft_F_Exp\LSV_01\Data\NATO_LSV_Adds_sand_CO.paa'];_unit setObjectTextureGlobal [4,'\A3\weapons_f_beta\launchers\titan\data\launcher_co.paa'];_unit setObjectTextureGlobal [5,'\A3\weapons_f_beta\launchers\titan\data\tubem_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Sand";

    };

    class I_GIN_Polaris_Armed_DES_01 : B_LSV_01_armed_F_OCimport_02 {
        author = "Helix Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "Polaris (Armed)";
        side = 2;
        faction = "HS_GIN_DES";
        crew = "I_GIN_Rifleman_DES_01";

        class Turrets : Turrets {
            class TopTurret : TopTurret { gunnerType = "I_GIN_Rifleman_DES_01"; };
            class CodRiverTurret : CodRiverTurret { gunnerType = "I_GIN_Rifleman_DES_01"; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = "I_GIN_Rifleman_DES_01"; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = "I_GIN_Rifleman_DES_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\A3\Soft_F_Exp\LSV_01\Data\NATO_LSV_01_sand_CO.paa'];_unit setObjectTextureGlobal [1,'\A3\Soft_F_Exp\LSV_01\Data\NATO_LSV_02_sand_CO.paa'];_unit setObjectTextureGlobal [2,'\A3\Soft_F_Exp\LSV_01\Data\NATO_LSV_03_sand_CO.paa'];_unit setObjectTextureGlobal [3,'\A3\Soft_F_Exp\LSV_01\Data\NATO_LSV_Adds_sand_CO.paa'];_unit setObjectTextureGlobal [4,'\A3\weapons_f_beta\launchers\titan\data\launcher_co.paa'];_unit setObjectTextureGlobal [5,'\A3\weapons_f_beta\launchers\titan\data\tubem_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Sand";

    };

    class I_GIN_Namer_DES_01 : B_APC_Tracked_01_rcws_F_OCimport_02 {
        author = "Helix Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "Namer";
        side = 2;
        faction = "HS_GIN_DES";
        crew = "I_GIN_Crewman_DES_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "I_GIN_Crewman_DES_01"; };
            class CommanderOptics : CommanderOptics { gunnerType = "I_GIN_Crewman_DES_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_GIN_Mk6_Proton_Mortar_DES_01 : B_Mortar_01_F_OCimport_02 {
        author = "Helix Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "Mk6 Proton Mortar";
        side = 2;
        faction = "HS_GIN_DES";
        crew = "B_Soldier_F";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "I_GIN_Rifleman_DES_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_GIN_Rooikat_DES_01 : B_AFV_Wheeled_01_cannon_F_OCimport_02 {
        author = "Helix Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rooikat";
        side = 2;
        faction = "HS_GIN_DES";
        crew = "I_GIN_Crewman_DES_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "I_GIN_Crewman_DES_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};