//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 204.147719 on Stable branch
// Generated with ALiVE version 1.14.1.2105061
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class O_CSArmy_WDL {
        displayName = "Communion of the Sacrificed";
        side = 0;
        flag = "\a3\UI_F_Enoch\Data\CfgMarkers\LivoniaLooters_CA.paa";
        icon = "\a3\UI_F_Enoch\Data\CfgMarkers\LivoniaLooters_CA.paa";
        priority = 0;
    };
};

class CfgGroups {
    class EAST {

        class O_CSArmy_WDL {
            name = "Communion of the Sacrificed";

            class Infantry {
                name = "Infantry";

                class o_csarmy_infantry_cs_fireteam_wdl {
                    name = "[CS] Fireteam";
                    side = 0;
                    faction = "O_CSArmy_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_CSArmy_CS_Rifleman_WDL_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CSArmy_CS_Rifleman_WDL_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CSArmy_CS_Rifleman_WDL_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CSArmy_CS_Rifleman_WDL_01";
                    };
                };

                class o_csarmy_infantry_cs_squad_wdl {
                    name = "[CS] Squad";
                    side = 0;
                    faction = "O_CSArmy_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_CSArmy_CS_Rifleman_WDL_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CSArmy_CS_Healer_WDL_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CSArmy_CS_Rifleman_WDL_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CSArmy_CS_Rifleman_WDL_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CSArmy_CS_Rifleman_WDL_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CSArmy_CS_Rifleman_WDL_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CSArmy_CS_Rifleman_WDL_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CSArmy_CS_Rifleman_WDL_01";
                    };
                };

                class o_csarmy_infantry_cs_horde_wdl {
                    name = "[CS] Horde";
                    side = 0;
                    faction = "O_CSArmy_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_CSArmy_CS_Rusher_WDL_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CSArmy_CS_Rusher_WDL_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CSArmy_CS_Rusher_WDL_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CSArmy_CS_Rusher_WDL_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CSArmy_CS_Rusher_WDL_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CSArmy_CS_Rusher_WDL_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CSArmy_CS_Rusher_WDL_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CSArmy_CS_Rusher_WDL_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_CSArmy_CS_Rusher_WDL_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class O_Soldier_F;
    class O_Soldier_F_OCimport_01 : O_Soldier_F { scope = 0; class EventHandlers; };
    class O_Soldier_F_OCimport_02 : O_Soldier_F_OCimport_01 { class EventHandlers; };

    class OPTRE_M12_ins_APC;
    class OPTRE_M12_ins_APC_OCimport_01 : OPTRE_M12_ins_APC { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_M12_ins_APC_OCimport_02 : OPTRE_M12_ins_APC_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoGunner_1;
            class CargoTurret_02;
        };
    };


    class O_CSArmy_CS_Rifleman_WDL_01 : O_Soldier_F_OCimport_02 {
        author = "Wyvern Studios ";
        scope = 2;
        scopeCurator = 2;
        displayName = "[CS] Rifleman";
        side = 0;
        faction = "O_CSArmy_WDL";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "mgsr_robe_olive_muddy";

        linkedItems[] = {"mgsr_vest_black","H_HelmetSpecO_blk","ItemMap","ItemcTab","SWLB_comlink_hush98","ItemCompass","ItemWatch","OPTRE_NVG"};
        respawnlinkedItems[] = {"mgsr_vest_black","H_HelmetSpecO_blk","ItemMap","ItemcTab","SWLB_comlink_hush98","ItemCompass","ItemWatch","OPTRE_NVG"};

        weapons[] = {"SWLW_Westar35S"};
        respawnWeapons[] = {"SWLW_Westar35S"};

        magazines[] = {"SWLW_Westar35S_Mag","SWLW_Westar35S_Mag"};
        respawnMagazines[] = {"SWLW_Westar35S_Mag","SWLW_Westar35S_Mag"};

        backpack = "B_CombinationUnitRespirator_01_F";

        ALiVE_orbatCreator_loadout[] = {{"SWLW_Westar35S","","","",{"SWLW_Westar35S_Mag",35},{},""},{},{},{"mgsr_robe_olive_muddy",{{"ACE_elasticBandage",8},{"ACE_fieldDressing",5},{"ACE_packingBandage",5}}},{"mgsr_vest_black",{{"JLTS_drugs_stimulant_hyperAdrenal",1},{"OPTRE_M2_Smoke",2,1},{"ACE_HandFlare_White",2,1},{"SWLW_Westar35S_Mag",9,35}}},{"B_CombinationUnitRespirator_01_F",{{"ACE_tourniquet",4},{"ACE_splint",1},{"ACE_morphine",2},{"ACE_epinephrine",1},{"ACE_EntrenchingTool",1}}},"H_HelmetSpecO_blk","mgsr_headbag_goggles",{},{"ItemMap","ItemcTab","SWLB_comlink_hush98","ItemCompass","ItemWatch","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_emblems_thehand'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_emblems_thehand";

    };

    class O_CSArmy_CS_Healer_WDL_01 : O_CSArmy_CS_Rifleman_WDL_01 {
        author = "Wyvern Studios ";
        scope = 2;
        scopeCurator = 2;
        displayName = "[CS] Healer";
        side = 0;
        faction = "O_CSArmy_WDL";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "mgsr_robe_olive_dirty";

        linkedItems[] = {"mgsr_carrier_belt","ItemMap","ItemcTab","SWLB_comlink_hush98_5","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"mgsr_carrier_belt","ItemMap","ItemcTab","SWLB_comlink_hush98_5","ItemCompass","ItemWatch"};

        weapons[] = {"SWLW_Westar35SA"};
        respawnWeapons[] = {"SWLW_Westar35SA"};

        magazines[] = {"SWLW_westar35sa_Mag","SWLW_westar35sa_Mag"};
        respawnMagazines[] = {"SWLW_westar35sa_Mag","SWLW_westar35sa_Mag"};

        backpack = "ls_mandalorian_medic_backpack";

        ALiVE_orbatCreator_loadout[] = {{},{},{"SWLW_Westar35SA","","","",{"SWLW_westar35sa_Mag",17},{},""},{"mgsr_robe_olive_dirty",{{"ACE_elasticBandage",8},{"ACE_fieldDressing",5},{"ACE_packingBandage",5}}},{"mgsr_carrier_belt",{{"JLTS_drugs_stimulant_hyperAdrenal",1},{"OPTRE_M2_Smoke",2,1},{"ACE_HandFlare_White",2,1},{"SWLW_westar35sa_Mag",3,17}}},{"ls_mandalorian_medic_backpack",{{"ACE_tourniquet",16},{"ACE_splint",6},{"ACE_morphine",15},{"ACE_EntrenchingTool",1},{"ACE_elasticBandage",25},{"ACE_fieldDressing",20},{"ACE_packingBandage",20},{"ACE_quikclot",15},{"ACE_epinephrine",15},{"ACE_surgicalKit",1},{"adv_aceCPR_AED",1},{"ACE_bloodIV_500",3},{"ACE_bloodIV_250",3},{"ACE_bloodIV",2},{"JLTS_drugs_stimulant_battle",2},{"JLTS_drugs_stimulant_adrenal",2},{"JLTS_drugs_bacta",2},{"JLTS_drugs_bacta_red",2},{"JLTS_drugs_electrolit",2}}},"","mgsr_headbag_goggles",{},{"ItemMap","ItemcTab","SWLB_comlink_hush98_5","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_emblems_thehand'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_emblems_thehand";

    };

    class O_CSArmy_CS_Sniper_WDL_01 : O_CSArmy_CS_Rifleman_WDL_01 {
        author = "Wyvern Studios ";
        scope = 2;
        scopeCurator = 2;
        displayName = "[CS] Sniper";
        side = 0;
        faction = "O_CSArmy_WDL";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "mgsr_robe_olive_muddy";

        linkedItems[] = {"mgsr_vest_black","H_HelmetB_camo","ItemMap","SWLB_comlink_hush98","ItemCompass","ItemWatch","OPTRE_NVG"};
        respawnlinkedItems[] = {"mgsr_vest_black","H_HelmetB_camo","ItemMap","SWLB_comlink_hush98","ItemCompass","ItemWatch","OPTRE_NVG"};

        weapons[] = {"SWLW_sniper"};
        respawnWeapons[] = {"SWLW_sniper"};

        magazines[] = {"SWLW_sniper_Mag","SWLW_sniper_Mag"};
        respawnMagazines[] = {"SWLW_sniper_Mag","SWLW_sniper_Mag"};

        backpack = "B_CombinationUnitRespirator_01_F";

        ALiVE_orbatCreator_loadout[] = {{"SWLW_sniper","","","SWLW_sniper_scope",{"SWLW_sniper_Mag",10},{},""},{},{},{"mgsr_robe_olive_muddy",{{"ACE_elasticBandage",8},{"ACE_fieldDressing",5},{"ACE_packingBandage",5}}},{"mgsr_vest_black",{{"JLTS_drugs_stimulant_hyperAdrenal",1},{"OPTRE_M2_Smoke",2,1},{"ACE_HandFlare_White",2,1},{"SWLW_sniper_Mag",9,10}}},{"B_CombinationUnitRespirator_01_F",{{"ACE_tourniquet",4},{"ACE_splint",1},{"ACE_morphine",2},{"ACE_epinephrine",1},{"ACE_EntrenchingTool",1}}},"H_HelmetB_camo","mgsr_headbag_goggles",{},{"ItemMap","","SWLB_comlink_hush98","ItemCompass","ItemWatch","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_emblems_thehand'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_emblems_thehand";

    };

    class O_CSArmy_CS_Acolyte_WDL_01 : O_CSArmy_CS_Sniper_WDL_01 {
        author = "Wyvern Studios ";
        scope = 2;
        scopeCurator = 2;
        displayName = "[CS] Acolyte";
        side = 0;
        faction = "O_CSArmy_WDL";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "SS_DURAL_U";

        linkedItems[] = {"ls_cis_bxCommando_vest","mgsr_headbag","ItemMap","SWLB_comlink_hush98_1","ItemCompass","ItemWatch","OPTRE_NVG"};
        respawnlinkedItems[] = {"ls_cis_bxCommando_vest","mgsr_headbag","ItemMap","SWLB_comlink_hush98_1","ItemCompass","ItemWatch","OPTRE_NVG"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"SS_DURAL_U",{{"JLTS_drugs_deathstick",3},{"JLTS_drugs_electrolit",1},{"JLTS_drugs_bacta_red",1},{"JLTS_drugs_stimulant_hyperAdrenal",1}}},{"ls_cis_bxCommando_vest",{}},{},"mgsr_headbag","REVAN_CAPE",{},{"ItemMap","","SWLB_comlink_hush98_1","ItemCompass","ItemWatch","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_CSArmy_CS_Priest_WDL_01 : O_CSArmy_CS_Acolyte_WDL_01 {
        author = "Wyvern Studios ";
        scope = 2;
        scopeCurator = 2;
        displayName = "[CS] Priest";
        side = 0;
        faction = "O_CSArmy_WDL";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "SS_DURAL_U";

        linkedItems[] = {"ls_cis_bxCommando_vest","ItemMap","SWLB_comlink_hush98_1","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"ls_cis_bxCommando_vest","ItemMap","SWLB_comlink_hush98_1","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"SS_DURAL_U",{{"JLTS_intel_holocron_sith",1},{"JLTS_drugs_stimulant_hyperAdrenal",2},{"JLTS_intel_datacard",1},{"JLTS_drugs_deathstick",4},{"JLTS_drugs_electrolit",2},{"JLTS_credits_5000",2},{"JLTS_credits_500",2},{"JLTS_credits_50",4}}},{"ls_cis_bxCommando_vest",{}},{},"","Shadow_mask",{},{"ItemMap","","SWLB_comlink_hush98_1","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_CSArmy_CS_Rusher_WDL_01 : O_CSArmy_CS_Priest_WDL_01 {
        author = "Wyvern Studios ";
        scope = 2;
        scopeCurator = 2;
        displayName = "[CS] Rusher";
        side = 0;
        faction = "O_CSArmy_WDL";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "mgsr_robe_olive_muddy";

        linkedItems[] = {"mgsr_carrier_belt","ItemMap","ItemcTab","SWLB_comlink_hush98_2","ItemCompass","ItemWatch","OPTRE_NVG"};
        respawnlinkedItems[] = {"mgsr_carrier_belt","ItemMap","ItemcTab","SWLB_comlink_hush98_2","ItemCompass","ItemWatch","OPTRE_NVG"};

        weapons[] = {"SWLW_westar35c"};
        respawnWeapons[] = {"SWLW_westar35c"};

        magazines[] = {"SWLW_westar35c_Mag","SWLW_westar35c_Mag"};
        respawnMagazines[] = {"SWLW_westar35c_Mag","SWLW_westar35c_Mag"};

        backpack = "B_LegStrapBag_black_F";

        ALiVE_orbatCreator_loadout[] = {{"SWLW_westar35c","","","",{"SWLW_westar35c_Mag",35},{},""},{},{},{"mgsr_robe_olive_muddy",{{"ACE_elasticBandage",8},{"ACE_fieldDressing",5},{"ACE_packingBandage",5}}},{"mgsr_carrier_belt",{{"JLTS_drugs_stimulant_hyperAdrenal",1},{"OPTRE_M2_Smoke",2,1},{"ACE_HandFlare_White",2,1},{"SWLW_westar35c_Mag",3,35}}},{"B_LegStrapBag_black_F",{{"ACE_tourniquet",4},{"ACE_splint",1},{"ACE_morphine",2},{"ACE_epinephrine",1},{"ACE_EntrenchingTool",1}}},"","Shadow_mask",{},{"ItemMap","ItemcTab","SWLB_comlink_hush98_2","ItemCompass","ItemWatch","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_emblems_thehand'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_emblems_thehand";

    };

    class O_CSArmy_CS_Crusader_WDL_01 : O_CSArmy_CS_Rusher_WDL_01 {
        author = "Wyvern Studios ";
        scope = 2;
        scopeCurator = 2;
        displayName = "[CS] Crusader";
        side = 0;
        faction = "O_CSArmy_WDL";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "mgsr_fatigues_black";

        linkedItems[] = {"OPTRE_UNSC_M52A_Armor1_URB","mgsr_headbag","ItemMap","ItemcTab","SWLB_comlink_hush98_4","ItemCompass","ItemWatch","OPTRE_NVG"};
        respawnlinkedItems[] = {"OPTRE_UNSC_M52A_Armor1_URB","mgsr_headbag","ItemMap","ItemcTab","SWLB_comlink_hush98_4","ItemCompass","ItemWatch","OPTRE_NVG"};

        weapons[] = {"3AS_DC15L_F"};
        respawnWeapons[] = {"3AS_DC15L_F"};

        magazines[] = {"3AS_200Rnd_EC40_Mag","3AS_200Rnd_EC40_Mag"};
        respawnMagazines[] = {"3AS_200Rnd_EC40_Mag","3AS_200Rnd_EC40_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"3AS_DC15L_F","","","",{"3AS_200Rnd_EC40_Mag",200},{},""},{},{},{"mgsr_fatigues_black",{{"ACE_elasticBandage",8},{"ACE_fieldDressing",5},{"ACE_packingBandage",5}}},{"OPTRE_UNSC_M52A_Armor1_URB",{{"JLTS_drugs_stimulant_hyperBattle",2},{"JLTS_drugs_deathstick",2},{"442_thermal_det_mag",2,1},{"3AS_200Rnd_EC40_Mag",3,200}}},{},"mgsr_headbag","REVAN_CAPE",{},{"ItemMap","ItemcTab","SWLB_comlink_hush98_4","ItemCompass","ItemWatch","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_emblems_thehand'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_emblems_thehand";

    };

    class O_CSArmy_CS_M12_Transport_WDL_01 : OPTRE_M12_ins_APC_OCimport_02 {
        author = "Wyvern Studios ";
        scope = 2;
        scopeCurator = 2;
        displayName = "[CS] M12-Transport";
        side = 0;
        faction = "O_CSArmy_WDL";
        crew = "O_CSArmy_CS_Rifleman_WDL_01";

        class Turrets : Turrets {
            class CargoGunner_1 : CargoGunner_1 { gunnerType = "O_CSArmy_CS_Rifleman_WDL_01"; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = "O_CSArmy_CS_Rifleman_WDL_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\OPTRE_Vehicles\Warthog\data\M12HogMaav_extupper_co.paa'];_unit setObjectTextureGlobal [1,'\OPTRE_Vehicles\Warthog\data\M12HogMaav_extunder_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "colorstand";

    };

};