//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 200.146773 on Stable branch
// Generated with ALiVE version 1.12.1.2002131
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class I_PAFArmy {
        displayName = "Planetary Armed Forces ";
        side = 2;
        flag = "\OPTRE_Core\Data\flag_caa_ca.paa";
        icon = "\OPTRE_Core\Data\flag_caa_ca.paa";
        priority = 0;
    };
};

class CfgGroups {
    class Indep {

        class I_PAFArmy {
            name = "Planetary Armed Forces ";

            class Infantry {
                name = "Infantry";

                class i_pafarmy_infantry_squad {
                    name = "Squad";
                    side = 2;
                    faction = "I_PAFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_PAFArmy_PDF_Officer_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_PAFArmy_PDF_Rifleman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_PAFArmy_PDF_Medic_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_PAFArmy_PDF_AT_Soldier_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_PAFArmy_PDF_Rifleman_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_PAFArmy_PDF_Rifleman_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_PAFArmy_PDF_Rifleman_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_PAFArmy_PDF_Auto_Rifleman_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_PAFArmy_PDF_Rifleman_01";
                    };
                };

                class i_pafarmy_infantry_fireteam {
                    name = "Fireteam";
                    side = 2;
                    faction = "I_PAFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_PAFArmy_PDF_Rifleman_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_PAFArmy_PDF_Rifleman_01";
                    };
                    class Unit2 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_PAFArmy_PDF_Rifleman_01";
                    };
                    class Unit3 {
                        position[] = {-5,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_PAFArmy_PDF_Rifleman_01";
                    };
                };

                class i_pafarmy_infantry_patrol_unit {
                    name = "Patrol Unit";
                    side = 2;
                    faction = "I_PAFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_PAFArmy_PF_Officer_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_PAFArmy_PF_Deputy_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_PAFArmy_PF_Deputy_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_PAFArmy_PF_Medical_Officer_01";
                    };
                };

                class i_pafarmy_infantry_patrol_unit_cis {
                    name = "Patrol Unit (CIS)";
                    side = 2;
                    faction = "I_PAFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_PAFArmy_PF_Deputy_CIS_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_PAFArmy_PF_Deputy_CIS_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_PAFArmy_PF_Deputy_CIS_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_PAFArmy_PF_Deputy_CIS_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class I_G_Soldier_F;
    class I_G_Soldier_F_OCimport_01 : I_G_Soldier_F { scope = 0; class EventHandlers; };
    class I_G_Soldier_F_OCimport_02 : I_G_Soldier_F_OCimport_01 { class EventHandlers; };

    class OPTRE_M12_FAV_PD;
    class OPTRE_M12_FAV_PD_OCimport_01 : OPTRE_M12_FAV_PD { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_M12_FAV_PD_OCimport_02 : OPTRE_M12_FAV_PD_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoGunner_1;
            class CargoTurret_02;
            class CargoTurret_03;
        };
    };

    class OPTRE_M12_FAV;
    class OPTRE_M12_FAV_OCimport_01 : OPTRE_M12_FAV { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_M12_FAV_OCimport_02 : OPTRE_M12_FAV_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoGunner_1;
            class CargoTurret_02;
            class CargoTurret_03;
        };
    };


    class I_PAFArmy_PDF_Rifleman_01 : I_G_Soldier_F_OCimport_02 {
        author = "Wyvern Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "[PDF] Rifleman";
        side = 2;
        faction = "I_PAFArmy";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "OPTRE_Ins_URF_Combat_Uniform";

        linkedItems[] = {"OPTRE_UNSC_M52A_Armor4_MAR","OPTRE_UNSC_CH252_Helmet_MAR","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"OPTRE_UNSC_M52A_Armor4_MAR","OPTRE_UNSC_CH252_Helmet_MAR","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","ItemWatch"};

        weapons[] = {"SWLW_Westar35S"};
        respawnWeapons[] = {"SWLW_Westar35S"};

        magazines[] = {"SWLW_Westar35S_Mag","SWLW_Westar35S_Mag"};
        respawnMagazines[] = {"SWLW_Westar35S_Mag","SWLW_Westar35S_Mag"};

        backpack = "B_LegStrapBag_black_F";

        ALiVE_orbatCreator_loadout[] = {{"SWLW_Westar35S","","","",{"SWLW_Westar35S_Mag",35},{},""},{},{},{"OPTRE_Ins_URF_Combat_Uniform",{{"ACE_elasticBandage",5},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_epinephrine",1},{"ACE_morphine",2},{"ACE_tourniquet",1},{"ACE_EntrenchingTool",1}}},{"OPTRE_UNSC_M52A_Armor4_MAR",{{"SWLW_Westar35S_Mag",12,35}}},{"B_LegStrapBag_black_F",{{"442_thermal_det_mag",2,1},{"3AS_SmokeWhite",1,1},{"3AS_SmokeBlue",1,1},{"3AS_SmokeGreen",1,1}}},"OPTRE_UNSC_CH252_Helmet_MAR","",{},{"ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'LS_INSIGNIA_ORSF'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "LS_INSIGNIA_ORSF";

    };

    class I_PAFArmy_PDF_Medic_01 : I_PAFArmy_PDF_Rifleman_01 {
        author = "Wyvern Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "[PDF] Medic";
        side = 2;
        faction = "I_PAFArmy";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "OPTRE_Ins_URF_Combat_Uniform";

        linkedItems[] = {"OPTRE_UNSC_M52A_Armor4_MAR","OPTRE_UNSC_CH252_Helmet_SNO_MED","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"OPTRE_UNSC_M52A_Armor4_MAR","OPTRE_UNSC_CH252_Helmet_SNO_MED","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","ItemWatch"};

        weapons[] = {"SWLW_westar35c"};
        respawnWeapons[] = {"SWLW_westar35c"};

        magazines[] = {"SWLW_westar35c_Mag","SWLW_westar35c_Mag"};
        respawnMagazines[] = {"SWLW_westar35c_Mag","SWLW_westar35c_Mag"};

        backpack = "ls_mandalorian_medic_backpack";

        ALiVE_orbatCreator_loadout[] = {{"SWLW_westar35c","","","",{"SWLW_westar35c_Mag",35},{},""},{},{},{"OPTRE_Ins_URF_Combat_Uniform",{{"ACE_elasticBandage",5},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_epinephrine",1},{"ACE_morphine",2},{"ACE_tourniquet",1},{"ACE_EntrenchingTool",1}}},{"OPTRE_UNSC_M52A_Armor4_MAR",{{"SWLW_westar35c_Mag",12,35}}},{"ls_mandalorian_medic_backpack",{{"ACE_elasticBandage",15},{"ACE_fieldDressing",15},{"ACE_packingBandage",15},{"ACE_quikclot",10},{"ACE_epinephrine",5},{"ACE_morphine",5},{"ACE_salineIV_250",2},{"ACE_salineIV_500",1},{"ACE_salineIV",1},{"ACE_splint",4},{"ACE_tourniquet",8},{"ACE_surgicalKit",1},{"adv_aceCPR_AED",1},{"442_thermal_det_mag",2,1},{"3AS_SmokeWhite",1,1},{"3AS_SmokeBlue",1,1},{"3AS_SmokeGreen",1,1}}},"OPTRE_UNSC_CH252_Helmet_SNO_MED","",{},{"ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'LS_INSIGNIA_ORSF'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "LS_INSIGNIA_ORSF";

    };

    class I_PAFArmy_PDF_AT_Soldier_01 : I_PAFArmy_PDF_Rifleman_01 {
        author = "Wyvern Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "[PDF] AT Soldier";
        side = 2;
        faction = "I_PAFArmy";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "OPTRE_Ins_URF_Combat_Uniform";

        linkedItems[] = {"OPTRE_UNSC_M52A_Armor4_MAR","OPTRE_UNSC_CH252_Helmet_MAR","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"OPTRE_UNSC_M52A_Armor4_MAR","OPTRE_UNSC_CH252_Helmet_MAR","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","ItemWatch"};

        weapons[] = {"SWLW_Westar35S","JLTS_RPS6"};
        respawnWeapons[] = {"SWLW_Westar35S","JLTS_RPS6"};

        magazines[] = {"SWLW_Westar35S_Mag","JLTS_RPS6_mag","SWLW_Westar35S_Mag"};
        respawnMagazines[] = {"SWLW_Westar35S_Mag","JLTS_RPS6_mag","SWLW_Westar35S_Mag"};

        backpack = "ls_mandalorian_heavy_backpack";

        ALiVE_orbatCreator_loadout[] = {{"SWLW_Westar35S","","","",{"SWLW_Westar35S_Mag",35},{},""},{"JLTS_RPS6","","","",{"JLTS_RPS6_mag",1},{},""},{},{"OPTRE_Ins_URF_Combat_Uniform",{{"ACE_elasticBandage",5},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_epinephrine",1},{"ACE_morphine",2},{"ACE_tourniquet",1},{"ACE_EntrenchingTool",1}}},{"OPTRE_UNSC_M52A_Armor4_MAR",{{"SWLW_Westar35S_Mag",12,35}}},{"ls_mandalorian_heavy_backpack",{{"442_thermal_det_mag",2,1},{"3AS_SmokeWhite",1,1},{"3AS_SmokeBlue",1,1},{"3AS_SmokeGreen",1,1},{"JLTS_RPS6_mag",2,1},{"JLTS_RPS6_HE_mag",2,1}}},"OPTRE_UNSC_CH252_Helmet_MAR","",{},{"ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'LS_INSIGNIA_ORSF'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "LS_INSIGNIA_ORSF";

    };

    class I_PAFArmy_PDF_Officer_01 : I_PAFArmy_PDF_Rifleman_01 {
        author = "Wyvern Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "[PDF] Officer";
        side = 2;
        faction = "I_PAFArmy";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "OPTRE_Ins_URF_Combat_Uniform";

        linkedItems[] = {"OPTRE_UNSC_M52A_Armor4_MAR","H_MilCap_grn","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"OPTRE_UNSC_M52A_Armor4_MAR","H_MilCap_grn","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","ItemWatch"};

        weapons[] = {"SWLW_Westar35S","JLTS_DC17SA"};
        respawnWeapons[] = {"SWLW_Westar35S","JLTS_DC17SA"};

        magazines[] = {"SWLW_Westar35S_Mag","JLTS_DC17SA_mag","SWLW_Westar35S_Mag","JLTS_DC17SA_mag"};
        respawnMagazines[] = {"SWLW_Westar35S_Mag","JLTS_DC17SA_mag","SWLW_Westar35S_Mag","JLTS_DC17SA_mag"};

        backpack = "B_LegStrapBag_black_F";

        ALiVE_orbatCreator_loadout[] = {{"SWLW_Westar35S","","","",{"SWLW_Westar35S_Mag",35},{},""},{},{"JLTS_DC17SA","","","",{"JLTS_DC17SA_mag",20},{},""},{"OPTRE_Ins_URF_Combat_Uniform",{{"ACE_elasticBandage",5},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_epinephrine",1},{"ACE_morphine",2},{"ACE_tourniquet",1},{"ACE_EntrenchingTool",1}}},{"OPTRE_UNSC_M52A_Armor4_MAR",{{"SWLW_Westar35S_Mag",10,35},{"JLTS_DC17SA_mag",3,20}}},{"B_LegStrapBag_black_F",{{"442_thermal_det_mag",2,1},{"3AS_SmokeWhite",1,1},{"3AS_SmokeBlue",1,1},{"3AS_SmokeGreen",1,1}}},"H_MilCap_grn","",{},{"ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'LS_INSIGNIA_ORSF'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "LS_INSIGNIA_ORSF";

    };

    class I_PAFArmy_PDF_Grenadier_01 : I_PAFArmy_PDF_Rifleman_01 {
        author = "Wyvern Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "[PDF] Grenadier";
        side = 2;
        faction = "I_PAFArmy";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "OPTRE_Ins_URF_Combat_Uniform";

        linkedItems[] = {"OPTRE_UNSC_M52A_Armor4_MAR","OPTRE_UNSC_CH252_Helmet_MAR","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"OPTRE_UNSC_M52A_Armor4_MAR","OPTRE_UNSC_CH252_Helmet_MAR","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","ItemWatch"};

        weapons[] = {"3AS_DC15C_GL"};
        respawnWeapons[] = {"3AS_DC15C_GL"};

        magazines[] = {"3AS_40Rnd_EC40_Mag","3AS_40Rnd_EC40_Mag"};
        respawnMagazines[] = {"3AS_40Rnd_EC40_Mag","3AS_40Rnd_EC40_Mag"};

        backpack = "ls_mandalorian_demo_backpack";

        ALiVE_orbatCreator_loadout[] = {{"3AS_DC15C_GL","","","",{"3AS_40Rnd_EC40_Mag",40},{},""},{},{},{"OPTRE_Ins_URF_Combat_Uniform",{{"ACE_elasticBandage",5},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_epinephrine",1},{"ACE_morphine",2},{"ACE_tourniquet",1},{"ACE_EntrenchingTool",1}}},{"OPTRE_UNSC_M52A_Armor4_MAR",{{"3AS_40Rnd_EC40_Mag",14,40}}},{"ls_mandalorian_demo_backpack",{{"442_thermal_det_mag",2,1},{"3AS_SmokeWhite",1,1},{"3AS_SmokeBlue",1,1},{"3AS_SmokeGreen",1,1},{"1Rnd_HE_Grenade_shell",7,1},{"UGL_FlareWhite_F",2,1},{"1Rnd_Smoke_Grenade_shell",2,1},{"ACE_40mm_Flare_white",2,1}}},"OPTRE_UNSC_CH252_Helmet_MAR","",{},{"ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'LS_INSIGNIA_ORSF'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "LS_INSIGNIA_ORSF";

    };

    class I_PAFArmy_PDF_Auto_Rifleman_01 : I_PAFArmy_PDF_Grenadier_01 {
        author = "Wyvern Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "[PDF] Auto-Rifleman";
        side = 2;
        faction = "I_PAFArmy";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "OPTRE_Ins_URF_Combat_Uniform";

        linkedItems[] = {"OPTRE_UNSC_M52A_Armor3_MAR","H_Bandanna_khk_hs","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"OPTRE_UNSC_M52A_Armor3_MAR","H_Bandanna_khk_hs","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","ItemWatch"};

        weapons[] = {"3AS_DC15L_F"};
        respawnWeapons[] = {"3AS_DC15L_F"};

        magazines[] = {"3AS_200Rnd_EC40_Mag","3AS_200Rnd_EC40_Mag"};
        respawnMagazines[] = {"3AS_200Rnd_EC40_Mag","3AS_200Rnd_EC40_Mag"};

        backpack = "ls_mandalorian_heavy_backpack";

        ALiVE_orbatCreator_loadout[] = {{"3AS_DC15L_F","","","",{"3AS_200Rnd_EC40_Mag",200},{},""},{},{},{"OPTRE_Ins_URF_Combat_Uniform",{{"ACE_elasticBandage",5},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_epinephrine",1},{"ACE_morphine",2},{"ACE_tourniquet",1},{"ACE_EntrenchingTool",1}}},{"OPTRE_UNSC_M52A_Armor3_MAR",{{"3AS_200Rnd_EC40_Mag",3,200}}},{"ls_mandalorian_heavy_backpack",{{"442_thermal_det_mag",2,1},{"3AS_SmokeWhite",1,1},{"3AS_SmokeBlue",1,1},{"3AS_SmokeGreen",1,1},{"3AS_200Rnd_EC40_Mag",5,200}}},"H_Bandanna_khk_hs","G_Tactical_Clear",{},{"ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'LS_INSIGNIA_ORSF'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "LS_INSIGNIA_ORSF";

    };

    class I_PAFArmy_PDF_Sniper_01 : I_PAFArmy_PDF_Auto_Rifleman_01 {
        author = "Wyvern Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "[PDF] Sniper";
        side = 2;
        faction = "I_PAFArmy";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "OPTRE_Ins_URF_Combat_Uniform";

        linkedItems[] = {"OPTRE_UNSC_M52A_Armor_Sniper_WDL","OPTRE_UNSC_CH252_Helmet3_WDL","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"OPTRE_UNSC_M52A_Armor_Sniper_WDL","OPTRE_UNSC_CH252_Helmet3_WDL","ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","ItemWatch"};

        weapons[] = {"SWLW_sniper","JLTS_DC17SA"};
        respawnWeapons[] = {"SWLW_sniper","JLTS_DC17SA"};

        magazines[] = {"SWLW_sniper_Mag","JLTS_DC17SA_mag","SWLW_sniper_Mag","JLTS_DC17SA_mag"};
        respawnMagazines[] = {"SWLW_sniper_Mag","JLTS_DC17SA_mag","SWLW_sniper_Mag","JLTS_DC17SA_mag"};

        backpack = "B_FieldPack_green_F";

        ALiVE_orbatCreator_loadout[] = {{"SWLW_sniper","","","SWLW_sniper_scope",{"SWLW_sniper_Mag",10},{},""},{},{"JLTS_DC17SA","","","",{"JLTS_DC17SA_mag",20},{},""},{"OPTRE_Ins_URF_Combat_Uniform",{{"ACE_elasticBandage",5},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_epinephrine",1},{"ACE_morphine",2},{"ACE_tourniquet",1},{"ACE_EntrenchingTool",1}}},{"OPTRE_UNSC_M52A_Armor_Sniper_WDL",{{"SWLW_sniper_Mag",3,10},{"JLTS_DC17SA_mag",3,20},{"JLTS_stun_mag_short",3,10}}},{"B_FieldPack_green_F",{{"JLTS_drugs_protein",2},{"442_thermal_det_mag",2,1},{"3AS_SmokeWhite",1,1},{"3AS_SmokeBlue",1,1},{"3AS_SmokeGreen",1,1},{"SWLW_sniper_Mag",5,10},{"JLTS_DC17SA_mag",3,20},{"JLTS_stun_mag_short",1,10},{"JLTS_stun_mag_long",1,5}}},"OPTRE_UNSC_CH252_Helmet3_WDL","G_Balaclava_TI_blk_F",{},{"ItemMap","ItemGPS","SWLB_comlink_hush98_2","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'LS_INSIGNIA_ORSF'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "LS_INSIGNIA_ORSF";

    };

    class I_PAFArmy_PF_Deputy_01 : I_PAFArmy_PDF_Rifleman_01 {
        author = "Wyvern Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "[PF] Deputy";
        side = 2;
        faction = "I_PAFArmy";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "U_B_GEN_Commander_F";

        linkedItems[] = {"OPTRE_UNSC_M52A_Armor_Soft","H_MilCap_blue","ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"OPTRE_UNSC_M52A_Armor_Soft","H_MilCap_blue","ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch"};

        weapons[] = {"JLTS_DC15S","JLTS_DC17SA"};
        respawnWeapons[] = {"JLTS_DC15S","JLTS_DC17SA"};

        magazines[] = {"JLTS_DC15A_mag","JLTS_DC17SA_mag","JLTS_DC15A_mag","JLTS_DC17SA_mag"};
        respawnMagazines[] = {"JLTS_DC15A_mag","JLTS_DC17SA_mag","JLTS_DC15A_mag","JLTS_DC17SA_mag"};

        backpack = "B_LegStrapBag_black_F";

        ALiVE_orbatCreator_loadout[] = {{"JLTS_DC15S","","","",{"JLTS_DC15A_mag",60},{},""},{},{"JLTS_DC17SA","","","",{"JLTS_DC17SA_mag",20},{},""},{"U_B_GEN_Commander_F",{}},{"OPTRE_UNSC_M52A_Armor_Soft",{{"JLTS_ids_police",1},{"JLTS_intel_trackingFob",1},{"JLTS_scanner_police",1},{"ACE_morphine",1},{"ACE_tourniquet",2},{"ACE_epinephrine",2},{"ACE_microDAGR",1},{"ACE_EarPlugs",1},{"ACE_CableTie",5},{"ACE_elasticBandage",10},{"ACE_packingBandage",5},{"ACE_fieldDressing",5}}},{"B_LegStrapBag_black_F",{{"JLTS_stun_mag_long",1,5},{"JLTS_stun_mag_short",1,10},{"JLTS_DC17SA_mag",3,20},{"JLTS_DC15S_mag",5,80}}},"H_MilCap_blue","",{},{"ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'LS_INSIGNIA_ORSF'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "LS_INSIGNIA_ORSF";

    };

    class I_PAFArmy_PF_Deputy_CIS_01 : I_PAFArmy_PF_Deputy_01 {
        author = "Wyvern Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "[PF] Deputy (CIS)";
        side = 2;
        faction = "I_PAFArmy";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "OPTRE_Ins_ER_uniform_GAtan";

        linkedItems[] = {"OPTRE_UNSC_M52A_Armor_Soft","H_MilCap_gry","ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"OPTRE_UNSC_M52A_Armor_Soft","H_MilCap_gry","ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch"};

        weapons[] = {"JLTS_E5"};
        respawnWeapons[] = {"JLTS_E5"};

        magazines[] = {"JLTS_E5_mag","JLTS_E5_mag"};
        respawnMagazines[] = {"JLTS_E5_mag","JLTS_E5_mag"};

        backpack = "B_LegStrapBag_black_F";

        ALiVE_orbatCreator_loadout[] = {{"JLTS_E5","","","",{"JLTS_E5_mag",100},{},""},{},{},{"OPTRE_Ins_ER_uniform_GAtan",{}},{"OPTRE_UNSC_M52A_Armor_Soft",{{"JLTS_ids_police",1},{"JLTS_intel_trackingFob",1},{"JLTS_scanner_police",1},{"ACE_morphine",1},{"ACE_tourniquet",2},{"ACE_epinephrine",2},{"ACE_microDAGR",1},{"ACE_EarPlugs",1},{"ACE_CableTie",5},{"ACE_elasticBandage",10},{"ACE_packingBandage",5},{"ACE_fieldDressing",5}}},{"B_LegStrapBag_black_F",{{"JLTS_E5_mag",6,100}}},"H_MilCap_gry","",{},{"ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'LS_INSIGNIA_ORSF'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "LS_INSIGNIA_ORSF";

    };

    class I_PAFArmy_PF_Officer_01 : I_PAFArmy_PF_Deputy_01 {
        author = "Wyvern Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "[PF] Officer";
        side = 2;
        faction = "I_PAFArmy";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "U_B_GEN_Commander_F";

        linkedItems[] = {"OPTRE_UNSC_M52A_Armor_Soft","H_Beret_gen_F","ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"OPTRE_UNSC_M52A_Armor_Soft","H_Beret_gen_F","ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch"};

        weapons[] = {"JLTS_DC17SA"};
        respawnWeapons[] = {"JLTS_DC17SA"};

        magazines[] = {"JLTS_DC17SA_mag","JLTS_DC17SA_mag"};
        respawnMagazines[] = {"JLTS_DC17SA_mag","JLTS_DC17SA_mag"};

        backpack = "B_LegStrapBag_black_F";

        ALiVE_orbatCreator_loadout[] = {{},{},{"JLTS_DC17SA","","","",{"JLTS_DC17SA_mag",20},{},""},{"U_B_GEN_Commander_F",{}},{"OPTRE_UNSC_M52A_Armor_Soft",{{"JLTS_ids_police",1},{"JLTS_intel_trackingFob",1},{"JLTS_scanner_police",1},{"ACE_morphine",1},{"ACE_tourniquet",2},{"ACE_epinephrine",2},{"ACE_microDAGR",1},{"ACE_EarPlugs",1},{"ACE_CableTie",5},{"ACE_elasticBandage",10},{"ACE_packingBandage",5},{"ACE_fieldDressing",5}}},{"B_LegStrapBag_black_F",{{"JLTS_DC17SA_mag",7,20},{"JLTS_stun_mag_short",1,10},{"JLTS_stun_mag_long",1,5}}},"H_Beret_gen_F","",{},{"ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'LS_INSIGNIA_ORSF'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "LS_INSIGNIA_ORSF";

    };

    class I_PAFArmy_PF_Medical_Officer_01 : I_PAFArmy_PF_Officer_01 {
        author = "Wyvern Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "[PF] Medical Officer";
        side = 2;
        faction = "I_PAFArmy";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "U_B_GEN_Commander_F";

        linkedItems[] = {"OPTRE_UNSC_M52A_Armor_Soft","H_PASGT_basic_white_F","ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"OPTRE_UNSC_M52A_Armor_Soft","H_PASGT_basic_white_F","ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch"};

        weapons[] = {"JLTS_DC15S","JLTS_DC17SA"};
        respawnWeapons[] = {"JLTS_DC15S","JLTS_DC17SA"};

        magazines[] = {"JLTS_stun_mag_short","JLTS_DC17SA_mag","JLTS_stun_mag_short","JLTS_DC17SA_mag"};
        respawnMagazines[] = {"JLTS_stun_mag_short","JLTS_DC17SA_mag","JLTS_stun_mag_short","JLTS_DC17SA_mag"};

        backpack = "B_Messenger_Black_F";

        ALiVE_orbatCreator_loadout[] = {{"JLTS_DC15S","","","",{},{"JLTS_stun_mag_short",10},""},{},{"JLTS_DC17SA","","","",{"JLTS_DC17SA_mag",20},{},""},{"U_B_GEN_Commander_F",{{"JLTS_DC15S_mag",3,80}}},{"OPTRE_UNSC_M52A_Armor_Soft",{{"JLTS_ids_police",1},{"JLTS_intel_trackingFob",1},{"JLTS_scanner_police",1},{"ACE_morphine",1},{"ACE_tourniquet",2},{"ACE_epinephrine",2},{"ACE_microDAGR",1},{"ACE_EarPlugs",1},{"ACE_CableTie",5},{"ACE_elasticBandage",10},{"ACE_packingBandage",5},{"ACE_fieldDressing",5},{"JLTS_stun_mag_short",3,10},{"JLTS_DC17SA_mag",3,20}}},{"B_Messenger_Black_F",{{"ACE_elasticBandage",10},{"ACE_fieldDressing",10},{"ACE_packingBandage",10},{"ACE_quikclot",5},{"ACE_epinephrine",5},{"ACE_morphine",5},{"ACE_salineIV_250",2},{"ACE_splint",2},{"JLTS_DC15S_mag",1,80},{"JLTS_stun_mag_long",1,5},{"JLTS_stun_mag_short",1,10}}},"H_PASGT_basic_white_F","G_Respirator_yellow_F",{},{"ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'LS_INSIGNIA_ORSF'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "LS_INSIGNIA_ORSF";

    };

    class I_PAFArmy_PF_Patrol_Car_01 : OPTRE_M12_FAV_PD_OCimport_02 {
        author = "Wyvern Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "[PF] Patrol Car";
        side = 2;
        faction = "I_PAFArmy";
        crew = "I_PAFArmy_PF_Deputy_01";

        class Turrets : Turrets {
            class CargoGunner_1 : CargoGunner_1 { gunnerType = "I_PAFArmy_PF_Deputy_01"; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_PAFArmy_PDF_AMG_Transport_01 : OPTRE_M12_FAV_OCimport_02 {
        author = "Wyvern Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "[PDF] AMG Transport";
        side = 2;
        faction = "I_PAFArmy";
        crew = "I_PAFArmy_PDF_Rifleman_01";

        class Turrets : Turrets {
            class CargoGunner_1 : CargoGunner_1 { gunnerType = "I_PAFArmy_PDF_Rifleman_01"; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = "I_PAFArmy_PDF_Rifleman_01"; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = "I_PAFArmy_PDF_Rifleman_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'OPTRE_Vehicles\Warthog\data\warthog_ins_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "colorinnie";

    };

};