//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 204.147719 on Stable branch
// Generated with ALiVE version 1.14.1.2105061
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class I_MPD {
        displayName = "Madrigal Police Department";
        side = 2;
        flag = "\OPTRE_Core\Data\flag_caa_ca.paa";
        icon = "\OPTRE_Core\Data\flag_caa_ca.paa";
        priority = 0;
    };
};

class CfgGroups {
    class Indep {

        class I_MPD {
            name = "Madrigal Police Department";

            class Infantry {
                name = "Infantry";

                class i_mpd_infantry_swat_team {
                    name = "SWAT Team";
                    side = 2;
                    faction = "I_MPD";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_MPD_SWAT_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_MPD_SWAT_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_MPD_SWAT_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_MPD_SWAT_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_MPD_SWAT_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class I_E_Soldier_F;
    class I_E_Soldier_F_OCimport_01 : I_E_Soldier_F { scope = 0; class EventHandlers; };
    class I_E_Soldier_F_OCimport_02 : I_E_Soldier_F_OCimport_01 { class EventHandlers; };

    class OPTRE_UNSC_falcon_PD;
    class OPTRE_UNSC_falcon_PD_OCimport_01 : OPTRE_UNSC_falcon_PD { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_UNSC_falcon_PD_OCimport_02 : OPTRE_UNSC_falcon_PD_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
        };
    };

    class OPTRE_M12_FAV_APC;
    class OPTRE_M12_FAV_APC_OCimport_01 : OPTRE_M12_FAV_APC { scope = 0; class EventHandlers; };
    class OPTRE_M12_FAV_APC_OCimport_02 : OPTRE_M12_FAV_APC_OCimport_01 { scope = 0; class EventHandlers; };

    class B_GEN_Offroad_01_covered_F;
    class B_GEN_Offroad_01_covered_F_OCimport_01 : B_GEN_Offroad_01_covered_F { scope = 0; class EventHandlers; class Turrets; };
    class B_GEN_Offroad_01_covered_F_OCimport_02 : B_GEN_Offroad_01_covered_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
        };
    };

    class B_GEN_Van_02_transport_F;
    class B_GEN_Van_02_transport_F_OCimport_01 : B_GEN_Van_02_transport_F { scope = 0; class EventHandlers; class Turrets; };
    class B_GEN_Van_02_transport_F_OCimport_02 : B_GEN_Van_02_transport_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
        };
    };


    class I_MPD_Rifleman_01 : I_E_Soldier_F_OCimport_02 {
        author = "LTC Denver";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman";
        side = 2;
        faction = "I_MPD";

        identityTypes[] = {"Head_Euro","LanguagePOL_F","G_HAF_default"};

        uniformClass = "U_B_GEN_Soldier_F";

        linkedItems[] = {"OPTRE_UNSC_M52A_Armor4_URB","H_Cap_police","ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"OPTRE_UNSC_M52A_Armor4_URB","H_Cap_police","ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_MA5C","OPTRE_M6C"};
        respawnWeapons[] = {"OPTRE_MA5C","OPTRE_M6C"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_12Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_12Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_12Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_12Rnd_127x40_Mag"};

        backpack = "B_LegStrapBag_black_F";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA5C","","","",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{},{"OPTRE_M6C","","","OPTRE_M6C_Scope",{"OPTRE_12Rnd_127x40_Mag",12},{},""},{"U_B_GEN_Soldier_F",{{"ACE_elasticBandage",5},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_CableTie",3},{"ACE_epinephrine",2},{"ACE_morphine",2},{"JLTS_scanner_police",1},{"ACE_splint",1},{"ACE_tourniquet",4},{"OPTRE_32Rnd_762x51_Mag",1,32}}},{"OPTRE_UNSC_M52A_Armor4_URB",{{"OPTRE_12Rnd_127x40_Mag",3,12},{"OPTRE_32Rnd_762x51_Mag",7,32}}},{"B_LegStrapBag_black_F",{{"ACE_M84",2,1}}},"H_Cap_police","G_Tactical_Clear",{},{"ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_osp'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_osp";

    };

    class I_MPD_Shotgun_01 : I_MPD_Rifleman_01 {
        author = "LTC Denver";
        scope = 2;
        scopeCurator = 2;
        displayName = "Shotgun";
        side = 2;
        faction = "I_MPD";

        identityTypes[] = {"Head_Euro","LanguagePOL_F","G_HAF_default"};

        uniformClass = "U_B_GEN_Soldier_F";

        linkedItems[] = {"OPTRE_UNSC_M52A_Armor4_URB","H_Cap_police","ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"OPTRE_UNSC_M52A_Armor4_URB","H_Cap_police","ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_M45","OPTRE_M6C"};
        respawnWeapons[] = {"OPTRE_M45","OPTRE_M6C"};

        magazines[] = {"OPTRE_6Rnd_8Gauge_Pellets","OPTRE_12Rnd_127x40_Mag","OPTRE_6Rnd_8Gauge_Pellets","OPTRE_12Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_6Rnd_8Gauge_Pellets","OPTRE_12Rnd_127x40_Mag","OPTRE_6Rnd_8Gauge_Pellets","OPTRE_12Rnd_127x40_Mag"};

        backpack = "B_LegStrapBag_black_F";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M45","","","",{"OPTRE_6Rnd_8Gauge_Pellets",6},{},""},{},{"OPTRE_M6C","","","OPTRE_M6C_Scope",{"OPTRE_12Rnd_127x40_Mag",12},{},""},{"U_B_GEN_Soldier_F",{{"ACE_elasticBandage",5},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_CableTie",3},{"ACE_epinephrine",2},{"ACE_morphine",2},{"JLTS_scanner_police",1},{"ACE_splint",1},{"ACE_tourniquet",4}}},{"OPTRE_UNSC_M52A_Armor4_URB",{{"OPTRE_12Rnd_127x40_Mag",3,12},{"OPTRE_6Rnd_8Gauge_Pellets",4,6},{"OPTRE_6Rnd_8Gauge_Slugs",3,6}}},{"B_LegStrapBag_black_F",{{"OPTRE_6Rnd_8Gauge_Pellets",2,6},{"OPTRE_6Rnd_8Gauge_Slugs",2,6},{"ACE_M84",2,1}}},"H_Cap_police","G_Tactical_Clear",{},{"ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_osp'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_osp";

    };

    class I_MPD_Patrol_Officer_01 : I_MPD_Rifleman_01 {
        author = "LTC Denver";
        scope = 2;
        scopeCurator = 2;
        displayName = "Patrol Officer";
        side = 2;
        faction = "I_MPD";

        identityTypes[] = {"Head_Euro","LanguagePOL_F","G_HAF_default"};

        uniformClass = "U_B_GEN_Soldier_F";

        linkedItems[] = {"OPTRE_UNSC_M52A_Armor4_URB","H_Cap_police","ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"OPTRE_UNSC_M52A_Armor4_URB","H_Cap_police","ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_M6C"};
        respawnWeapons[] = {"OPTRE_M6C"};

        magazines[] = {"OPTRE_12Rnd_127x40_Mag","OPTRE_12Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_12Rnd_127x40_Mag","OPTRE_12Rnd_127x40_Mag"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"OPTRE_M6C","","","OPTRE_M6C_Scope",{"OPTRE_12Rnd_127x40_Mag",12},{},""},{"U_B_GEN_Soldier_F",{{"ACE_elasticBandage",5},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_CableTie",3},{"ACE_epinephrine",2},{"ACE_morphine",2},{"JLTS_scanner_police",1},{"ACE_splint",1},{"ACE_tourniquet",4}}},{"OPTRE_UNSC_M52A_Armor4_URB",{{"OPTRE_12Rnd_127x40_Mag",5,12}}},{},"H_Cap_police","G_Tactical_Clear",{},{"ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_osp'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_osp";

    };

    class I_MPD_Pilot_01 : I_MPD_Rifleman_01 {
        author = "LTC Denver";
        scope = 2;
        scopeCurator = 2;
        displayName = "Pilot";
        side = 2;
        faction = "I_MPD";

        identityTypes[] = {"Head_Euro","LanguagePOL_F","G_HAF_default"};

        uniformClass = "U_B_GEN_Soldier_F";

        linkedItems[] = {"OPTRE_UNSC_M52A_Armor_Pilot_AF","OPTRE_UNSC_CH252_Helmet_SNO","ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"OPTRE_UNSC_M52A_Armor_Pilot_AF","OPTRE_UNSC_CH252_Helmet_SNO","ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_M6C"};
        respawnWeapons[] = {"OPTRE_M6C"};

        magazines[] = {"OPTRE_12Rnd_127x40_Mag","OPTRE_12Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_12Rnd_127x40_Mag","OPTRE_12Rnd_127x40_Mag"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"OPTRE_M6C","","","OPTRE_M6C_Scope",{"OPTRE_12Rnd_127x40_Mag",12},{},""},{"U_B_GEN_Soldier_F",{{"ACE_elasticBandage",5},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_CableTie",3},{"ACE_epinephrine",2},{"ACE_morphine",2},{"JLTS_scanner_police",1},{"ACE_splint",1},{"ACE_tourniquet",4}}},{"OPTRE_UNSC_M52A_Armor_Pilot_AF",{{"OPTRE_12Rnd_127x40_Mag",5,12}}},{},"OPTRE_UNSC_CH252_Helmet_SNO","G_Aviator",{},{"ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_osp'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_osp";

    };

    class I_MPD_SWAT_01 : I_MPD_Rifleman_01 {
        author = "LTC Denver";
        scope = 2;
        scopeCurator = 2;
        displayName = "SWAT";
        side = 2;
        faction = "I_MPD";

        identityTypes[] = {"Head_Euro","LanguagePOL_F","G_HAF_default"};

        uniformClass = "U_B_GEN_Commander_F";

        linkedItems[] = {"OPTRE_UNSC_M52A_Armor2_URB","OPTRE_UNSC_CH252_Helmet2_URB","ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"OPTRE_UNSC_M52A_Armor2_URB","OPTRE_UNSC_CH252_Helmet2_URB","ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_MA5C","OPTRE_M6C"};
        respawnWeapons[] = {"OPTRE_MA5C","OPTRE_M6C"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_12Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_12Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_12Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_12Rnd_127x40_Mag"};

        backpack = "OPTRE_UNSC_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA5C","","acc_pointer_IR","OPTRE_MA5C_SmartLink",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{},{"OPTRE_M6C","","","OPTRE_M6C_Scope",{"OPTRE_12Rnd_127x40_Mag",12},{},""},{"U_B_GEN_Commander_F",{{"ACE_elasticBandage",5},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_CableTie",3},{"ACE_epinephrine",2},{"ACE_morphine",2},{"JLTS_scanner_police",1},{"ACE_splint",1},{"ACE_tourniquet",4}}},{"OPTRE_UNSC_M52A_Armor2_URB",{{"OPTRE_12Rnd_127x40_Mag",3,12},{"OPTRE_32Rnd_762x51_Mag",7,32}}},{"OPTRE_UNSC_Rucksack",{{"ACE_CableTie",5},{"ACE_M84",2,1},{"OPTRE_M2_Smoke",4,1}}},"OPTRE_UNSC_CH252_Helmet2_URB","G_Balaclava_TI_blk_F",{},{"ItemMap","ItemcTab","tf_anprc152_1","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_osp'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_osp";

    };

    class I_MPD_UH_144_Falcon_Police_01 : OPTRE_UNSC_falcon_PD_OCimport_02 {
        author = "LTC Denver";
        scope = 2;
        scopeCurator = 2;
        displayName = "UH-144 Falcon [Police]";
        side = 2;
        faction = "I_MPD";
        crew = "I_MPD_Pilot_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = "I_MPD_Rifleman_01"; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = "I_MPD_Rifleman_01"; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = "I_MPD_Rifleman_01"; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = "I_MPD_Rifleman_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_MPD_M12_APC_SWAT_01 : OPTRE_M12_FAV_APC_OCimport_02 {
        author = "LTC Denver";
        scope = 2;
        scopeCurator = 2;
        displayName = "M12 APC [SWAT]";
        side = 2;
        faction = "I_MPD";
        crew = "I_MPD_SWAT_01";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\OPTRE_Vehicles\Warthog\data\night\M12HogMaav_extupper_night_co.paa'];_unit setObjectTextureGlobal [1,'\OPTRE_Vehicles\Warthog\data\night\M12HogMaav_extunder_night_co.paa'];_unit setObjectTextureGlobal [2,'\OPTRE_Vehicles\Warthog\data\night\transp_lopo_night_co.paa'];_unit setObjectTextureGlobal [3,'\OPTRE_Vehicles\Warthog\data\night\hog_apc_night_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "colornight";

    };

    class I_MPD_MPD_Patrol_Vehicle_01 : B_GEN_Offroad_01_covered_F_OCimport_02 {
        author = "LTC Denver";
        scope = 2;
        scopeCurator = 2;
        displayName = "MPD Patrol Vehicle";
        side = 2;
        faction = "I_MPD";
        crew = "I_MPD_Patrol_Officer_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_MPD_MPD_Van_01 : B_GEN_Van_02_transport_F_OCimport_02 {
        author = "LTC Denver";
        scope = 2;
        scopeCurator = 2;
        displayName = "MPD Van";
        side = 2;
        faction = "I_MPD";
        crew = "I_MPD_Rifleman_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = "I_MPD_Rifleman_01"; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = "I_MPD_Rifleman_01"; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = "I_MPD_Rifleman_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};