//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 200.146773 on Stable branch
// Generated with ALiVE version 1.12.1.2002131
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class O_CIS {
        displayName = "CIS Special Operations";
        side = 0;
        flag = "\MRC\JLTS\Core_mod_droids\data\markers\flags\cis_ca.paa";
        icon = "\MRC\JLTS\Core_mod_droids\data\markers\flags\cis_ca.paa";
        priority = 0;
    };
};

class CfgGroups {
    class EAST {

        class O_CIS {
            name = "CIS Special Operations";

            class Infantry {
                name = "Infantry";

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class O_soldier_Melee;
    class O_soldier_Melee_OCimport_01 : O_soldier_Melee { scope = 0; class EventHandlers; };
    class O_soldier_Melee_OCimport_02 : O_soldier_Melee_OCimport_01 { class EventHandlers; };


    class O_CIS_Commando_Droid_Secuirty_01 : O_soldier_Melee_OCimport_02 {
        author = "Wyvern Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "Commando Droid (Secuirty)";
        side = 0;
        faction = "O_CIS";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "ls_cis_bxDroid_uniform";

        linkedItems[] = {"ls_cis_bxCommando_vest","ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"ls_cis_bxCommando_vest","ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch"};

        weapons[] = {"JLTS_E5","WBK_Dutch_Vibro"};
        respawnWeapons[] = {"JLTS_E5","WBK_Dutch_Vibro"};

        magazines[] = {"JLTS_E5_mag","WBK_Cybercrystal","JLTS_E5_mag","WBK_Cybercrystal"};
        respawnMagazines[] = {"JLTS_E5_mag","WBK_Cybercrystal","JLTS_E5_mag","WBK_Cybercrystal"};

        ALiVE_orbatCreator_loadout[] = {{"JLTS_E5","","","",{"JLTS_E5_mag",100},{},""},{},{"WBK_Dutch_Vibro","","","",{"WBK_Cybercrystal",30},{},""},{"ls_cis_bxDroid_uniform",{{"WBK_Cybercrystal",1,30},{"442_thermal_det_mag",2,1},{"JLTS_E5_mag",9,100}}},{"ls_cis_bxCommando_vest",{}},{},"","",{},{"ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'LS_INSIGNIA_ORSF'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "LS_INSIGNIA_ORSF";

    };

    class O_CIS_Commando_Droid_Security_01 : O_soldier_Melee_OCimport_02 {
        author = "Wyvern Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "Commando Droid (Security)";
        side = 0;
        faction = "O_CIS";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "ls_cis_bxSecurityDroid_uniform";

        linkedItems[] = {"ls_cis_bxCommando_vest","ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"ls_cis_bxCommando_vest","ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch"};

        weapons[] = {"WBK_Dutch_Vibro"};
        respawnWeapons[] = {"WBK_Dutch_Vibro"};

        magazines[] = {"WBK_Cybercrystal","WBK_Cybercrystal"};
        respawnMagazines[] = {"WBK_Cybercrystal","WBK_Cybercrystal"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"WBK_Dutch_Vibro","","","",{"WBK_Cybercrystal",30},{},""},{"ls_cis_bxSecurityDroid_uniform",{{"WBK_Cybercrystal",1,30},{"442_thermal_det_mag",2,1}}},{"ls_cis_bxCommando_vest",{}},{},"","",{},{"ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'LS_INSIGNIA_ORSF'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "LS_INSIGNIA_ORSF";

    };

    class O_CIS_Commando_Droid_01 : O_soldier_Melee_OCimport_02 {
        author = "Wyvern Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "Commando Droid";
        side = 0;
        faction = "O_CIS";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "ls_cis_bxDroid_uniform";

        linkedItems[] = {"ls_cis_bxCommando_vest","ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"ls_cis_bxCommando_vest","ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch"};

        weapons[] = {"WBK_Dutch_Vibro"};
        respawnWeapons[] = {"WBK_Dutch_Vibro"};

        magazines[] = {"WBK_Cybercrystal","WBK_Cybercrystal"};
        respawnMagazines[] = {"WBK_Cybercrystal","WBK_Cybercrystal"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"WBK_Dutch_Vibro","","","",{"WBK_Cybercrystal",30},{},""},{"ls_cis_bxDroid_uniform",{{"WBK_Cybercrystal",1,30},{"442_thermal_det_mag",2,1}}},{"ls_cis_bxCommando_vest",{}},{},"","",{},{"ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'LS_INSIGNIA_ORSF'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "LS_INSIGNIA_ORSF";

    };

    class O_CIS_Commando_Droid_Captain_01 : O_soldier_Melee_OCimport_02 {
        author = "Wyvern Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "Commando Droid Captain";
        side = 0;
        faction = "O_CIS";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "ls_cis_bxCaptainDroid_uniform";

        linkedItems[] = {"ls_cis_bxCommando_vest","ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"ls_cis_bxCommando_vest","ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch"};

        weapons[] = {"WBK_Dutch_Vibro"};
        respawnWeapons[] = {"WBK_Dutch_Vibro"};

        magazines[] = {"WBK_Cybercrystal","WBK_Cybercrystal"};
        respawnMagazines[] = {"WBK_Cybercrystal","WBK_Cybercrystal"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"WBK_Dutch_Vibro","","","",{"WBK_Cybercrystal",30},{},""},{"ls_cis_bxCaptainDroid_uniform",{{"WBK_Cybercrystal",1,30},{"442_thermal_det_mag",2,1}}},{"ls_cis_bxCommando_vest",{}},{},"","",{},{"ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'LS_INSIGNIA_ORSF'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "LS_INSIGNIA_ORSF";

    };

    class O_CIS_Commando_Droid_Diplomat_01 : O_soldier_Melee_OCimport_02 {
        author = "Wyvern Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "Commando Droid (Diplomat)";
        side = 0;
        faction = "O_CIS";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "ls_cis_bxDiplomatDroid_uniform";

        linkedItems[] = {"ls_cis_bxCommando_vest","ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"ls_cis_bxCommando_vest","ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch"};

        weapons[] = {"WBK_Dutch_Vibro"};
        respawnWeapons[] = {"WBK_Dutch_Vibro"};

        magazines[] = {"WBK_Cybercrystal","WBK_Cybercrystal"};
        respawnMagazines[] = {"WBK_Cybercrystal","WBK_Cybercrystal"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"WBK_Dutch_Vibro","","","",{"WBK_Cybercrystal",30},{},""},{"ls_cis_bxDiplomatDroid_uniform",{{"WBK_Cybercrystal",1,30},{"442_thermal_det_mag",2,1}}},{"ls_cis_bxCommando_vest",{}},{},"","",{},{"ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'LS_INSIGNIA_ORSF'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "LS_INSIGNIA_ORSF";

    };

    class O_CIS_Commando_Droid_Training_01 : O_soldier_Melee_OCimport_02 {
        author = "Wyvern Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "Commando Droid (Training)";
        side = 0;
        faction = "O_CIS";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "ls_cis_bxTraining_uniform";

        linkedItems[] = {"ls_cis_bxCommando_vest","ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"ls_cis_bxCommando_vest","ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch"};

        weapons[] = {"WBK_Dutch_Vibro"};
        respawnWeapons[] = {"WBK_Dutch_Vibro"};

        magazines[] = {"WBK_Cybercrystal","WBK_Cybercrystal"};
        respawnMagazines[] = {"WBK_Cybercrystal","WBK_Cybercrystal"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"WBK_Dutch_Vibro","","","",{"WBK_Cybercrystal",30},{},""},{"ls_cis_bxTraining_uniform",{{"WBK_Cybercrystal",1,30},{"442_thermal_det_mag",2,1}}},{"ls_cis_bxCommando_vest",{}},{},"","",{},{"ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'LS_INSIGNIA_ORSF'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "LS_INSIGNIA_ORSF";

    };

};