//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 200.146773 on Stable branch
// Generated with ALiVE version 1.12.1.2002131
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class I_BTArmy {
        displayName = "Black Tree Mercentile Union";
        side = 2;
        flag = "\MRC\JLTS\Core_mod_droids\data\markers\flags\cis_ca.paa";
        icon = "\MRC\JLTS\Core_mod_droids\data\markers\flags\cis_ca.paa";
        priority = 0;
    };
};

class CfgGroups {
    class Indep {

        class I_BTArmy {
            name = "Black Tree Mercentile Union";

            class Infantry {
                name = "Infantry";

                class i_btarmy_infantry_squad {
                    name = "Squad";
                    side = 2;
                    faction = "I_BTArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_BTArmy_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_BTArmy_Rifleman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_BTArmy_Rifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_BTArmy_Medic_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_BTArmy_AT_Soldier_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_BTArmy_Rifleman_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_BTArmy_Rifleman_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_BTArmy_Rifleman_01";
                    };
                };

                class i_btarmy_infantry_fire_team {
                    name = "Fire Team";
                    side = 2;
                    faction = "I_BTArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_BTArmy_Rifleman_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_BTArmy_Rifleman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_BTArmy_Rifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_BTArmy_Rifleman_01";
                    };
                };

                class i_btarmy_infantry_diplomat_security_team {
                    name = "Diplomat Security Team";
                    side = 2;
                    faction = "I_BTArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_BTArmy_Diplomat_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_BTArmy_Diplomat_Guard_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_BTArmy_Diplomat_Guard_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_BTArmy_Diplomat_Security_Droid_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_BTArmy_Diplomat_Security_Droid_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_BTArmy_Diplomat_Security_Droid_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_BTArmy_Diplomat_Security_Droid_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class I_G_Soldier_F;
    class I_G_Soldier_F_OCimport_01 : I_G_Soldier_F { scope = 0; class EventHandlers; };
    class I_G_Soldier_F_OCimport_02 : I_G_Soldier_F_OCimport_01 { class EventHandlers; };


    class I_BTArmy_Rifleman_01 : I_G_Soldier_F_OCimport_02 {
        author = "Wyvern Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman";
        side = 2;
        faction = "I_BTArmy";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "U_O_R_Gorka_01_black_F";

        linkedItems[] = {"OPTRE_UNSC_M52A_Armor_Sniper_URB","H_PASGT_basic_black_F","ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"OPTRE_UNSC_M52A_Armor_Sniper_URB","H_PASGT_basic_black_F","ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch"};

        weapons[] = {"SWLW_Westar35S"};
        respawnWeapons[] = {"SWLW_Westar35S"};

        magazines[] = {"SWLW_Westar35S_Mag","SWLW_Westar35S_Mag"};
        respawnMagazines[] = {"SWLW_Westar35S_Mag","SWLW_Westar35S_Mag"};

        backpack = "ls_mandalorian_standard_backpack";

        ALiVE_orbatCreator_loadout[] = {{"SWLW_Westar35S","","","SWLW_Westar35S_scope",{"SWLW_Westar35S_Mag",35},{},""},{},{},{"U_O_R_Gorka_01_black_F",{{"ACE_elasticBandage",10},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_epinephrine",1},{"ACE_morphine",1},{"ACE_tourniquet",2},{"ACE_EntrenchingTool",1},{"ACE_IR_Strobe_Item",1}}},{"OPTRE_UNSC_M52A_Armor_Sniper_URB",{{"SWLW_Westar35S_Mag",15,35}}},{"ls_mandalorian_standard_backpack",{{"ACE_SpraypaintBlack",1},{"442_thermal_det_mag",2,1},{"3AS_SmokeGreen",2,1},{"3AS_SmokeWhite",2,1},{"3AS_SmokeBlue",2,1}}},"H_PASGT_basic_black_F","G_Balaclava_TI_blk_F",{},{"ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_emblems_blackwidow'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_emblems_blackwidow";

    };

    class I_BTArmy_Medic_01 : I_BTArmy_Rifleman_01 {
        author = "Wyvern Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "Medic";
        side = 2;
        faction = "I_BTArmy";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "U_O_R_Gorka_01_black_F";

        linkedItems[] = {"OPTRE_UNSC_M52A_Armor_Sniper_URB","H_PASGT_basic_white_F","ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"OPTRE_UNSC_M52A_Armor_Sniper_URB","H_PASGT_basic_white_F","ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch"};

        weapons[] = {"SWLW_westar35c"};
        respawnWeapons[] = {"SWLW_westar35c"};

        magazines[] = {"SWLW_westar35c_Mag","SWLW_westar35c_Mag"};
        respawnMagazines[] = {"SWLW_westar35c_Mag","SWLW_westar35c_Mag"};

        backpack = "ls_mandalorian_medic_backpack";

        ALiVE_orbatCreator_loadout[] = {{"SWLW_westar35c","","","",{"SWLW_westar35c_Mag",35},{},""},{},{},{"U_O_R_Gorka_01_black_F",{{"ACE_elasticBandage",10},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_epinephrine",1},{"ACE_morphine",1},{"ACE_tourniquet",2},{"ACE_EntrenchingTool",1},{"ACE_IR_Strobe_Item",1}}},{"OPTRE_UNSC_M52A_Armor_Sniper_URB",{{"SWLW_westar35c_Mag",3,35}}},{"ls_mandalorian_medic_backpack",{{"ACE_splint",4},{"ACE_SpraypaintRed",1},{"ACE_morphine",15},{"ACE_epinephrine",15},{"ACE_packingBandage",15},{"ACE_elasticBandage",20},{"ACE_fieldDressing",15},{"ACE_quikclot",10},{"ACE_salineIV_250",2},{"ACE_salineIV_500",2},{"ACE_salineIV",1},{"442_thermal_det_mag",2,1},{"3AS_SmokeGreen",2,1},{"3AS_SmokeWhite",2,1},{"3AS_SmokeBlue",2,1}}},"H_PASGT_basic_white_F","G_Balaclava_TI_blk_F",{},{"ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_emblems_blackwidow'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_emblems_blackwidow";

    };

    class I_BTArmy_Leader_01 : I_BTArmy_Rifleman_01 {
        author = "Wyvern Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "Leader";
        side = 2;
        faction = "I_BTArmy";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "U_O_R_Gorka_01_black_F";

        linkedItems[] = {"OPTRE_UNSC_M52A_Armor_Sniper_URB","H_Beret_blk","ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"OPTRE_UNSC_M52A_Armor_Sniper_URB","H_Beret_blk","ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch"};

        weapons[] = {"SWLW_Westar35S"};
        respawnWeapons[] = {"SWLW_Westar35S"};

        magazines[] = {"SWLW_Westar35S_Mag","SWLW_Westar35S_Mag"};
        respawnMagazines[] = {"SWLW_Westar35S_Mag","SWLW_Westar35S_Mag"};

        backpack = "B_LegStrapBag_black_F";

        ALiVE_orbatCreator_loadout[] = {{"SWLW_Westar35S","","","SWLW_Westar35S_scope",{"SWLW_Westar35S_Mag",35},{},""},{},{},{"U_O_R_Gorka_01_black_F",{{"ACE_elasticBandage",10},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_epinephrine",1},{"ACE_morphine",1},{"ACE_tourniquet",2},{"ACE_EntrenchingTool",1},{"ACE_IR_Strobe_Item",1}}},{"OPTRE_UNSC_M52A_Armor_Sniper_URB",{{"SWLW_Westar35S_Mag",15,35}}},{"B_LegStrapBag_black_F",{{"ACE_SpraypaintBlack",1},{"442_thermal_det_mag",2,1},{"3AS_SmokeGreen",2,1},{"3AS_SmokeWhite",2,1},{"3AS_SmokeBlue",2,1}}},"H_Beret_blk","G_Balaclava_TI_blk_F",{},{"ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_emblems_blackwidow'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_emblems_blackwidow";

    };

    class I_BTArmy_AT_Soldier_01 : I_BTArmy_Rifleman_01 {
        author = "Wyvern Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "AT Soldier";
        side = 2;
        faction = "I_BTArmy";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "U_O_R_Gorka_01_black_F";

        linkedItems[] = {"OPTRE_UNSC_M52A_Armor_Sniper_URB","H_PASGT_basic_black_F","ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"OPTRE_UNSC_M52A_Armor_Sniper_URB","H_PASGT_basic_black_F","ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch"};

        weapons[] = {"SWLW_Westar35S","JLTS_RPS6"};
        respawnWeapons[] = {"SWLW_Westar35S","JLTS_RPS6"};

        magazines[] = {"SWLW_Westar35S_Mag","JLTS_RPS6_mag","SWLW_Westar35S_Mag"};
        respawnMagazines[] = {"SWLW_Westar35S_Mag","JLTS_RPS6_mag","SWLW_Westar35S_Mag"};

        backpack = "ls_mandalorian_demo_backpack";

        ALiVE_orbatCreator_loadout[] = {{"SWLW_Westar35S","","","SWLW_Westar35S_scope",{"SWLW_Westar35S_Mag",35},{},""},{"JLTS_RPS6","","","",{"JLTS_RPS6_mag",1},{},""},{},{"U_O_R_Gorka_01_black_F",{{"ACE_elasticBandage",10},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_epinephrine",1},{"ACE_morphine",1},{"ACE_tourniquet",2},{"ACE_EntrenchingTool",1},{"ACE_IR_Strobe_Item",1}}},{"OPTRE_UNSC_M52A_Armor_Sniper_URB",{{"SWLW_Westar35S_Mag",15,35}}},{"ls_mandalorian_demo_backpack",{{"ACE_SpraypaintBlack",1},{"442_thermal_det_mag",2,1},{"3AS_SmokeGreen",2,1},{"3AS_SmokeWhite",2,1},{"3AS_SmokeBlue",2,1},{"JLTS_RPS6_mag",2,1},{"JLTS_RPS6_HE_mag",3,1}}},"H_PASGT_basic_black_F","G_Balaclava_TI_blk_F",{},{"ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_emblems_blackwidow'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_emblems_blackwidow";

    };

    class I_BTArmy_Assassin_01 : I_BTArmy_Rifleman_01 {
        author = "Wyvern Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "Assassin";
        side = 2;
        faction = "I_BTArmy";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "U_O_R_Gorka_01_black_F";

        linkedItems[] = {"V_BandollierB_blk","H_HeadSet_black_F","ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_BandollierB_blk","H_HeadSet_black_F","ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch"};

        weapons[] = {"JLTS_E5S","JLTS_RG4D"};
        respawnWeapons[] = {"JLTS_E5S","JLTS_RG4D"};

        magazines[] = {"JLTS_E5S_mag","JLTS_RG4D_mag","JLTS_E5S_mag","JLTS_RG4D_mag"};
        respawnMagazines[] = {"JLTS_E5S_mag","JLTS_RG4D_mag","JLTS_E5S_mag","JLTS_RG4D_mag"};

        backpack = "B_Messenger_Black_F";

        ALiVE_orbatCreator_loadout[] = {{"JLTS_E5S","","","",{"JLTS_E5S_mag",20},{},""},{},{"JLTS_RG4D","","","",{"JLTS_RG4D_mag",15},{},""},{"U_O_R_Gorka_01_black_F",{{"ACE_elasticBandage",10},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_epinephrine",1},{"ACE_morphine",1},{"ACE_tourniquet",2},{"ACE_EntrenchingTool",1},{"ACE_IR_Strobe_Item",1}}},{"V_BandollierB_blk",{{"JLTS_E5S_mag",8,20}}},{"B_Messenger_Black_F",{{"ACE_SpraypaintBlack",1},{"442_thermal_det_mag",2,1},{"3AS_SmokeGreen",2,1},{"3AS_SmokeWhite",2,1},{"3AS_SmokeBlue",2,1},{"JLTS_E5S_mag",6,20},{"JLTS_RG4D_mag",5,15}}},"H_HeadSet_black_F","G_Balaclava_TI_blk_F",{},{"ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_emblems_blackwidow'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_emblems_blackwidow";

    };

    class I_BTArmy_Diplomat_Guard_01 : I_BTArmy_Rifleman_01 {
        author = "Wyvern Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "Diplomat Guard";
        side = 2;
        faction = "I_BTArmy";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "OPTRE_UNSC_Dress_Uniform_odst";

        linkedItems[] = {"OPTRE_UNSC_M52A_Armor_Sniper_URB","H_Beret_blk","ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"OPTRE_UNSC_M52A_Armor_Sniper_URB","H_Beret_blk","ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch"};

        weapons[] = {"JLTS_E5","SWLW_Westar35SA"};
        respawnWeapons[] = {"JLTS_E5","SWLW_Westar35SA"};

        magazines[] = {"JLTS_E5_mag","SWLW_westar35sa_Mag","JLTS_E5_mag","SWLW_westar35sa_Mag"};
        respawnMagazines[] = {"JLTS_E5_mag","SWLW_westar35sa_Mag","JLTS_E5_mag","SWLW_westar35sa_Mag"};

        backpack = "B_LegStrapBag_black_F";

        ALiVE_orbatCreator_loadout[] = {{"JLTS_E5","","","",{"JLTS_E5_mag",100},{},""},{},{"SWLW_Westar35SA","","","",{"SWLW_westar35sa_Mag",17},{},""},{"OPTRE_UNSC_Dress_Uniform_odst",{{"ACE_elasticBandage",10},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_epinephrine",1},{"ACE_morphine",1},{"ACE_tourniquet",2},{"ACE_EntrenchingTool",1},{"ACE_IR_Strobe_Item",1}}},{"OPTRE_UNSC_M52A_Armor_Sniper_URB",{{"JLTS_E5_mag",10,100},{"SWLW_westar35sa_Mag",3,17}}},{"B_LegStrapBag_black_F",{{"ACE_SpraypaintBlack",1},{"442_thermal_det_mag",2,1},{"3AS_SmokeGreen",2,1},{"3AS_SmokeWhite",2,1},{"3AS_SmokeBlue",2,1},{"SWLW_westar35sa_Mag",6,17}}},"H_Beret_blk","G_Balaclava_TI_blk_F",{},{"ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_emblems_blackwidow'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_emblems_blackwidow";

    };

    class I_BTArmy_Diplomat_01 : I_BTArmy_Rifleman_01 {
        author = "Wyvern Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "Diplomat";
        side = 2;
        faction = "I_BTArmy";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "OPTRE_UNSC_Dress_Uniform_odst";

        linkedItems[] = {"H_Beret_CSAT_01_F","ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"H_Beret_CSAT_01_F","ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        backpack = "B_LegStrapBag_black_F";

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"OPTRE_UNSC_Dress_Uniform_odst",{{"ACE_elasticBandage",10},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_epinephrine",1},{"ACE_morphine",1},{"ACE_tourniquet",2},{"ACE_EntrenchingTool",1},{"ACE_IR_Strobe_Item",1}}},{},{"B_LegStrapBag_black_F",{{"ACE_SpraypaintBlack",1},{"442_thermal_det_mag",2,1},{"3AS_SmokeGreen",2,1},{"3AS_SmokeWhite",2,1},{"3AS_SmokeBlue",2,1}}},"H_Beret_CSAT_01_F","G_Squares_Tinted",{},{"ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_emblems_blackwidow'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_emblems_blackwidow";

    };

    class I_BTArmy_Diplomat_Security_Droid_01 : I_BTArmy_Rifleman_01 {
        author = "Wyvern Studios";
        scope = 2;
        scopeCurator = 2;
        displayName = "Diplomat Security Droid";
        side = 2;
        faction = "I_BTArmy";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "ls_cis_bxDiplomatDroid_uniform";

        linkedItems[] = {"ls_cis_bxCommando_vest","ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch","JLTS_NVG_droid_chip_2"};
        respawnlinkedItems[] = {"ls_cis_bxCommando_vest","ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch","JLTS_NVG_droid_chip_2"};

        weapons[] = {"JLTS_E5"};
        respawnWeapons[] = {"JLTS_E5"};

        magazines[] = {"JLTS_E5_mag","JLTS_E5_mag"};
        respawnMagazines[] = {"JLTS_E5_mag","JLTS_E5_mag"};

        ALiVE_orbatCreator_loadout[] = {{"JLTS_E5","","","",{"JLTS_E5_mag",100},{},""},{},{},{"ls_cis_bxDiplomatDroid_uniform",{{"ACE_elasticBandage",10},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_epinephrine",1},{"ACE_morphine",1},{"ACE_tourniquet",2},{"ACE_EntrenchingTool",1},{"ACE_IR_Strobe_Item",1},{"JLTS_E5_mag",11,100}}},{"ls_cis_bxCommando_vest",{{"JLTS_E5_mag",4,100}}},{},"","",{},{"ItemMap","ItemGPS","SWLB_comlink_hush98_1","ItemCompass","ItemWatch","JLTS_NVG_droid_chip_2"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_emblems_blackwidow'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_emblems_blackwidow";

    };

};